{
  "hash": "29bb1e06fb5af4da821ab975907b1613",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"W6. 정규화 · LDA · 다중분류 · 불균형\"\ndescription: \"Ridge·Lasso·Elastic Net, Fisher LDA, 다중분류 전략, class imbalance\"\nauthor: \"Eunji Ha\"\ndate: today\n\n# ── AI 채팅 위젯 설정 ──────────────────────────────────────────\nformat:\n  html:\n    include-in-header:\n      text: |\n        <meta name=\"ai-title\" content=\"W6. 정규화 · LDA · 다중분류 · 불균형\">\n        <meta name=\"ai-context\" content=\"\n        이 챕터는 선형 모델의 네 가지 확장을 다룹니다.\n        첫째 정규화입니다. p > n이면 X^T X의 역행렬이 없어 최소제곱법이 실패하지만,\n        Ridge는 대각선에 lambda를 더해 (X^T X + lambda I)^-1로 항상 풀립니다.\n        Ridge(L2)는 계수를 0에 가깝게 줄이지만 0으로 만들지는 않고,\n        Lasso(L1)는 정확히 0으로 만들어 feature selection 효과가 있습니다.\n        p=500, 진짜 신호 10개인 데이터에서 Lasso는 39개를 고르며 진짜 10개를 모두 포함하고,\n        Ridge는 500개 전부를 0이 아닌 값으로 둡니다. Elastic Net은 둘의 절충입니다.\n        lambda는 교차검증으로 고르며 lambda.min과 lambda.1se가 있습니다.\n        둘째 LDA입니다. Fisher LDA는 between-class 분산은 키우고 within-class 분산은 줄이는\n        방향으로 데이터를 정사영합니다. PCA와 달리 supervised이며, 분산이 큰 축과\n        class를 가르는 축이 다를 때 PCA는 실패합니다. 실습에서 PC1 투영의 t = 1.92,\n        LD1 투영의 t = 16.2로 8배 차이가 납니다.\n        셋째 다중분류로 One-vs-One, One-vs-Rest, ECOC, softmax를 다룹니다.\n        넷째 class imbalance입니다. 유병률 7%에서 기본 임계값 0.5는 recall 0.131에 그치고,\n        임계값을 0.225로 조정하면 F1이 0.209에서 0.344로 오르면서 Brier score는 그대로입니다.\n        반면 1:1 다운샘플링은 recall은 0.793으로 높지만 F1은 0.301이고\n        Brier score가 0.058에서 0.180으로 3배 악화됩니다.\n        즉 확률이 필요하면 재샘플링이 아니라 threshold moving을 써야 합니다\n        (van den Goorbergh et al. 2022).\n        \">\n---\n\n::: {.callout-note}\n## 🎯 Learning objectives\n\n-   $p \\gg n$ 에서 최소제곱법이 실패하는 이유와 정규화의 해결 원리를 설명할 수 있다\n-   **Ridge와 Lasso의 차이를 기하학적으로 설명하고 상황에 맞게 고를 수 있다**\n-   λ를 교차검증으로 선택하고 `lambda.min`과 `lambda.1se`를 구분할 수 있다\n-   LDA의 목적함수를 설명하고 PCA와의 차이를 말할 수 있다\n-   다중분류 전략(OvO / OvR / ECOC / softmax)을 비교할 수 있다\n-   **class imbalance에서 재샘플링과 threshold moving의 대가를 비교할 수 있다**\n:::\n\n> 🤔 **유전자 20,000개, 환자 100명. $(X^{\\mathsf{T}}X)^{-1}$ 이 존재하지 않는데 계수를 어떻게 구하나?**\n\n------------------------------------------------------------------------\n\n## 1. 왜 정규화인가 🔒\n\n### 1) W5가 남긴 문제\n\n-   최소제곱법의 해는 $\\hat{\\mathbf{w}} = (X^{\\mathsf{T}}X)^{-1}X^{\\mathsf{T}}\\mathbf{y}$\n-   $X^{\\mathsf{T}}X$ 는 $p \\times p$ 행렬. **rank는 최대 $n$**\n-   $p > n$ 이면 rank 부족 → **역행렬 없음** → 해가 무수히 많음\n-   $p < n$ 이어도 다중공선성이 심하면 거의 특이행렬 → 계수가 폭주\n\n### 2) 🧪 실습: OLS는 실패하고 Ridge는 작동한다\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nn <- 30; p <- 50                       # p > n\nX <- matrix(rnorm(n * p), n, p)\nbeta_true <- c(rep(2, 5), rep(0, p - 5))   # 진짜 신호는 5개뿐\ny <- as.vector(X %*% beta_true) + rnorm(n, sd = 1)\n\n# 최소제곱법 (W5의 normal equation) — 결과 문자열은 ASCII로 (로케일 안전)\nols <- try(solve(t(X) %*% X) %*% t(X) %*% y, silent = TRUE)\nif (inherits(ols, \"try-error\")) \"OLS FAILED: X'X is singular\" else \"OLS succeeded\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"OLS FAILED: X'X is singular\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ridge: 대각선에 lambda를 더하는 것만으로 항상 역행렬이 존재\nridge_closed <- function(X, y, lambda) {\n  solve(t(X) %*% X + lambda * diag(ncol(X))) %*% t(X) %*% y\n}\n\ndo.call(rbind, lapply(c(0.1, 1, 10), function(lam) {\n  w <- ridge_closed(X, y, lam)\n  data.frame(lambda = lam,\n             norm_w        = round(sqrt(sum(w^2)), 3),\n             mean_signal   = round(mean(w[1:5]), 3),      # 진짜 신호 5개\n             mean_noise    = round(mean(abs(w[6:p])), 3)) # 나머지 45개\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lambda norm_w mean_signal mean_noise\n1    0.1  3.435       1.103      0.262\n2    1.0  3.308       1.061      0.253\n3   10.0  2.595       0.817      0.205\n```\n\n\n:::\n:::\n\n\n-   $\\lambda$ 를 더하는 것만으로 **항상 역행렬이 존재** — 수학적으로 문제가 사라짐\n-   $\\lambda$ 가 커질수록 계수 전체가 0 쪽으로 수축(shrinkage)\n-   진짜 신호와 잡음의 크기 차이는 유지됨\n\n### 3) 벌점의 아이디어\n\n$$\\text{최소화 대상} = \\underbrace{\\text{Loss}(\\mathbf{w})}_{\\text{데이터에 맞추기}} + \\underbrace{\\lambda \\cdot \\text{Penalty}(\\mathbf{w})}_{\\text{모델을 단순하게}}$$\n\n-   $\\lambda = 0$ — 기존 최소제곱법\n-   $\\lambda \\to \\infty$ — 모든 계수가 0\n-   **W1의 Occam's razor를 수식으로 옮긴 것**\n-   $\\lambda$ 는 hyper-parameter → 교차검증으로 결정(W3)\n\n------------------------------------------------------------------------\n\n## 2. Ridge, Lasso, Elastic Net 📉\n\n### 1) Ridge (L2 penalty)\n\n$$\\min_{\\mathbf{w}} \\; \\|\\mathbf{y} - X\\mathbf{w}\\|^2 + \\lambda \\sum_{j=1}^{p} w_j^2$$\n\n-   계수를 **0에 가깝게** 줄이지만 정확히 0으로 만들지는 않음\n-   상관된 feature들에게 **가중치를 고르게 나눠 줌**\n-   닫힌 해 존재 — $(X^{\\mathsf{T}}X + \\lambda I)^{-1}X^{\\mathsf{T}}\\mathbf{y}$\n-   다중공선성 대응에 강함\n\n### 2) Lasso (L1 penalty)\n\n$$\\min_{\\mathbf{w}} \\; \\|\\mathbf{y} - X\\mathbf{w}\\|^2 + \\lambda \\sum_{j=1}^{p} |w_j|$$\n\n-   계수를 **정확히 0으로** 만듦 → **내장된 feature selection**(W2의 embedded)\n-   닫힌 해 없음 — 좌표하강법 등 반복 알고리즘\n-   상관된 feature 그룹에서 **하나만 골라 나머지를 버림**\n\n### 3) 왜 L1만 0을 만드는가\n\n-   벌점을 제약으로 바꿔 보면 — L2는 **원**, L1은 **마름모**\n-   손실함수의 등고선이 제약 영역과 처음 닿는 지점이 해\n-   마름모는 **꼭짓점이 축 위에** 있음 → 닿기 쉬운 곳이 곧 $w_j = 0$\n-   원은 매끄러워 축에 닿을 확률이 사실상 0\n\n### 4) Elastic Net\n\n$$\\lambda\\Big[\\alpha \\sum |w_j| + \\tfrac{1}{2}(1-\\alpha)\\sum w_j^2\\Big]$$\n\n-   $\\alpha = 1$ → Lasso, $\\alpha = 0$ → Ridge\n-   상관된 feature를 **그룹으로 함께 선택**(grouping effect)\n-   pathway 단위로 공발현하는 오믹스 데이터에 적합\n\n### 5) 🧪 실습: 희소성 비교\n\n-   feature 500개, 그중 **진짜 신호는 10개**, 샘플 100개\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(glmnet)\n\nset.seed(2026)\nn <- 100; p <- 500\nX <- matrix(rnorm(n * p), n, p)\nbeta_true <- c(rep(1.5, 10), rep(0, p - 10))\ny <- as.vector(X %*% beta_true) + rnorm(n, sd = 1)\n\nset.seed(1)\ncv_lasso <- cv.glmnet(X, y, alpha = 1)\ncv_ridge <- cv.glmnet(X, y, alpha = 0)\ncv_enet  <- cv.glmnet(X, y, alpha = 0.5)\n\n# lambda.min에서 0이 아닌 계수의 위치 (1~10번이 진짜 신호)\nselected <- function(cv) which(coef(cv, s = \"lambda.min\")[-1] != 0)\nfits <- list(\"Lasso (a=1)\"         = cv_lasso,\n             \"Elastic Net (a=0.5)\" = cv_enet,\n             \"Ridge (a=0)\"         = cv_ridge)\n\ndata.frame(\n  model        = names(fits),\n  n_nonzero    = sapply(fits, function(cv) length(selected(cv))),\n  true_signals = sapply(fits, function(cv) sum(selected(cv) <= 10)),\n  false_pos    = sapply(fits, function(cv) sum(selected(cv) >  10)),\n  row.names    = NULL\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                model n_nonzero true_signals false_pos\n1         Lasso (a=1)        39           10        29\n2 Elastic Net (a=0.5)        50           10        40\n3         Ridge (a=0)       500           10       490\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 위쪽 여백을 넉넉히 — glmnet은 상단 축에 nonzero 개수를 찍으므로 제목과 겹침\npar(mfrow = c(1, 2), mar = c(4.5, 4.5, 4.5, 1))\n\nplot(cv_lasso$glmnet.fit, xvar = \"lambda\")\ntitle(\"Lasso (L1)\", line = 3)\nabline(v = log(cv_lasso$lambda.min), lty = 2)\n\nplot(cv_ridge$glmnet.fit, xvar = \"lambda\")\ntitle(\"Ridge (L2)\", line = 3)\nabline(v = log(cv_ridge$lambda.min), lty = 2)\n```\n\n::: {.cell-output-display}\n![](06_regularization_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n\n-   **Lasso** — 500개 중 39개만 살림. 진짜 신호 **10개를 모두 포함**, 위양성 29개\n-   **Ridge** — 500개 전부 0이 아님. 선택 기능 없음\n-   **Elastic Net** — 50개. 둘의 중간\n-   coefficient path 그림 — 왼쪽은 계수들이 하나씩 **0에서 이탈**, 오른쪽은 전부 매끄럽게 수축\n\n### 6) λ 선택\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  criterion = c(\"lambda.min\", \"lambda.1se\"),\n  lambda    = round(c(cv_lasso$lambda.min, cv_lasso$lambda.1se), 4),\n  n_nonzero = c(sum(coef(cv_lasso, s = \"lambda.min\")[-1] != 0),\n                sum(coef(cv_lasso, s = \"lambda.1se\")[-1] != 0))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   criterion lambda n_nonzero\n1 lambda.min 0.1618        39\n2 lambda.1se 0.2699        18\n```\n\n\n:::\n:::\n\n\n-   **`lambda.min`** — CV 오차가 최소인 지점. 성능 우선\n-   **`lambda.1se`** — 최소에서 표준오차 1개 이내의 가장 강한 벌점. **더 단순한 모델**\n-   바이오마커 패널처럼 **변수 수를 줄이는 것이 목적이면 `lambda.1se`**\n\n### 7) ⚠️ 반드시 지킬 것\n\n-   **표준화 필수** — 벌점이 계수 크기에 비례하므로 단위가 큰 변수만 벌을 받음\n    -   `glmnet`은 기본으로 표준화 후 원래 스케일로 되돌려 줌\n-   **λ 선택도 학습** — 전체 데이터로 λ를 고르고 같은 CV로 성능을 보고하면 낙관 편향(W3)\n    -   → **nested CV** 또는 별도 test set\n-   **선택된 변수는 불안정** — 표본을 바꾸면 목록이 달라짐\n    -   여러 fold에서 반복 선택된 변수만 보고할 것(W14)\n\n------------------------------------------------------------------------\n\n## 3. Linear Discriminant Analysis 📐\n\n### 1) 아이디어\n\n-   전통적 선형 학습법. 이진 분류에서는 **Fisher discriminant analysis**\n-   데이터를 **직선 하나에 정사영**했을 때 class가 가장 잘 갈리는 방향 $\\mathbf{w}$ 를 찾음\n-   정사영한 값이 기준값보다 크면 class 1, 작으면 class 2\n\n### 2) 목적함수\n\n$$J(\\mathbf{w}) = \\frac{\\mathbf{w}^{\\mathsf{T}}S_B\\mathbf{w}}{\\mathbf{w}^{\\mathsf{T}}S_W\\mathbf{w}}$$\n\n-   $S_B = (\\mathbf{m}_1 - \\mathbf{m}_2)(\\mathbf{m}_1 - \\mathbf{m}_2)^{\\mathsf{T}}$ — **between-class** 산포\n-   $S_W = \\sum_i \\sum_{\\mathbf{x} \\in C_i} (\\mathbf{x} - \\mathbf{m}_i)(\\mathbf{x} - \\mathbf{m}_i)^{\\mathsf{T}}$ — **within-class** 산포\n-   해석 — **class 평균은 멀어지고, class 내부는 뭉치도록**\n\n### 3) 풀이\n\n-   $J(\\mathbf{w})$ 를 최대화 → 일반화 고유값 문제\n-   해는 $\\mathbf{w} \\propto S_W^{-1}(\\mathbf{m}_1 - \\mathbf{m}_2)$\n-   ⚠️ $S_W^{-1}$ 이 필요 → **$p > n$ 이면 LDA도 실패** → 정규화 LDA, 대각 LDA\n\n### 4) 🧪 실습: LDA vs PCA — 분산이 큰 축이 정답인가\n\n-   분산이 **가장 큰 방향은 class와 무관**하고, class 차이는 분산이 작은 방향에 숨겨진 데이터\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nlibrary(ggplot2)\n\nset.seed(2026)\nn <- 200\ng  <- rep(c(\"A\", \"B\"), each = n / 2)\nz1 <- rnorm(n, sd = 3)                                  # 분산 큼, class와 무관\nz2 <- rnorm(n, sd = 1) + ifelse(g == \"A\", -1.2, 1.2)    # 분산 작음, class 정보\n\nd <- data.frame(x1 = z1 + z2, x2 = z1 - z2, g = factor(g))\n\npca <- prcomp(d[, 1:2], scale. = FALSE)\nlda_fit <- lda(g ~ x1 + x2, data = d)\n\nunit <- function(v) v / sqrt(sum(v^2))\nproject <- function(v) {\n  s <- as.matrix(d[, 1:2]) %*% v\n  abs(t.test(s ~ d$g)$statistic)\n}\n\ndata.frame(\n  axis        = c(\"PC1 (unsupervised)\", \"LD1 (supervised)\"),\n  direction   = c(paste(round(unit(pca$rotation[, 1]), 3), collapse = \", \"),\n                  paste(round(unit(lda_fit$scaling[, 1]), 3), collapse = \", \")),\n  separation_t = round(c(project(pca$rotation[, 1]),\n                         project(lda_fit$scaling[, 1])), 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                axis     direction separation_t\n1 PC1 (unsupervised)  0.751, 0.661         1.92\n2   LD1 (supervised) 0.726, -0.688        16.20\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctr <- colMeans(d[, 1:2])\nv_pc <- unit(pca$rotation[, 1]); v_ld <- unit(lda_fit$scaling[, 1])\n\np_scatter <- ggplot(d, aes(x1, x2, colour = g)) +\n  geom_point(alpha = .6, size = 1.2) +\n  geom_abline(slope = v_pc[2] / v_pc[1],\n              intercept = ctr[2] - v_pc[2] / v_pc[1] * ctr[1],\n              linetype = 2, linewidth = .8) +\n  geom_abline(slope = v_ld[2] / v_ld[1],\n              intercept = ctr[2] - v_ld[2] / v_ld[1] * ctr[1],\n              linewidth = .8) +\n  scale_colour_manual(values = c(A = \"#2e8b7a\", B = \"#d1495b\")) +\n  coord_equal() + theme_minimal() +\n  labs(colour = NULL, caption = \"dashed = PC1   |   solid = LD1\")\n\nproj_df <- rbind(\n  data.frame(axis = \"PC1 (unsupervised)\",\n             value = as.vector(as.matrix(d[, 1:2]) %*% v_pc), g = d$g),\n  data.frame(axis = \"LD1 (supervised)\",\n             value = as.vector(as.matrix(d[, 1:2]) %*% v_ld), g = d$g)\n)\nproj_df$axis <- factor(proj_df$axis, levels = c(\"PC1 (unsupervised)\", \"LD1 (supervised)\"))\n\nggplot(proj_df, aes(value, fill = g)) +\n  geom_density(alpha = .55, colour = NA) +\n  facet_wrap(~ axis, scales = \"free\") +\n  scale_fill_manual(values = c(A = \"#2e8b7a\", B = \"#d1495b\")) +\n  labs(x = \"Projected value\", y = \"Density\", fill = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](06_regularization_files/figure-html/unnamed-chunk-7-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_scatter\n```\n\n::: {.cell-output-display}\n![](06_regularization_files/figure-html/unnamed-chunk-8-1.png){width=480}\n:::\n:::\n\n\n-   두 방향이 **거의 직교** — PC1 (0.751, 0.661), LD1 (0.726, −0.688)\n-   PC1 투영 $t = 1.92$ (거의 겹침) vs LD1 투영 $t = 16.2$ — **8배 차이**\n-   **PCA는 label을 보지 않는다.** 분산이 큰 축이 관심 있는 축이라는 보장은 없음\n\n### 5) 가정과 한계\n\n-   각 class가 **같은 공분산 구조**를 갖는다고 가정 → 다르면 QDA\n-   class당 평균이 비슷하면 무력 (W13의 PCA vs LDA 비교와 연결)\n-   장점 — 차원 축소와 분류를 동시에, 계산이 매우 빠름\n\n------------------------------------------------------------------------\n\n## 4. 다중분류 🔢\n\nclass가 $N$ 개일 때, 이진 분류기를 조합해 푸는 전략들.\n\n| 전략 | 분류기 수 | 학습 방식 | 특징 |\n|------|-----------|----------|------|\n| **One-vs-One (OvO)** | $N(N-1)/2$ | class 쌍마다 하나 | 분류기는 많지만 각각 작고 빠름. 투표로 결정 |\n| **One-vs-Rest (OvR)** | $N$ | 한 class vs 나머지 전부 | 분류기 수가 적음. **각 문제가 불균형해짐** |\n| **ECOC** | 설계에 따름 | 코드워드로 인코딩 | 일부 분류기가 틀려도 **오류 정정** 가능 |\n| **Softmax** | 1 | 확률을 동시에 추정 | 확률의 합이 1. 로지스틱의 자연스러운 확장 |\n\n-   **OvR** — class 수가 많으면 각 이진 문제의 양성 비율이 $1/N$ → 5절의 불균형 문제 발생\n-   **ECOC** — 각 class에 이진 코드워드를 부여, 해밍 거리로 판정. 코드 설계가 성능을 좌우\n-   **Softmax** — $P(y = k \\mid \\mathbf{x}) = e^{z_k} / \\sum_j e^{z_j}$. 확률이 필요하면 기본 선택\n-   실무 — 대부분의 라이브러리가 자동 처리하지만, **어느 방식인지 확인할 것**(확률 해석이 달라짐)\n\n------------------------------------------------------------------------\n\n## 5. Class Imbalance ⚖️\n\n### 1) 문제\n\n-   training sample의 class 분포가 크게 치우친 상태 (희귀질환, 약물 반응자)\n-   기본 임계값 0.5는 **다수 class에 유리하게 맞춰져 있음**\n-   결과 — 소수 class를 거의 예측하지 못함 (W4의 accuracy paradox)\n\n### 2) Threshold moving\n\n-   모델은 그대로 두고 **판정 기준만 옮김**\n-   odds에 class 비율을 보정\n\n$$\\frac{y'}{1-y'} = \\frac{y}{1-y} \\times \\frac{m^-}{m^+}$$\n\n-   $m^+, m^-$ — 소수·다수 class의 샘플 수\n-   또는 **training fold에서 F1·비용을 최대화하는 임계값을 직접 탐색**\n-   ✅ **예측확률을 건드리지 않음** → 보정(calibration)이 유지됨\n\n### 3) Undersampling\n\n-   다수 class를 줄여 비율을 맞춤\n-   단점 — 정보 손실\n-   **EasyEnsemble** — 다수 class를 여러 부분집합으로 나눠 각각 학습 후 ensemble (W9)\n\n### 4) Oversampling\n\n-   소수 class를 늘림\n-   **SMOTE** — 소수 class 샘플 사이를 **보간**해 합성 샘플 생성\n-   단점 — 합성 샘플이 실제 분포를 왜곡, 고차원에서 특히 불안정\n\n### 5) 🧪 실습: 세 전략의 대가\n\n-   유병률 약 7%, 로지스틱 회귀 하나로 세 전략을 비교\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nn <- 4000\nd <- data.frame(x1 = rnorm(n), x2 = rnorm(n))\nd$y <- rbinom(n, 1, plogis(-3.2 + 1.2 * d$x1 + 0.8 * d$x2))\ntr <- 1:2000; te <- 2001:4000\n\nf1 <- function(pred, act) {\n  tp <- sum(pred == 1 & act == 1); fp <- sum(pred == 1 & act == 0)\n  fn <- sum(pred == 0 & act == 1)\n  if (tp == 0) return(0)\n  p <- tp / (tp + fp); r <- tp / (tp + fn); 2 * p * r / (p + r)\n}\nreport <- function(p, thr, act, name) {\n  pred <- as.integer(p > thr); tp <- sum(pred == 1 & act == 1)\n  data.frame(strategy = name, threshold = round(thr, 3), n_flagged = sum(pred),\n             recall = round(tp / sum(act == 1), 3),\n             precision = round(tp / max(sum(pred), 1), 3),\n             F1 = round(f1(pred, act), 3),\n             mean_pred = round(mean(p), 3),\n             Brier = round(mean((p - act)^2), 4))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm    <- glm(y ~ x1 + x2, data = d[tr, ], family = binomial)\np_te <- predict(m, d[te, ], type = \"response\")\np_tr <- predict(m, d[tr, ], type = \"response\")\n\n# ② training fold에서 F1을 최대화하는 임계값 탐색\nthrs <- seq(0.01, 0.9, by = 0.005)\nbest <- thrs[which.max(sapply(thrs, function(t) f1(as.integer(p_tr > t), d$y[tr])))]\n\n# ③ 다수 class를 1:1로 다운샘플링 후 학습\npos  <- tr[d$y[tr] == 1]\nneg  <- sample(tr[d$y[tr] == 0], length(pos))\nm_bal <- glm(y ~ x1 + x2, data = d[c(pos, neg), ], family = binomial)\np_bal <- predict(m_bal, d[te, ], type = \"response\")\n\nrbind(\n  report(p_te,  0.5,  d$y[te], \"1. Default threshold 0.5\"),\n  report(p_te,  best, d$y[te], \"2. Tuned threshold\"),\n  report(p_bal, 0.5,  d$y[te], \"3. Downsample 1:1\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  strategy threshold n_flagged recall precision    F1 mean_pred\n1 1. Default threshold 0.5     0.500        37  0.131     0.514 0.209     0.081\n2       2. Tuned threshold     0.225       186  0.393     0.306 0.344     0.081\n3        3. Downsample 1:1     0.500       619  0.793     0.186 0.301     0.366\n   Brier\n1 0.0575\n2 0.0575\n3 0.1798\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsweep <- data.frame(threshold = thrs,\n                    F1 = sapply(thrs, function(t) f1(as.integer(p_te > t), d$y[te])))\n\nggplot(sweep, aes(threshold, F1)) +\n  geom_line(linewidth = .9, colour = \"#d1495b\") +\n  geom_vline(xintercept = best, linetype = 2) +\n  geom_vline(xintercept = 0.5, linetype = 3, colour = \"grey40\") +\n  labs(x = \"Decision threshold\", y = \"F1 (test set)\",\n       caption = \"dashed = tuned on training   |   dotted = default 0.5\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](06_regularization_files/figure-html/unnamed-chunk-11-1.png){width=624}\n:::\n:::\n\n\n-   **기본 0.5** — 실제 환자의 **13%만** 찾아냄. F1 0.209\n-   **임계값 조정** — F1 0.344로 개선. 그리고 **Brier score는 0.0575 그대로**\n-   **다운샘플링** — recall 0.793으로 가장 높지만 precision 0.186, F1은 0.301로 오히려 낮음\n    -   평균 예측확률 0.366 vs 실제 유병률 0.072 → **Brier 0.0575 → 0.1798로 3배 악화**\n-   ✅ **임계값 조정이 성능도 좋고 확률도 지킨다**\n\n::: {.callout-warning}\n## ⚠️ 불균형 처리의 원칙\n\n-   **확률이 필요한가?** 임상 위험도·자원 배분에 쓸 것이면 → 재샘플링 금지, threshold moving\n-   **순위만 필요한가?** 상위 k개만 뽑을 것이면 → 재샘플링도 무방(하지만 이득도 적음)\n-   재샘플링을 했다면 **반드시 재보정**(W4의 Platt scaling / isotonic)\n-   재샘플링은 **전처리다** — training fold 안에서만(W2). test fold에는 절대 적용 금지\n-   불균형 그 자체는 문제가 아니다. **문제는 임계값과 지표 선택**\n:::\n\n::: {.callout-important}\n## Where this ends up\n\n-   Ridge·Lasso의 벌점이 사실 **prior**라는 것 → W11 (MAP)\n-   EasyEnsemble, 그리고 variance를 깎는 전략 → W9\n-   LDA의 정사영 아이디어 → W13 (PCA vs LDA)\n-   선택된 변수의 안정성 보고 → W14\n:::\n\n------------------------------------------------------------------------\n\n## 📝 Summary\n\n-   $p > n$ 이면 $X^{\\mathsf{T}}X$ 의 역행렬이 없음 → **대각선에 λ를 더하면 항상 풀림**\n-   **Ridge(L2)** — 0에 가깝게 수축, 상관 변수에 가중치 분산, 다중공선성에 강함\n-   **Lasso(L1)** — 정확히 0으로. 마름모 제약의 **꼭짓점이 축 위**에 있기 때문\n-   실습 — 500개 중 Lasso는 39개 선택(진짜 10개 모두 포함), Ridge는 500개 전부 유지\n-   **Elastic Net** — 상관된 feature를 그룹으로 선택. 오믹스에 적합\n-   λ는 CV로 — 변수 수를 줄이려면 **`lambda.1se`**\n-   **LDA는 supervised, PCA는 아니다** — 같은 데이터에서 분리력 $t$ 1.92 vs 16.2\n-   다중분류 — OvR은 각 문제가 불균형해짐, 확률이 필요하면 softmax\n-   **불균형: 임계값 조정이 F1도 올리고 Brier도 지킨다.** 다운샘플링은 확률을 3배 망가뜨림\n\n## 🔑 Key terms\n\n| 용어 | 정의 |\n|------|------|\n| **Shrinkage** | 벌점으로 계수를 0 쪽으로 수축시키는 것 |\n| **Ridge (L2)** | 계수 제곱합 벌점. 0으로 만들지 않음. 닫힌 해 존재 |\n| **Lasso (L1)** | 계수 절댓값합 벌점. 정확히 0을 만듦 (feature selection) |\n| **Elastic Net** | L1·L2 혼합. 상관된 feature를 그룹으로 선택 |\n| **lambda.1se** | CV 최소에서 표준오차 1개 이내의 가장 강한 벌점. 더 단순한 모델 |\n| **S_B / S_W** | between-class / within-class 산포 행렬 |\n| **LDA** | $S_B$ 는 키우고 $S_W$ 는 줄이는 방향으로 정사영하는 supervised 방법 |\n| **OvO / OvR / ECOC** | 다중분류를 이진 분류기 조합으로 푸는 전략 |\n| **Threshold moving** | 모델은 두고 판정 임계값만 조정. 확률을 보존 |\n| **SMOTE** | 소수 class 샘플 사이를 보간해 합성 샘플을 만드는 oversampling |\n\n## ➕ References\n\n-   Hoerl AE, Kennard RW. Ridge regression: biased estimation for nonorthogonal problems. *Technometrics* 1970;12(1):55–67.\n-   Tibshirani R. Regression shrinkage and selection via the lasso. *JRSS-B* 1996;58(1):267–288.\n-   Zou H, Hastie T. Regularization and variable selection via the elastic net. *JRSS-B* 2005;67(2):301–320.\n-   Friedman J, Hastie T, Tibshirani R. Regularization paths for generalized linear models via coordinate descent. *Journal of Statistical Software* 2010;33(1):1–22.\n-   Fisher RA. The use of multiple measurements in taxonomic problems. *Annals of Eugenics* 1936;7(2):179–188.\n-   Dietterich TG, Bakiri G. Solving multiclass learning problems via error-correcting output codes. *JAIR* 1995;2:263–286.\n-   Chawla NV, Bowyer KW, Hall LO, Kegelmeyer WP. SMOTE: Synthetic Minority Over-sampling Technique. *JAIR* 2002;16:321–357.\n-   Liu XY, Wu J, Zhou ZH. Exploratory undersampling for class-imbalance learning. *IEEE TSMC-B* 2009;39(2):539–550.\n-   van den Goorbergh R, van Smeden M, Timmerman D, Van Calster B. The harm of class imbalance corrections for risk prediction models. *JAMIA* 2022;29(9):1525–1534.\n\n------------------------------------------------------------------------\n\n[← W5. 선형회귀와 로지스틱회귀](05_linear_model.qmd)\n",
    "supporting": [
      "06_regularization_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}