{
  "hash": "34e2783a3fbb5990d2ad5059f7aad988",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"W14. 모델 해석과 보고\"\ndescription: \"Variable importance, PDP/ICE, SHAP, 해석 가능한 모델, TRIPOD+AI, 흔한 실수\"\nauthor: \"Eunji Ha\"\ndate: today\n\n# ── AI 채팅 위젯 설정 ──────────────────────────────────────────\nformat:\n  html:\n    include-in-header:\n      text: |\n        <meta name=\"ai-title\" content=\"W14. 모델 해석과 보고\">\n        <meta name=\"ai-context\" content=\"\n        이 챕터는 학습한 모델을 해석하고 논문으로 보고하는 방법을 다룹니다.\n        진짜 생성 규칙을 아는 모의 임상 코호트를 써서 설명이 진실과 맞는지 확인합니다.\n        결과는 log CRP, 남성에서만 작용하는 나이, BMI의 U자 효과, 약한 혈압 효과로 정해지고,\n        lcrp2는 CRP와 상관 0.937인 대리 변수일 뿐 원인이 아니며 lab_x와 flag는 효과가 없습니다.\n        test AUC는 선형 로지스틱 0.6525, spline 로지스틱 0.7597, spline과 age:sex 상호작용 0.7678,\n        rpart 100개로 만든 random forest 0.7481, 진짜 확률 0.7711입니다.\n        불순도 기반 중요도는 효과 없는 연속형 lab_x에 0.052를 줘서 실제 효과가 있는 male 0.017보다 높습니다.\n        test set의 permutation importance는 lab_x에 0을 줍니다. train set으로 재면 lab_x도 0.0173으로 부풀려집니다.\n        서로 상관된 lcrp와 lcrp2는 하나씩 섞으면 0.0560과 -0.0014인데 함께 섞으면 0.0931입니다.\n        하나를 빼고 다시 학습하면 AUC가 거의 안 변합니다. 다른 하나가 대신하기 때문입니다.\n        PDP는 BMI의 U자를 되찾지만 양 끝을 과소평가합니다.\n        ICE는 PDP가 평균 내 가린 개인차를 보여줍니다. random forest는 나이 효과를 남녀 모두에 비슷하게 퍼뜨렸고\n        age:sex를 넣은 GLM은 여성 0.0065, 남성 0.1378로 진실 0과 0.1229에 가깝습니다.\n        SHAP은 협력 게임의 Shapley 값으로 예측을 feature별 기여로 나누고 합이 예측과 기준값의 차이와 정확히 같습니다.\n        선형 모형에서 SHAP은 beta 곱하기 x에서 평균을 뺀 값과 같습니다.\n        SHAP은 모델을 설명하지 세상을 설명하지 않습니다. 원인이 아닌 lcrp2도 SHAP 기여를 받습니다.\n        해석 가능한 모델이 블랙박스만큼 좋으면 해석 가능한 모델을 써야 합니다.\n        TRIPOD+AI는 2024년 BMJ에 발표된 27개 항목의 보고 지침입니다.\n        외부 코호트에서 AUC는 0.8092로 오히려 높았지만 평균 예측 0.4338 대 실제 0.288로 calibration이 크게 어긋났습니다.\n        test set을 200번 재사용해 고른 모델은 test AUC 0.6166인데 새 데이터에서는 0.5140입니다.\n        전체 데이터로 feature를 고른 뒤 CV하면 순수 잡음에서도 AUC 0.8642가 나오고 fold 안에서 고르면 0.4499입니다.\n        유병률 5퍼센트에서 모두 음성이라고 찍으면 정확도 0.9502입니다.\n        \">\n---\n\n::: {.callout-note}\n## 🎯 Learning objectives\n\n-   **불순도 기반 중요도와 permutation importance의 차이를 설명하고, 어느 쪽을 언제 믿을지 말할 수 있다**\n-   상관된 feature가 중요도 해석을 어떻게 망가뜨리는지 설명할 수 있다\n-   PDP와 ICE를 그리고, ICE가 PDP보다 나은 상황을 알아볼 수 있다\n-   **SHAP의 정의와 성질을 설명하고, 한 환자의 예측을 feature별 기여로 분해할 수 있다**\n-   \"모델을 설명하는 것\"과 \"세상을 설명하는 것\"을 구분할 수 있다\n-   **TRIPOD+AI의 핵심 요구사항을 알고, discrimination과 calibration을 함께 보고할 수 있다**\n-   누수, test set 재사용, 불균형 무시 같은 흔한 실수를 코드로 재현하고 피할 수 있다\n:::\n\n> 🤔 **모델이 \"이 환자의 위험을 올린 가장 큰 요인은 CRP\"라고 말한다. 그 말을 믿고 CRP를 낮추면 위험이 줄어들까?**\n\n------------------------------------------------------------------------\n\n## 1. 왜 해석하는가 🔍\n\n### 1) 해석의 목적\n\n| 목적 | 질문 | 예 |\n|---|---|---|\n| **디버깅** | 모델이 엉뚱한 것을 배우지 않았나? | 병원 ID·촬영 기기로 질병을 맞히는 모델 |\n| **과학적 발견** | 어떤 변수가 결과와 관련되는가? | 예후 바이오마커 후보 |\n| **신뢰와 규제** | 임상의·심사자가 받아들일 수 있나? | 의료기기 인허가, 논문 심사 |\n| **개인별 설명** | 이 환자는 왜 고위험인가? | 진료 현장의 의사결정 보조 |\n\n### 2) 해석의 분류\n\n-   **Global vs local** — 모델 전체가 무엇에 기대는가 / 이 한 예측은 왜 이렇게 나왔나\n-   **Model-specific vs model-agnostic** — 트리의 불순도 감소처럼 모델 내부를 쓰는가 / 예측 함수만 있으면 어떤 모델에도 쓸 수 있는가\n-   이 챕터의 permutation importance, PDP, ICE, SHAP은 모두 **model-agnostic**입니다 — `predict()`만 있으면 됩니다\n\n### 3) 🧪 실습: 진실을 아는 모의 코호트\n\n설명이 맞는지 확인하려면 **진짜 규칙을 알아야** 합니다. 결과(예: 30일 내 악화)를 다음 규칙으로 만듭니다.\n\n$$\\text{logit}\\,P(y=1) = -1.3 + 0.9\\,(\\text{lcrp} - 1) + 0.07\\,(\\text{age} - 60)\\cdot\\text{male} + 0.045\\,(\\text{bmi} - 27)^2 + 0.012\\,(\\text{sbp} - 130)$$\n\n-   **lcrp** (log CRP) — 선형 효과\n-   **age** — **남성에서만** 효과 (상호작용)\n-   **bmi** — **U자** 효과 (너무 낮아도, 높아도 위험)\n-   **sbp** — 약한 효과\n-   **lcrp2** — 다른 검사법으로 잰 CRP. lcrp와 강하게 상관되지만 **원인이 아닌 대리 변수**\n-   **lab_x**(연속형), **flag**(이진형) — **효과 없음**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rpart); library(splines)\nsim_clin <- function(n, seed, shift = 0, age_mu = 60) {\n  set.seed(seed)\n  age   <- rnorm(n, age_mu, 10)\n  male  <- rbinom(n, 1, .5)\n  lcrp  <- rnorm(n, 1, .8)\n  lcrp2 <- lcrp + rnorm(n, 0, .3)                 # 대리 변수 (원인 아님)\n  bmi   <- rnorm(n, 27, 4)\n  sbp   <- rnorm(n, 130, 15)\n  lab_x <- rnorm(n)                               # 효과 없음\n  flag  <- rbinom(n, 1, .5)                       # 효과 없음\n  eta <- -1.3 + shift + 0.9 * (lcrp - 1) + 0.07 * (age - 60) * male +\n         0.045 * (bmi - 27)^2 + 0.012 * (sbp - 130)\n  y <- rbinom(n, 1, plogis(eta))\n  data.frame(age, male, lcrp, lcrp2, bmi, sbp, lab_x, flag, y, p_true = plogis(eta))\n}\ntrue_eta <- function(d) -1.3 + 0.9 * (d$lcrp - 1) + 0.07 * (d$age - 60) * d$male +\n                         0.045 * (d$bmi - 27)^2 + 0.012 * (d$sbp - 130)\nfeats <- c(\"age\", \"male\", \"lcrp\", \"lcrp2\", \"bmi\", \"sbp\", \"lab_x\", \"flag\")\ntr <- sim_clin(1000, 1); te <- sim_clin(2000, 2)\nc(prevalence_train = round(mean(tr$y), 3), prevalence_test = round(mean(te$y), 3),\n  cor_lcrp_lcrp2 = round(cor(tr$lcrp, tr$lcrp2), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprevalence_train  prevalence_test   cor_lcrp_lcrp2 \n           0.373            0.391            0.937 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nauc <- function(p, y) {                          # Mann-Whitney 로 계산한 AUC\n  r <- rank(p); n1 <- sum(y == 1); n0 <- sum(y == 0)\n  (sum(r[y == 1]) - n1 * (n1 + 1) / 2) / (n1 * n0)\n}\n## 블랙박스 : rpart 100개로 만든 random forest (W9)\nrf_fit <- function(d, feats, ntree = 100, mtry = 6, seed = 1) {\n  set.seed(seed)\n  lapply(seq_len(ntree), function(b) {\n    idx <- sample(nrow(d), replace = TRUE); f <- sample(feats, mtry)\n    rpart(reformulate(f, \"y\"), data = d[idx, c(f, \"y\")], method = \"anova\",\n          control = rpart.control(cp = 0.001, minbucket = 20, xval = 0, maxsurrogate = 0))\n  })\n}\nrf_pred <- function(m, newdata) rowMeans(sapply(m, predict, newdata = newdata))\nrf <- rf_fit(tr, feats)\npf <- function(d) rf_pred(rf, d)                 # 해석 도구에 넘길 \"예측 함수\"\n\nm_lin <- glm(y ~ age + male + lcrp + lcrp2 + bmi + sbp + lab_x + flag, data = tr, family = binomial)\nm_spl <- glm(y ~ ns(age, 3) + male + ns(lcrp, 3) + lcrp2 + ns(bmi, 3) + ns(sbp, 3) + lab_x + flag,\n             data = tr, family = binomial)\nm_int <- glm(y ~ ns(age, 3) * male + ns(lcrp, 3) + lcrp2 + ns(bmi, 3) + ns(sbp, 3) + lab_x + flag,\n             data = tr, family = binomial)\ndata.frame(model = c(\"logistic (linear)\", \"logistic + splines\", \"logistic + splines + age:sex\",\n                     \"random forest (100 rpart trees)\", \"true probability (ceiling)\"),\n           test_AUC = round(c(auc(predict(m_lin, te), te$y), auc(predict(m_spl, te), te$y),\n                              auc(predict(m_int, te), te$y), auc(pf(te), te$y),\n                              auc(te$p_true, te$y)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            model test_AUC\n1               logistic (linear)   0.6525\n2              logistic + splines   0.7597\n3    logistic + splines + age:sex   0.7678\n4 random forest (100 rpart trees)   0.7481\n5      true probability (ceiling)   0.7711\n```\n\n\n:::\n:::\n\n\n-   진짜 확률로도 AUC **0.7711**이 상한입니다 (W11의 Bayes 상한)\n-   선형 로지스틱은 U자와 상호작용을 못 잡아 **0.6525**\n-   **random forest(0.7481)가 spline 로지스틱(0.7597)보다 낮습니다.** 5절에서 다시 이야기합니다\n-   이제 random forest를 \"블랙박스\"로 두고, 해석 도구들이 진실을 얼마나 되찾는지 봅니다\n\n------------------------------------------------------------------------\n\n## 2. Variable importance 📊\n\n### 1) 두 가지 중요도\n\n**불순도 기반 (impurity / Gini / MDI)** — 트리에서 그 변수로 나눌 때 줄어든 불순도(회귀는 SSE)를 모든 split·모든 트리에 걸쳐 합친 것. **학습 데이터로** 계산되고 공짜로 나옵니다.\n\n**Permutation importance** — **test set에서** 그 변수 하나만 무작위로 섞었을 때 성능이 얼마나 떨어지는가.\n\n$$\\text{PI}_j = \\text{AUC}(\\text{원래}) - \\text{AUC}(x_j \\text{를 섞은 데이터})$$\n\n섞으면 $x_j$ 와 $y$ 의 관계가 끊어지므로, 모델이 $x_j$ 에 기대고 있었다면 성능이 떨어집니다.\n\n### 2) 🧪 실습: 효과 없는 변수를 누가 잡아내나\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimp_impurity <- sapply(feats, function(v) sum(sapply(rf, function(t)\n  if (v %in% names(t$variable.importance)) t$variable.importance[[v]] else 0)))\nimp_impurity <- imp_impurity / sum(imp_impurity)                 # 비율로\n\nperm_imp <- function(pred_fun, d, feats, R = 5, seed = 1, groups = NULL) {\n  set.seed(seed); base <- auc(pred_fun(d), d$y)\n  items <- if (is.null(groups)) as.list(feats) else groups\n  sapply(items, function(g) mean(replicate(R, {\n    dp <- d; idx <- sample(nrow(d)); dp[g] <- d[idx, g, drop = FALSE]   # g 만 섞는다\n    base - auc(pred_fun(dp), d$y)\n  })))\n}\npi_test  <- perm_imp(pf, te, feats)\npi_train <- perm_imp(pf, tr, feats)\nimp_tab <- data.frame(feature = feats,\n  true_effect = c(\"yes (male only)\", \"yes (via age)\", \"yes\", \"no (proxy)\", \"yes (U-shape)\",\n                  \"yes (weak)\", \"no\", \"no\"),\n  impurity_share = round(imp_impurity, 3),\n  perm_AUC_drop_test = round(pi_test, 4), perm_AUC_drop_train = round(pi_train, 4),\n  row.names = NULL)\nimp_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  feature     true_effect impurity_share perm_AUC_drop_test perm_AUC_drop_train\n1     age yes (male only)          0.148             0.0233              0.0694\n2    male   yes (via age)          0.017             0.0030              0.0059\n3    lcrp             yes          0.226             0.0581              0.1113\n4   lcrp2      no (proxy)          0.110             0.0013              0.0215\n5     bmi   yes (U-shape)          0.368             0.1283              0.1710\n6     sbp      yes (weak)          0.074             0.0042              0.0303\n7   lab_x              no          0.052             0.0000              0.0173\n8    flag              no          0.005            -0.0001              0.0020\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\neff <- ifelse(feats %in% c(\"lcrp2\", \"lab_x\", \"flag\"), \"no causal effect\", \"has effect\")\nil <- rbind(data.frame(feature = feats, v = imp_impurity, what = \"impurity share (train)\", eff = eff),\n            data.frame(feature = feats, v = pi_test, what = \"permutation AUC drop (test)\", eff = eff))\nil$what <- factor(il$what, levels = c(\"impurity share (train)\", \"permutation AUC drop (test)\"))\nil$feature <- factor(il$feature, levels = rev(feats))\nggplot(il, aes(v, feature, fill = eff)) + geom_col(width = .7) +\n  facet_wrap(~ what, scales = \"free_x\") +\n  scale_fill_manual(values = c(\"has effect\" = \"#2e8b7a\", \"no causal effect\" = \"#d1495b\")) +\n  labs(x = NULL, y = NULL, fill = NULL) + theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](14_interpretation_files/figure-html/unnamed-chunk-4-1.png){width=729.6}\n:::\n:::\n\n\n-   효과 없는 연속형 **lab_x가 불순도 중요도 0.052**를 받아, 실제 효과가 있는 **male(0.017)보다 높습니다**\n-   같은 \"효과 없음\"인 이진형 **flag는 0.005** — 연속형은 나눌 지점이 수백 개라 **우연히 좋아 보이는 split을 찾을 기회가 많기 때문**입니다 (Strobl et al. 2007)\n-   test set의 permutation importance는 lab_x **0.0000**, flag **-0.0001** — 정확히 걸러냅니다\n-   ⚠️ **train set으로 permutation importance를 재면 lab_x도 0.0173**. 모델이 학습 데이터의 잡음까지 외운 만큼 부풀려집니다. **반드시 test(또는 OOB) 데이터로**\n-   male의 중요도가 작게 나오는 것은 male이 **age를 통해서만** 작용하기 때문입니다 — 중요도는 상호작용을 한 변수에 깔끔하게 배분하지 못합니다\n\n### 3) 🧪 실습: 상관된 변수의 함정\n\nlcrp와 lcrp2는 상관 0.937. 모델은 둘 중 아무거나 써도 됩니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrp <- perm_imp(pf, te, feats, groups = list(\"lcrp\", \"lcrp2\", c(\"lcrp\", \"lcrp2\")))\nbase_auc <- auc(pf(te), te$y)\ndrop_refit <- sapply(list(\"lcrp\", \"lcrp2\", c(\"lcrp\", \"lcrp2\")), function(g)\n  base_auc - auc(rf_pred(rf_fit(tr, setdiff(feats, g)), te), te$y))\ndata.frame(what = c(\"lcrp\", \"lcrp2\", \"lcrp + lcrp2 together\"),\n           permute_AUC_drop = round(grp, 4), drop_and_refit_AUC_drop = round(drop_refit, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   what permute_AUC_drop drop_and_refit_AUC_drop\n1                  lcrp           0.0560                  0.0043\n2                 lcrp2          -0.0014                 -0.0026\n3 lcrp + lcrp2 together           0.0931                  0.0493\n```\n\n\n:::\n:::\n\n\n-   **하나씩 섞으면** lcrp 0.0560, lcrp2 -0.0014. **함께 섞으면 0.0931** — 둘의 합보다 훨씬 큽니다\n-   **빼고 다시 학습**(drop-column)하면 어느 하나를 빼도 AUC가 거의 안 변합니다(0.0043, -0.0026). **다른 하나가 대신하기 때문**입니다. 둘 다 빼야 0.0493\n-   ⚠️ 그러니 \"lcrp를 빼도 성능이 같으니 CRP는 중요하지 않다\"도, \"lcrp2의 permutation importance가 0이니 무의미하다\"도 틀린 결론입니다\n-   ⚠️ 또 하나를 섞으면 **\"CRP는 높은데 hs-CRP는 낮은\" 현실에 없는 환자**가 만들어집니다. 모델은 그런 데이터를 본 적이 없으므로 그 예측은 **외삽**입니다\n-   ✅ 대처 — 상관된 변수는 **묶어서(grouped)** 섞거나, 조건부(conditional) permutation을 쓰거나, 분석 전에 대표 변수 하나만 남기기\n\n------------------------------------------------------------------------\n\n## 3. Partial dependence와 ICE 📈\n\n### 1) 정의\n\n**PDP (Partial Dependence Plot)** — 관심 변수 $x_S$ 를 $v$ 로 **모든 샘플에 똑같이 고정**하고 예측을 평균\n\n$$\\hat{f}_S(v) = \\frac{1}{n}\\sum_{i=1}^{n}\\hat{f}(v, \\mathbf{x}_{i,C})$$\n\n**ICE (Individual Conditional Expectation)** — 평균 내기 전의 **샘플별 곡선** $\\hat{f}(v, \\mathbf{x}_{i,C})$. PDP는 ICE 곡선들의 평균입니다.\n\n### 2) 🧪 실습: PDP는 U자를 되찾는가\n\n\n::: {.cell}\n\n```{.r .cell-code}\npdp <- function(pred_fun, d, var, grid) sapply(grid, function(g) { d[[var]] <- g; mean(pred_fun(d)) })\ng_bmi   <- seq(18, 36, by = 1)\npdp_rf  <- pdp(pf, te, \"bmi\", g_bmi)\npdp_tru <- pdp(function(d) plogis(true_eta(d)), te, \"bmi\", g_bmi)   # 진짜 모형의 PDP\nround(data.frame(bmi = g_bmi, random_forest = pdp_rf, truth = pdp_tru)[c(1, 5, 10, 15, 19), ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   bmi random_forest truth\n1   18         0.683 0.891\n5   22         0.398 0.471\n10  27         0.272 0.251\n15  32         0.416 0.471\n19  36         0.653 0.891\n```\n\n\n:::\n\n```{.r .cell-code}\nc(argmin_rf = g_bmi[which.min(pdp_rf)], argmin_truth = g_bmi[which.min(pdp_tru)],\n  cor_rf_truth = round(cor(pdp_rf, pdp_tru), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   argmin_rf argmin_truth cor_rf_truth \n      25.000       27.000        0.955 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npl <- rbind(data.frame(bmi = g_bmi, p = pdp_rf,  src = \"random forest PDP\"),\n            data.frame(bmi = g_bmi, p = pdp_tru, src = \"true model PDP\"))\nggplot(pl, aes(bmi, p, colour = src, linetype = src)) +\n  geom_rug(data = te, aes(x = bmi), inherit.aes = FALSE, alpha = .08, sides = \"b\") +\n  geom_line(linewidth = 1) +\n  scale_colour_manual(values = c(\"random forest PDP\" = \"#d1495b\", \"true model PDP\" = \"#7d8597\")) +\n  scale_linetype_manual(values = c(\"random forest PDP\" = 1, \"true model PDP\" = 2)) +\n  labs(x = \"BMI\", y = \"average predicted risk\", colour = NULL, linetype = NULL) +\n  theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](14_interpretation_files/figure-html/unnamed-chunk-7-1.png){width=576}\n:::\n:::\n\n\n-   random forest의 PDP가 **U자를 되찾습니다** (최저점 BMI 25 vs 진짜 27, 곡선 상관 0.955)\n-   다만 **양 끝을 과소평가**합니다 — BMI 18에서 0.683 vs 진짜 0.891. 아래 rug처럼 **양 끝에는 데이터가 거의 없어** 트리가 평평하게 끊습니다\n-   ⚠️ PDP는 **데이터가 드문 구간에서 가장 믿기 어렵습니다.** 항상 rug나 히스토그램을 같이 그리세요\n\n### 3) 🧪 실습: PDP가 가린 것 — ICE\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(5); ice_idx <- sample(nrow(te), 150)\ng_age <- seq(40, 80, by = 2)\nice_curves <- function(pred_fun) sapply(g_age, function(g) { d <- te[ice_idx, ]; d$age <- g; pred_fun(d) })\nice_rf  <- ice_curves(pf)\nice_glm <- ice_curves(function(d) predict(m_int, d, type = \"response\"))\nice_tru <- ice_curves(function(d) plogis(true_eta(d)))\nsx <- te$male[ice_idx]\nslope10 <- function(M) 10 * apply(M, 1, function(r) coef(lm(r ~ g_age))[2])   # 10년당 위험 변화\ndata.frame(model = c(\"random forest\", \"GLM splines + age:sex\", \"truth\"),\n           female = round(c(mean(slope10(ice_rf)[sx == 0]), mean(slope10(ice_glm)[sx == 0]),\n                            mean(slope10(ice_tru)[sx == 0])), 4),\n           male   = round(c(mean(slope10(ice_rf)[sx == 1]), mean(slope10(ice_glm)[sx == 1]),\n                            mean(slope10(ice_tru)[sx == 1])), 4),\n           PDP_all = round(c(10 * coef(lm(colMeans(ice_rf) ~ g_age))[2],\n                             10 * coef(lm(colMeans(ice_glm) ~ g_age))[2],\n                             10 * coef(lm(colMeans(ice_tru) ~ g_age))[2]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  model female   male PDP_all\n1         random forest 0.0496 0.0669  0.0589\n2 GLM splines + age:sex 0.0065 0.1378  0.0774\n3                 truth 0.0000 0.1229  0.0663\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nic <- rbind(\n  data.frame(id = rep(seq_along(ice_idx), length(g_age)), age = rep(g_age, each = length(ice_idx)),\n             p = as.vector(ice_rf),  sex = rep(ifelse(sx == 1, \"male\", \"female\"), length(g_age)),\n             model = \"random forest\"),\n  data.frame(id = rep(seq_along(ice_idx), length(g_age)), age = rep(g_age, each = length(ice_idx)),\n             p = as.vector(ice_glm), sex = rep(ifelse(sx == 1, \"male\", \"female\"), length(g_age)),\n             model = \"GLM splines + age:sex\"))\nic$model <- factor(ic$model, levels = c(\"random forest\", \"GLM splines + age:sex\"))\npd <- aggregate(p ~ age + model, data = ic, FUN = mean)\nggplot(ic, aes(age, p)) +\n  geom_line(aes(group = id, colour = sex), alpha = .25, linewidth = .35) +\n  geom_line(data = pd, colour = \"black\", linewidth = 1.1) +\n  facet_wrap(~ model) +\n  scale_colour_manual(values = c(female = \"#2e8b7a\", male = \"#d1495b\")) +\n  guides(colour = guide_legend(override.aes = list(alpha = 1, linewidth = 1))) +\n  labs(x = \"age (set for every patient)\", y = \"predicted risk\", colour = NULL,\n       caption = \"thin lines = ICE (one patient each); thick = PDP (their average)\") +\n  theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](14_interpretation_files/figure-html/unnamed-chunk-9-1.png){width=729.6}\n:::\n:::\n\n\n-   진실은 **여성 0, 남성 +0.1229** (10년당 위험 증가)\n-   age:sex를 넣은 GLM의 ICE는 **여성 0.0065, 남성 0.1378** — 두 무리가 뚜렷이 갈립니다(오른쪽 그림)\n-   random forest는 **여성 0.0496, 남성 0.0669** — 나이 효과를 남녀에게 **비슷하게 퍼뜨렸습니다**. 트리가 이 매끄러운 상호작용을 제대로 배우지 못한 것입니다\n-   ✅ **PDP 하나만 보면 둘 다 \"나이가 들수록 위험 증가\"로 보입니다.** ICE를 그려야 \"누구에게\"가 보입니다\n-   ⚠️ 그리고 **ICE가 보여주는 것은 모델이 배운 것이지 진실이 아닙니다.** random forest의 ICE를 보고 \"여성도 나이 효과가 있다\"고 쓰면 틀립니다\n\n### 4) PDP의 가정과 ALE\n\nPDP는 $x_S$ 를 바꿀 때 나머지 변수가 **그대로라고** 가정합니다. 변수끼리 상관되어 있으면 \"BMI 18인데 체중은 100 kg\" 같은 **존재하지 않는 조합**에서 예측을 평균하게 됩니다.\n\n**ALE (Accumulated Local Effects)** 는 $x_S$ 의 작은 구간 안에 **실제로 있는 샘플만** 써서 예측의 국소 변화량을 누적합니다. 상관된 변수가 있을 때 PDP 대신 권장됩니다 (Apley & Zhu 2020, R `ALEPlot`/`iml`).\n\n------------------------------------------------------------------------\n\n## 4. SHAP 🧮\n\n### 1) Shapley value\n\n협력 게임 이론에서 온 개념입니다. feature들이 \"팀\"이 되어 예측값을 만들었을 때, **각자의 공헌을 공정하게 나누는** 방법.\n\n$$\\phi_j = \\sum_{S \\subseteq F \\setminus \\{j\\}} \\frac{|S|!\\,(|F|-|S|-1)!}{|F|!}\\Big[v(S \\cup \\{j\\}) - v(S)\\Big]$$\n\n$v(S)$ = feature 집합 $S$ 만 \"알고\" 나머지는 배경 데이터로 채웠을 때의 예측. 즉 **$j$ 가 들어오기 전후의 예측 차이를, 모든 가능한 등장 순서에 대해 평균**한 것입니다.\n\n**네 가지 성질** — 이 성질을 모두 만족하는 분배 방법은 Shapley value 하나뿐입니다\n\n-   **Efficiency** — $\\sum_j \\phi_j = f(\\mathbf{x}) - \\mathbb{E}[f(\\mathbf{X})]$. 기여의 합이 정확히 \"평균 대비 이 예측의 차이\"\n-   **Symmetry** — 같은 기여를 하는 두 feature는 같은 값\n-   **Dummy** — 예측에 아무 영향이 없는 feature는 0\n-   **Additivity** — 모델 두 개의 합을 설명하면 각 설명의 합\n\n### 2) 🧪 실습: 순열 샘플링으로 구현하기\n\n모든 부분집합($2^p$)을 다 도는 대신, **무작위 순서**를 뽑아 feature를 하나씩 배경값에서 실제값으로 바꿔 가며 예측이 얼마나 변하는지 잽니다 (Štrumbelj & Kononenko 2014).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshap_perm <- function(pred_fun, x, bg, feats, M = 200) {\n  p <- length(feats); rows <- vector(\"list\", M); perms <- matrix(0L, M, p)\n  for (m in 1:M) {\n    z <- bg[sample(nrow(bg), 1), feats]; pi <- sample(p); perms[m, ] <- pi\n    h <- z[rep(1, p + 1), ]                                # 배경 샘플에서 출발\n    for (k in 1:p) h[(k + 1):(p + 1), feats[pi[k]]] <- x[[feats[pi[k]]]]   # 순서대로 x 값으로 교체\n    rows[[m]] <- h\n  }\n  f <- matrix(pred_fun(do.call(rbind, rows)), p + 1)       # 한 번에 예측 : (p+1) x M\n  phi <- setNames(numeric(p), feats)\n  for (m in 1:M) phi[feats[perms[m, ]]] <- phi[feats[perms[m, ]]] + diff(f[, m])\n  list(phi = phi / M, f_x = f[p + 1, 1], base = mean(f[1, ]))\n}\n```\n:::\n\n\n**검증** — 선형 모형(log-odds 척도)에서 Shapley value는 닫힌 해가 있습니다: $\\phi_j = \\beta_j\\,(x_j - \\mathbb{E}[x_j])$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(6); bg <- tr[sample(nrow(tr), 200), ]            # 배경(기준) 데이터\nset.seed(7)\ns_lin  <- shap_perm(function(d) predict(m_lin, d), te[1, ], bg, feats, M = 2000)\nclosed <- coef(m_lin)[feats] * (unlist(te[1, feats]) - colMeans(bg[feats]))\nround(rbind(permutation_sampling = s_lin$phi, closed_form = closed), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         age   male    lcrp  lcrp2     bmi    sbp  lab_x   flag\npermutation_sampling -0.3541 0.0472 -1.6233 0.1754 -0.0260 0.1443 0.0150 0.0164\nclosed_form          -0.3518 0.0480 -1.6211 0.1754 -0.0265 0.1438 0.0158 0.0167\n```\n\n\n:::\n\n```{.r .cell-code}\nc(max_abs_diff = signif(max(abs(s_lin$phi - closed)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax_abs_diff \n     0.00227 \n```\n\n\n:::\n:::\n\n\n-   순열 2000개로 닫힌 해와 **몬테카를로 오차 수준에서** 일치합니다\n-   ✅ 선형 모형에서 SHAP은 \"계수 × 평균에서 벗어난 정도\"일 뿐입니다. SHAP은 이것을 **아무 모델에나** 일반화한 것입니다\n\n### 3) 🧪 실습: 한 환자의 예측 뜯어보기 (local)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nip <- which.max(pf(te[1:200, ]))                           # 처음 200명 중 가장 위험한 환자\nset.seed(8)\ns1 <- shap_perm(pf, te[ip, ], bg, feats, M = 300)\nte[ip, feats]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        age male     lcrp    lcrp2      bmi      sbp      lab_x flag\n126 65.3758    0 1.271866 1.086568 18.34429 161.3275 -0.0247364    0\n```\n\n\n:::\n\n```{.r .cell-code}\nc(prediction = round(s1$f_x, 4), base = round(s1$base, 4),\n  base_plus_sum_phi = round(s1$base + sum(s1$phi), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       prediction              base base_plus_sum_phi \n           0.7950            0.3754            0.7950 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(sort(s1$phi, decreasing = TRUE), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    bmi    lcrp     sbp   lcrp2     age   lab_x    male    flag \n 0.3227  0.0358  0.0336  0.0218  0.0062  0.0006  0.0000 -0.0012 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsl <- data.frame(feature = names(s1$phi), phi = s1$phi,\n                 val = sapply(names(s1$phi), function(v) format(round(te[ip, v], 1))))\nsl$label <- paste0(sl$feature, \" = \", sl$val)\nsl$label <- factor(sl$label, levels = sl$label[order(sl$phi)])\nggplot(sl, aes(phi, label, fill = phi > 0)) + geom_col(width = .7) +\n  geom_vline(xintercept = 0, colour = \"grey40\") +\n  scale_fill_manual(values = c(\"TRUE\" = \"#d1495b\", \"FALSE\" = \"#2e8b7a\"), guide = \"none\") +\n  labs(x = \"SHAP value (change in predicted risk)\", y = NULL,\n       caption = paste0(\"base \", round(s1$base, 3), \" + sum of SHAP = prediction \", round(s1$f_x, 3))) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](14_interpretation_files/figure-html/unnamed-chunk-13-1.png){width=576}\n:::\n:::\n\n\n-   이 환자의 예측 위험은 **0.795**, 배경 평균은 0.3754 — 그 차이를 feature별로 나눈 것이 SHAP입니다\n-   기준값 + SHAP 합 = 예측이 **정확히** 맞습니다 (efficiency)\n-   가장 큰 기여는 CRP가 아니라 **BMI 18.3**(저체중)입니다. U자의 왼쪽 끝이 이 환자의 위험을 끌어올렸습니다\n-   ✅ 전역 중요도로는 알 수 없는 **\"이 환자는 왜?\"**에 답하는 것이 local 설명입니다\n\n### 4) 🧪 실습: 전역 요약 — 100명의 SHAP\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(9)\nex <- sample(nrow(te), 100)\nS  <- t(sapply(ex, function(i) shap_perm(pf, te[i, ], bg, feats, M = 100)$phi))\ndata.frame(feature = feats,\n           mean_abs_SHAP = round(colMeans(abs(S)), 4),\n           perm_AUC_drop_test = round(pi_test, 4),\n           true_effect = imp_tab$true_effect, row.names = NULL)[order(-colMeans(abs(S))), ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  feature mean_abs_SHAP perm_AUC_drop_test     true_effect\n5     bmi        0.1068             0.1283   yes (U-shape)\n3    lcrp        0.0800             0.0581             yes\n1     age        0.0452             0.0233 yes (male only)\n4   lcrp2        0.0259             0.0013      no (proxy)\n6     sbp        0.0202             0.0042      yes (weak)\n7   lab_x        0.0090             0.0000              no\n2    male        0.0045             0.0030   yes (via age)\n8    flag        0.0013            -0.0001              no\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbs <- do.call(rbind, lapply(feats, function(v) data.frame(feature = v, phi = S[, v],\n          val = rank(te[ex, v]) / length(ex))))                 # 색 = feature 값의 상대 순위\nbs$feature <- factor(bs$feature, levels = feats[order(colMeans(abs(S)))])\nset.seed(10)\nggplot(bs, aes(phi, feature, colour = val)) +\n  geom_vline(xintercept = 0, colour = \"grey60\") +\n  geom_jitter(height = .18, width = 0, size = 1) +\n  scale_colour_gradient(low = \"#2e8b7a\", high = \"#d1495b\", breaks = c(.1, .9), labels = c(\"low\", \"high\")) +\n  labs(x = \"SHAP value (change in predicted risk)\", y = NULL, colour = \"feature\\nvalue\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](14_interpretation_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n-   평균 |SHAP| 순위(bmi → lcrp → age)가 permutation importance와 대체로 같습니다\n-   **bmi 줄에서는 빨강(높음)과 청록(낮음)이 모두 오른쪽**에 있습니다 — U자. 평균 |SHAP| 하나로는 이 모양이 안 보입니다\n-   ⚠️ **lcrp2는 원인이 아닌데도 평균 |SHAP|이 0이 아닙니다.** 모델이 lcrp2를 **쓰고 있기** 때문입니다\n-   ✅ **SHAP은 모델을 설명하지, 세상을 설명하지 않습니다.** \"SHAP 값이 크다 = 그 변수를 바꾸면 결과가 바뀐다\"는 인과적 해석은 틀릴 수 있습니다\n\n### 5) SHAP 사용 시 주의\n\n| 함정 | 설명 |\n|---|---|\n| **인과가 아님** | 대리 변수·교란 변수도 큰 SHAP을 받습니다 (lcrp2) |\n| **상관된 feature** | 기본(interventional) SHAP은 feature를 **독립적으로** 바꿔 넣어 존재하지 않는 조합을 만듭니다. 조건부(observational) SHAP은 신용이 상관된 변수로 번져 나갑니다. **어느 쪽을 썼는지 적을 것** |\n| **척도** | 확률 척도냐 log-odds 척도냐에 따라 순위가 달라질 수 있습니다 |\n| **배경 데이터** | \"평균적인 환자\"를 누구로 정하느냐(train 전체? 대조군?)에 따라 값이 바뀝니다 |\n| **계산량** | 정확한 계산은 $2^p$. 트리 모델은 TreeSHAP(`xgboost`, `shap`)이 빠르고 정확합니다 |\n\n**LIME** — 설명하려는 점 **주변에 표본을 흩뿌리고**, 그 근처에서만 맞는 **단순한 선형 모형**을 적합해 계수를 설명으로 씁니다. 빠르고 직관적이지만 이웃의 범위(kernel 폭)에 따라 설명이 크게 흔들려서, 현재는 SHAP이 더 널리 쓰입니다.\n\n------------------------------------------------------------------------\n\n## 5. 해석 가능한 모델 vs 사후 설명 ⚖️\n\nRudin(2019)의 주장 — **고위험 의사결정에서는 블랙박스를 설명하려 하지 말고, 처음부터 해석 가능한 모델을 쓰라.**\n\n1절의 결과를 다시 보면\n\n| 모델 | test AUC | 해석 |\n|---|---|---|\n| random forest | 0.7481 | 사후 설명(SHAP, PDP) 필요. 나이×성별 상호작용을 제대로 못 배움 |\n| logistic + splines | 0.7597 | 각 변수의 효과 곡선을 **그대로 그릴 수 있음** |\n| logistic + splines + age:sex | **0.7678** | 상호작용까지 계수로 보임. ICE가 진실과 일치 |\n\n-   이 데이터에서는 **해석 가능한 모델이 블랙박스보다 낫습니다.** 표 형태의 임상 데이터에서 드문 일이 아닙니다 — 복잡한 모델의 이득은 대개 작습니다 (Christodoulou et al. 2019)\n-   사후 설명은 **근사**입니다. SHAP·PDP가 보여주는 것이 모델이 실제로 하는 일과 어긋날 수 있습니다\n-   ✅ **순서** — 먼저 해석 가능한 모델(정규화 GLM + spline, 얕은 트리, GAM)로 기준선을 세우고, 블랙박스가 **의미 있게** 나을 때만 블랙박스 + 사후 설명으로 갑니다\n-   영상·서열·단일세포처럼 feature가 원시 신호이고 수가 매우 많을 때는 해석 가능한 모델만으로 부족할 수 있습니다. 그때가 사후 설명이 필요한 자리입니다\n\n------------------------------------------------------------------------\n\n## 6. 보고 지침 📋\n\n### 1) TRIPOD+AI\n\n-   **TRIPOD**(2015)는 예측 모형 개발·검증 연구의 보고 지침입니다. **TRIPOD+AI**(Collins et al., *BMJ* 2024)는 회귀와 머신러닝을 모두 포괄하도록 개정된 **27개 항목** 체크리스트이고, 초록용 체크리스트가 따로 있습니다\n-   임상 예측 모형 논문을 투고하면 많은 저널이 이 체크리스트 제출을 요구합니다\n\n이 과목과 직접 연결되는 핵심 요구사항을 추리면\n\n| 영역 | 보고할 것 | 이 과목 |\n|---|---|---|\n| **데이터** | 출처, 기간, 포함·제외 기준, 결측 처리, 표본 크기의 근거 | W2 |\n| **결과 정의** | 무엇을 언제 어떻게 판정했는지, 예측변수 측정과 눈가림 | — |\n| **분석** | 전처리, 모델·초매개변수 선택, **내부 검증 방법**(CV, bootstrap) | W2, W3 |\n| **불균형** | 재표본(over/undersampling, SMOTE) 여부와 방법 | W6 |\n| **성능** | **discrimination과 calibration을 함께**, 신뢰구간 포함 | W4 |\n| **공정성** | 성별·연령 등 **하위집단별 성능** | — |\n| **해석** | 설명 방법을 썼다면 무엇을 어떻게 | W14 |\n| **공개(open science)** | 프로토콜, **데이터·코드 공개**, 모델 자체의 공개 | W14 |\n| **환자·대중 참여** | 연구 설계·해석에 환자가 참여했는지 | — |\n\n### 2) 🧪 실습: AUC만 보고하면 놓치는 것 — 외부 검증\n\n다른 병원 코호트를 만듭니다. **더 고령이고(평균 68세) 기저 위험이 낮습니다**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\next <- sim_clin(2000, 3, shift = -0.8, age_mu = 68)\ncal <- function(p, y) {                                   # discrimination + calibration\n  lp <- qlogis(pmin(pmax(p, 1e-6), 1 - 1e-6))\n  c(AUC = auc(p, y), Brier = mean((p - y)^2),\n    cal_intercept = unname(coef(glm(y ~ 1, offset = lp, family = binomial))[1]),  # 0 이 이상적\n    cal_slope = unname(coef(glm(y ~ lp, family = binomial))[2]),                 # 1 이 이상적\n    mean_pred = mean(p), observed = mean(y))\n}\np_glm_te <- predict(m_int, te, type = \"response\"); p_glm_ex <- predict(m_int, ext, type = \"response\")\np_rf_te  <- pf(te);                                 p_rf_ex  <- pf(ext)\ncbind(data.frame(model = rep(c(\"GLM splines + age:sex\", \"random forest\"), 2),\n                 cohort = rep(c(\"internal test\", \"external\"), each = 2)),\n      round(rbind(cal(p_glm_te, te$y), cal(p_rf_te, te$y), cal(p_glm_ex, ext$y), cal(p_rf_ex, ext$y)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  model        cohort    AUC  Brier cal_intercept cal_slope\n1 GLM splines + age:sex internal test 0.7678 0.1840        0.0487    0.8517\n2         random forest internal test 0.7481 0.1935        0.0624    1.0898\n3 GLM splines + age:sex      external 0.8092 0.1738       -0.9244    0.8863\n4         random forest      external 0.7786 0.1808       -0.6790    1.2334\n  mean_pred observed\n1    0.3827    0.391\n2    0.3786    0.391\n3    0.4338    0.288\n4    0.4168    0.288\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalbin <- function(p, y, model, cohort) {\n  b <- cut(p, quantile(p, 0:10 / 10), include.lowest = TRUE)\n  data.frame(pred = tapply(p, b, mean), obs = tapply(y, b, mean), model = model, cohort = cohort)\n}\ncb <- rbind(calbin(p_glm_te, te$y, \"GLM splines + age:sex\", \"internal test\"),\n            calbin(p_rf_te,  te$y, \"random forest\",         \"internal test\"),\n            calbin(p_glm_ex, ext$y, \"GLM splines + age:sex\", \"external\"),\n            calbin(p_rf_ex,  ext$y, \"random forest\",         \"external\"))\ncb$cohort <- factor(cb$cohort, levels = c(\"internal test\", \"external\"))\nggplot(cb, aes(pred, obs, colour = model)) +\n  geom_abline(linetype = 2, colour = \"grey50\") +\n  geom_line(linewidth = .8) + geom_point(size = 1.8) +\n  facet_wrap(~ cohort) + coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +\n  scale_colour_manual(values = c(\"GLM splines + age:sex\" = \"#2e8b7a\", \"random forest\" = \"#d1495b\")) +\n  labs(x = \"mean predicted risk (decile)\", y = \"observed event rate\", colour = NULL) +\n  theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](14_interpretation_files/figure-html/unnamed-chunk-17-1.png){width=729.6}\n:::\n:::\n\n\n-   외부 코호트에서 **AUC는 오히려 올랐습니다**(GLM 0.7678 → 0.8092). 고령 환자가 섞여 위험의 폭이 넓어졌기 때문입니다\n-   그런데 **평균 예측 0.4338 vs 실제 0.288** — 모든 환자의 위험을 부풀립니다. calibration intercept **-0.9244**(이상적으로 0)\n-   AUC만 보고했다면 \"외부에서도 잘 된다\"고 결론 내렸을 것입니다. 이 모델로 \"위험 40% 이상은 입원\"을 정하면 **불필요한 입원이 쏟아집니다**\n-   내부 test에서도 두 모델의 calibration slope가 다릅니다(GLM 0.8517: 약간 과적합, RF 1.0898: 예측이 너무 보수적)\n-   ✅ **discrimination(AUC)은 순서를, calibration은 숫자 자체를 봅니다.** 확률을 임상적으로 쓸 거면 둘 다 필요합니다 (W4)\n-   ✅ 외부 검증에서 calibration이 어긋나면 **재보정(recalibration)** — intercept(과 slope)만 새 코호트에 맞추는 것으로 대부분 해결됩니다\n\n### 3) 외부 검증의 의미\n\n| 검증 | 데이터 | 답하는 질문 |\n|---|---|---|\n| **내부** (CV, bootstrap, 분할) | 같은 출처 | 과적합 없이 **이 모집단에서** 작동하는가 |\n| **시간적** | 같은 병원, 나중 시기 | 시간이 지나도 작동하는가 |\n| **지리적 / 외부** | 다른 병원·국가 | **다른 모집단에** 옮겨 쓸 수 있는가 |\n\n⚠️ 무작위로 나눈 test set은 **외부 검증이 아닙니다.** 같은 병원 데이터를 7:3으로 나눈 것은 내부 검증입니다.\n\n### 4) 🧪 실습: 재현성 — 버전과 seed를 남긴다\n\n\n::: {.cell}\n\n```{.r .cell-code}\nR.version.string\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"R version 4.5.2 (2025-10-31 ucrt)\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsapply(c(\"rpart\", \"splines\", \"ggplot2\"), function(p) as.character(packageVersion(p)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   rpart  splines  ggplot2 \n\"4.1.24\"  \"4.5.2\"  \"4.0.3\" \n```\n\n\n:::\n:::\n\n\n-   논문의 Methods나 보충자료에 **R/Python 버전, 패키지 버전, seed**를 적고, 코드는 GitHub + Zenodo DOI로 공개하세요\n-   `sessionInfo()`(R), `pip freeze`(Python), `renv.lock` / `environment.yml`을 저장소에 같이 두면 재현이 쉬워집니다 (Ch0)\n-   이 사이트가 GitHub Actions에서 **매번 처음부터 다시 렌더링**되는 것도 같은 이유입니다 — 코드가 실제로 돌아가는지 기계가 매번 확인합니다\n\n------------------------------------------------------------------------\n\n## 7. 흔한 실수 체크리스트 🚨\n\n### 1) 🧪 실습: test set을 여러 번 쓰면\n\n**신호가 전혀 없는** 데이터로 후보 모형 200개를 만들고, test AUC가 가장 높은 것을 고릅니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(11)\nn <- 150; p <- 30\nXtr <- matrix(rnorm(n * p), n, p);      ytr <- rbinom(n, 1, .5)       # 신호 없음\nXte <- matrix(rnorm(n * p), n, p);      yte <- rbinom(n, 1, .5)\nXnew <- matrix(rnorm(2000 * p), 2000, p); ynew <- rbinom(2000, 1, .5)   # 새 데이터\ncand <- lapply(1:200, function(k) sample(p, 5))                         # feature 5개짜리 후보 200개\nfits <- lapply(cand, function(f) glm(ytr ~ Xtr[, f], family = binomial))\nscore <- function(fit, f, X) as.vector(cbind(1, X[, f]) %*% coef(fit))\nauc_te <- mapply(function(fit, f) auc(score(fit, f, Xte), yte), fits, cand)\nbest <- which.max(auc_te)\ndata.frame(what = c(\"best of 200, judged on the reused test set\", \"that same model on fresh data\",\n                    \"median of the 200 on the test set\"),\n           AUC = round(c(auc_te[best], auc(score(fits[[best]], cand[[best]], Xnew), ynew),\n                         median(auc_te)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                        what    AUC\n1 best of 200, judged on the reused test set 0.6166\n2              that same model on fresh data 0.5140\n3          median of the 200 on the test set 0.5123\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(a = auc_te), aes(a)) +\n  geom_histogram(bins = 30, fill = \"#7d8597\", colour = \"white\") +\n  geom_vline(xintercept = auc_te[best], colour = \"#d1495b\", linewidth = 1) +\n  geom_vline(xintercept = auc(score(fits[[best]], cand[[best]], Xnew), ynew), colour = \"#2e8b7a\",\n             linewidth = 1, linetype = 2) +\n  labs(x = \"test AUC of 200 useless models\", y = \"count\",\n       caption = \"red = chosen model on the reused test set; teal dashed = same model on fresh data\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](14_interpretation_files/figure-html/unnamed-chunk-20-1.png){width=576}\n:::\n:::\n\n\n-   아무 신호가 없는데도 200개 중 가장 좋은 것은 test AUC **0.6166**. 새 데이터에서는 **0.5140**\n-   \"test set에서 제일 좋은 것을 골라 test 성능을 보고\"하면 **선택 자체가 과적합**입니다. 모델·feature·초매개변수를 여러 번 바꿔 보는 모든 과정이 여기에 해당합니다\n-   ✅ test set은 **마지막에 한 번만**. 선택은 CV나 별도 validation set으로 (W3의 nested CV)\n\n### 2) 🧪 실습: CV 밖에서 feature를 고르면\n\n순수 잡음 2000개, 샘플 100개. 결과와 가장 관련 있어 보이는 10개를 골라 로지스틱 회귀.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12)\nn <- 100; p <- 2000\nX <- matrix(rnorm(n * p), n, p); y <- rbinom(n, 1, .5)                  # 신호 없음\ntstat <- function(X, y) abs(colMeans(X[y == 1, ]) - colMeans(X[y == 0, ])) /\n  sqrt(apply(X[y == 1, ], 2, var) / sum(y == 1) + apply(X[y == 0, ], 2, var) / sum(y == 0))\nfold <- sample(rep(1:5, length.out = n))\ncv_auc <- function(select_inside) {\n  pr <- numeric(n); top_all <- order(tstat(X, y), decreasing = TRUE)[1:10]\n  for (f in 1:5) {\n    tri <- fold != f\n    top <- if (select_inside) order(tstat(X[tri, ], y[tri]), decreasing = TRUE)[1:10] else top_all\n    g <- suppressWarnings(glm(y[tri] ~ X[tri, top], family = binomial))\n    pr[!tri] <- cbind(1, X[!tri, top]) %*% coef(g)\n  }\n  auc(pr, y)\n}\ndata.frame(pipeline = c(\"select top 10 on ALL data, then 5-fold CV\", \"select inside each training fold\"),\n           CV_AUC = round(c(cv_auc(FALSE), cv_auc(TRUE)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                   pipeline CV_AUC\n1 select top 10 on ALL data, then 5-fold CV 0.8642\n2          select inside each training fold 0.4499\n```\n\n\n:::\n:::\n\n\n-   전체 데이터로 고르고 CV하면 **AUC 0.8642** — 잡음으로 논문 한 편이 나옵니다\n-   fold 안에서 고르면 **0.4499**, 즉 동전 던지기 수준. 이것이 진실입니다\n-   ✅ **feature 선택·정규화·결측 대치·재표본까지 모든 전처리는 fold 안에서** (W2). 오믹스 바이오마커 논문에서 가장 흔한 오류입니다\n\n### 3) 🧪 실습: 불균형을 무시하면\n\n유병률을 약 5%로 낮춘 같은 코호트입니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrtr <- sim_clin(3000, 21, shift = -3.2); rte <- sim_clin(5000, 22, shift = -3.2)\nmr <- glm(y ~ ns(age, 3) * male + ns(lcrp, 3) + ns(bmi, 3) + ns(sbp, 3), data = rtr, family = binomial)\npr <- predict(mr, rte, type = \"response\")\navg_prec <- function(p, y) { o <- order(p, decreasing = TRUE); y <- y[o]; mean((cumsum(y) / seq_along(y))[y == 1]) }\nsens <- function(pred, y) sum(pred == 1 & y == 1) / sum(y == 1)\nc(prevalence_test = round(mean(rte$y), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprevalence_test \n         0.0498 \n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(classifier = c(\"always predict 0\", \"GLM, threshold 0.5\", \"GLM, threshold = prevalence\"),\n           accuracy = round(c(mean(rte$y == 0), mean((pr > .5) == rte$y), mean((pr > mean(rtr$y)) == rte$y)), 4),\n           sensitivity = round(c(0, sens(as.integer(pr > .5), rte$y), sens(as.integer(pr > mean(rtr$y)), rte$y)), 4),\n           AUC = c(\"0.5\", rep(format(round(auc(pr, rte$y), 4)), 2)),\n           PR_AUC = c(format(round(mean(rte$y), 4)), rep(format(round(avg_prec(pr, rte$y), 4)), 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   classifier accuracy sensitivity    AUC PR_AUC\n1            always predict 0   0.9502      0.0000    0.5 0.0498\n2          GLM, threshold 0.5   0.9538      0.1606 0.8189 0.3586\n3 GLM, threshold = prevalence   0.7770      0.6867 0.8189 0.3586\n```\n\n\n:::\n:::\n\n\n-   **\"모두 음성\"이라고 찍기만 해도 정확도 0.9502** — 모델(0.9538)과 거의 같습니다\n-   임계값 0.5를 그대로 쓰면 환자의 **16%만** 잡습니다. 유병률 근처로 낮추면 정확도는 0.7770으로 떨어지지만 민감도 **0.6867**\n-   PR-AUC의 기준선은 0.5가 아니라 **유병률(0.0498)**입니다. 모델의 0.3586은 낮아 보이지만 기준선보다 훨씬 높습니다 — 기준선을 같이 보고해야 의미가 있습니다\n-   ✅ 불균형 데이터에서는 **정확도를 주 지표로 쓰지 말고**, AUC와 PR-AUC, 임상적으로 정한 임계값에서의 민감도·특이도를 보고 (W4, W6)\n\n### 4) 체크리스트\n\n| 단계 | 확인할 것 | 챕터 |\n|---|---|---|\n| 설계 | 결과 정의·예측 시점이 명확한가? 예측 시점 **이후** 정보가 feature에 섞이지 않았나? | W2 |\n| 분할 | 같은 환자·같은 배치가 train과 test에 동시에 있지 않나? (group split) | W3 |\n| 전처리 | 정규화·대치·feature 선택·재표본이 **모두 fold 안**인가? | W2, W6 |\n| 선택 | test set을 모델 선택에 쓰지 않았나? 초매개변수는 nested CV로 골랐나? | W3 |\n| 지표 | AUC **와** calibration, 불균형이면 PR-AUC까지, **신뢰구간**과 함께 | W4 |\n| 기준선 | 단순한 모델(로지스틱)과 비교했나? 복잡한 모델의 이득이 의미 있는가? | W5, W14 |\n| 해석 | 중요도는 test 데이터로? 상관된 변수를 고려했나? 인과적 표현을 피했나? | W14 |\n| 검증 | 외부(다른 병원·시기) 검증이 있나? 하위집단별 성능은? | W14 |\n| 공개 | 코드·seed·버전·(가능하면) 데이터와 모델을 공개했나? | W14 |\n\n------------------------------------------------------------------------\n\n::: {.callout-warning}\n## ⚠️ 해석 결과를 논문에 쓸 때\n\n-   **\"X가 결과의 원인이다\" 대신 \"모델은 X에 가장 크게 의존했다\"**라고 쓰세요. 중요도·SHAP은 연관이지 인과가 아닙니다\n-   **불순도 기반 중요도만 보고하지 말 것** — 연속형·다범주 변수에 편향되어 있습니다. test 데이터의 permutation importance나 SHAP을 함께\n-   **상관된 변수 묶음**은 개별이 아니라 **묶음으로** 해석하고, 그렇게 했다고 적을 것\n-   SHAP을 썼다면 **배경 데이터, 척도(확률/log-odds), interventional/conditional 여부**를 명시\n-   PDP에는 **데이터 분포(rug)를 같이** 그리고, 데이터가 드문 구간의 모양은 해석하지 말 것\n-   해석 가능한 모델과 **성능을 나란히 보고**하세요. 블랙박스를 쓴 이유가 성능이라면 그 차이를 숫자로 보여야 합니다\n:::\n\n::: {.callout-important}\n## Where this ends up\n\n-   permutation importance와 W9 random forest의 OOB importance는 같은 발상입니다\n-   calibration과 Brier score → W4, class imbalance와 재표본 → W6\n-   누수와 fold 안의 전처리 → W2, nested CV와 test set 한 번만 → W3\n-   Bayes 상한(진짜 확률의 AUC 0.7711) → W11\n-   **W15 프로젝트** — 이 챕터의 체크리스트를 그대로 제출물 평가 기준으로 씁니다. \"검증 설계의 타당성 > 최종 성능 수치\"\n:::\n\n------------------------------------------------------------------------\n\n## 📝 Summary\n\n-   해석은 **디버깅, 과학적 발견, 신뢰, 개인별 설명**을 위해 합니다. 진짜 규칙을 아는 모의 데이터로 설명 도구를 검증했습니다\n-   **불순도 중요도는 효과 없는 연속형 변수(lab_x 0.052)를 실제 효과가 있는 변수(male 0.017)보다 높게** 봅니다. test set의 permutation importance는 0.0000\n-   permutation importance를 **train으로 재면** 잡음 변수도 0.0173으로 부풀려집니다\n-   **상관된 변수** — 하나씩 섞으면 lcrp 0.0560 / lcrp2 -0.0014, 함께 섞으면 0.0931. 하나를 빼고 재학습하면 다른 하나가 대신해 거의 0\n-   **PDP**는 BMI의 U자를 되찾지만(상관 0.955) 데이터가 드문 양 끝을 과소평가합니다(0.683 vs 0.891)\n-   **ICE**는 PDP가 가린 개인차를 보여줍니다. age:sex GLM은 여성 0.0065 / 남성 0.1378(진실 0 / 0.1229), random forest는 0.0496 / 0.0669로 효과를 퍼뜨렸습니다 — **ICE는 모델이 배운 것을 보여줍니다**\n-   **SHAP** — Shapley value로 예측을 기여로 분해. efficiency로 기준값 + 합 = 예측. 선형 모형에서는 $\\beta_j(x_j - \\bar{x}_j)$ 와 일치\n-   한 환자(예측 0.795)의 가장 큰 기여는 CRP가 아니라 **BMI 18.3** — local 설명의 가치\n-   **SHAP은 모델을 설명하지 세상을 설명하지 않습니다** — 원인이 아닌 lcrp2도 기여를 받습니다\n-   이 데이터에서 **해석 가능한 GLM(0.7678)이 random forest(0.7481)보다 낫습니다.** 해석 가능한 모델로 기준선을 먼저\n-   **TRIPOD+AI** — 27개 항목(BMJ 2024). discrimination과 calibration, 공정성, 코드·데이터 공개\n-   외부 코호트에서 **AUC는 0.8092로 올랐지만 평균 예측 0.4338 vs 실제 0.288** — AUC만 보고하면 놓칩니다\n-   test set 재사용 — 쓸모없는 200개 중 최고가 0.6166, 새 데이터에서 0.5140\n-   CV 밖 feature 선택 — 순수 잡음으로 **0.8642**, 제대로 하면 0.4499\n-   유병률 5%에서 \"모두 음성\"의 정확도 **0.9502**. PR-AUC 기준선은 유병률\n\n## 🔑 Key terms\n\n| 용어 | 정의 |\n|------|------|\n| **Global / local 설명** | 모델 전체의 행동 / 한 예측의 이유 |\n| **Model-agnostic** | 예측 함수만으로 동작하는 설명 방법 |\n| **Impurity importance (MDI)** | 트리 split의 불순도 감소 합. 연속형·다범주에 편향 |\n| **Permutation importance** | test에서 변수를 섞었을 때 성능 감소 |\n| **Drop-column importance** | 변수를 빼고 재학습했을 때 성능 감소 |\n| **PDP** | 변수를 모든 샘플에 고정했을 때 평균 예측 |\n| **ICE** | PDP의 샘플별 곡선. 이질성·상호작용을 보여줌 |\n| **ALE** | 실제 데이터 근처의 국소 변화 누적. 상관에 강함 |\n| **Shapley value / SHAP** | 모든 등장 순서에 대한 한계 기여의 평균 |\n| **Efficiency** | $\\sum\\phi_j = f(\\mathbf{x}) - \\mathbb{E}f$ |\n| **LIME** | 국소 선형 대리 모형으로 설명 |\n| **Calibration intercept / slope** | 예측 확률 수준의 치우침 / 퍼짐 (0과 1이 이상적) |\n| **External validation** | 다른 시기·기관 데이터에서의 검증 |\n| **TRIPOD+AI** | 임상 예측 모형 보고 지침, 27개 항목 (2024) |\n\n## ➕ References\n\n-   Collins GS, Moons KGM, Dhiman P, et al. TRIPOD+AI statement: updated guidance for reporting clinical prediction models that use regression or machine learning methods. *BMJ* 2024;385:e078378.\n-   Collins GS, Reitsma JB, Altman DG, Moons KGM. Transparent reporting of a multivariable prediction model for individual prognosis or diagnosis (TRIPOD). *BMJ* 2015;350:g7594.\n-   Breiman L. Random forests. *Machine Learning* 2001;45:5–32.\n-   Strobl C, Boulesteix AL, Zeileis A, Hothorn T. Bias in random forest variable importance measures: illustrations, sources and a solution. *BMC Bioinformatics* 2007;8:25.\n-   Hooker G, Mentch L, Zhou S. Unrestricted permutation forces extrapolation: variable importance requires at least one more model, or there is no free variable importance. *Statistics and Computing* 2021;31:82.\n-   Friedman JH. Greedy function approximation: a gradient boosting machine. *Annals of Statistics* 2001;29(5):1189–1232.\n-   Goldstein A, Kapelner A, Bleich J, Pitkin E. Peeking inside the black box: visualizing statistical learning with plots of individual conditional expectation. *J Comput Graph Stat* 2015;24(1):44–65.\n-   Apley DW, Zhu J. Visualizing the effects of predictor variables in black box supervised learning models. *JRSS-B* 2020;82(4):1059–1086.\n-   Lundberg SM, Lee SI. A unified approach to interpreting model predictions. *NeurIPS 2017*.\n-   Štrumbelj E, Kononenko I. Explaining prediction models and individual predictions with feature contributions. *Knowledge and Information Systems* 2014;41:647–665.\n-   Ribeiro MT, Singh S, Guestrin C. \"Why should I trust you?\": explaining the predictions of any classifier. *KDD 2016*:1135–1144.\n-   Rudin C. Stop explaining black box machine learning models for high stakes decisions and use interpretable models instead. *Nature Machine Intelligence* 2019;1:206–215.\n-   Christodoulou E, Ma J, Collins GS, et al. A systematic review shows no performance benefit of machine learning over logistic regression for clinical prediction models. *J Clin Epidemiol* 2019;110:12–22.\n-   Van Calster B, McLernon DJ, van Smeden M, et al. Calibration: the Achilles heel of predictive analytics. *BMC Medicine* 2019;17:230.\n-   Kapoor S, Narayanan A. Leakage and the reproducibility crisis in machine-learning-based science. *Patterns* 2023;4(9):100804.\n-   Molnar C. *Interpretable Machine Learning*, 2nd ed. 2022. christophm.github.io/interpretable-ml-book\n\n------------------------------------------------------------------------\n\n[← W13. Dimension Reduction](13_dimension_reduction.qmd)\n",
    "supporting": [
      "14_interpretation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}