{
  "hash": "fc60381e3bc36ece67545311b01550a9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"W5. 선형회귀와 로지스틱회귀\"\ndescription: \"최소제곱법, gradient descent, odds와 logit, 그리고 손실함수의 선택\"\nauthor: \"Eunji Ha\"\ndate: today\n\n# ── AI 채팅 위젯 설정 ──────────────────────────────────────────\nformat:\n  html:\n    include-in-header:\n      text: |\n        <meta name=\"ai-title\" content=\"W5. 선형회귀와 로지스틱회귀\">\n        <meta name=\"ai-context\" content=\"\n        이 챕터는 선형 모델의 두 기본형인 linear regression과 logistic regression을 다룹니다.\n        Linear regression은 f(x) = w^T x + b 형태이며 MSE(square loss)를 최소화합니다.\n        최소제곱법의 닫힌 해는 normal equation (X^T X)^-1 X^T y 이고,\n        R의 lm()과 정확히 같은 계수를 줍니다.\n        Gradient descent는 같은 해에 반복적으로 접근하는 방법으로,\n        learning rate가 너무 작으면 수렴이 느리고 너무 크면 발산합니다.\n        발산 임계값은 2/L이며 L은 (2/n)X^T X의 최대 고유값입니다.\n        회귀 진단으로 잔차 플롯, 다중공선성(VIF), 영향점(Cook's distance)을 다룹니다.\n        Logistic regression은 이진 분류에서 y=1일 확률을 모델링하며,\n        odds = p/(1-p), logit = log(odds)가 선형 형태가 되도록 합니다.\n        계수를 지수화하면 odds ratio가 되어 해석 가능합니다.\n        손실함수로 MSE 대신 log loss(cross-entropy)를 쓰는 이유는 세 가지입니다.\n        첫째 log loss는 베르누이 likelihood의 음의 로그이므로 MLE와 일치하고,\n        둘째 log loss는 w에 대해 볼록이지만 MSE와 sigmoid의 조합은 비볼록이며,\n        셋째 확신을 갖고 틀렸을 때 MSE는 기울기가 0으로 소실되어 학습이 멈춥니다.\n        p=0.01, y=1일 때 MSE의 기울기는 -0.0196, log loss는 -0.99로 약 50배 차이가 납니다.\n        임상 예측모델에서는 EPV(events per variable) 10 이상이 경험 규칙입니다.\n        \">\n---\n\n::: {.callout-note}\n## 🎯 Learning objectives\n\n-   선형 모델의 형태와 MSE·최소제곱법의 관계를 설명할 수 있다\n-   Normal equation을 직접 계산해 `lm()`의 계수를 재현할 수 있다\n-   **Gradient descent를 구현하고 learning rate의 효과를 설명할 수 있다**\n-   잔차·VIF로 회귀 모델을 진단할 수 있다\n-   Odds·logit·sigmoid의 관계를 유도하고 계수를 odds ratio로 해석할 수 있다\n-   **로지스틱 회귀에서 MSE 대신 log loss를 쓰는 세 가지 이유를 설명할 수 있다**\n:::\n\n> 🤔 **가장 단순한 모델이 왜 여전히 모든 벤치마크의 기준선인가?**\n\n------------------------------------------------------------------------\n\n## 1. 선형 모델이 근간인 이유 📐\n\n### 1) 데이터와 모델\n\n-   샘플 $\\mathbf{x} = (x_1; x_2; \\dots ; x_d)$ — $d$ 개 feature를 가진 관측 하나\n-   $x_i$ — 샘플 $\\mathbf{x}$ 의 $i$ 번째 feature 값\n-   모델 — feature들의 **선형 결합**\n\n$$f(\\mathbf{x}) = w_1x_1 + w_2x_2 + \\cdots + w_dx_d + b = \\mathbf{w}^{\\mathsf{T}}\\mathbf{x} + b$$\n\n-   $\\mathbf{w}$ — feature별 weight vector\n-   $b$ — bias (절편)\n-   전체 데이터는 design matrix $X$ 로 표현 → 행렬 연산 한 줄로 계산\n\n### 2) 왜 여전히 기준선인가\n\n-   **해석이 가능** — 각 weight가 곧 그 feature의 기여도\n-   **닫힌 해가 존재** — 반복 없이 한 번에 최적해\n-   **표본이 작아도 동작** — $p \\gg n$ 에서도 정규화를 얹으면 사용 가능(W6)\n-   **비선형 모델의 부품** — 신경망은 선형 결합 + 비선형 함수의 반복\n-   ⚠️ 새 방법을 제안할 때 **선형 모델보다 나은지 먼저 보일 것**\n\n------------------------------------------------------------------------\n\n## 2. Linear Regression 📉\n\n### 1) 데이터 준비\n\n-   $D = \\{(\\mathbf{x}_1, y_1), (\\mathbf{x}_2, y_2), \\dots, (\\mathbf{x}_m, y_m)\\}$\n-   $y$ 는 연속형\n-   **Discrete feature 처리** (W2와 연결)\n    -   순서 있음 — 0~1 범위 수치로 변환 (예: 병기 I·II·III → 0, 0.5, 1)\n    -   순서 없음 — 범주 수만큼 **dummy variable** (0/1) 생성\n\n### 2) MSE (square loss)\n\n$$\\text{MSE} = \\frac{1}{m}\\sum_{i=1}^{m}\\left(y_i - f(\\mathbf{x}_i)\\right)^2$$\n\n-   각 오차를 변으로 하는 **정사각형 면적의 합** — 기하학적 직관\n-   제곱이므로 큰 오차에 큰 벌점\n-   $\\mathbf{w}$ 에 대해 **2차 함수** → weight가 여러 개면 볼록한 그릇 모양\n\n### 3) 최소제곱법과 닫힌 해\n\n-   MSE를 최소화하는 $\\mathbf{w}$ 를 찾는 것 = **least square method**\n-   미분해서 0으로 두면 **normal equation**\n\n$$\\hat{\\mathbf{w}} = (X^{\\mathsf{T}}X)^{-1}X^{\\mathsf{T}}\\mathbf{y}$$\n\n-   ⚠️ $X^{\\mathsf{T}}X$ 가 **역행렬을 갖지 않으면** 계산 불가\n    -   feature 수 > 샘플 수 ($p \\gg n$)\n    -   완전 다중공선성\n    -   → W6의 정규화가 이 문제를 직접 해결\n\n### 4) 🧪 실습: normal equation은 정말 `lm()`과 같은가\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nn <- 200\nd <- data.frame(x1 = rnorm(n), x2 = rnorm(n))\nd$y <- 1.5 + 2 * d$x1 - 0.8 * d$x2 + rnorm(n, sd = 0.5)\n\nX <- cbind(intercept = 1, as.matrix(d[, c(\"x1\", \"x2\")]))\ny <- d$y\n\n# 닫힌 해를 직접 계산\nbeta_hat <- solve(t(X) %*% X) %*% t(X) %*% y\n\ndata.frame(\n  term            = c(\"intercept\", \"x1\", \"x2\"),\n  normal_equation = round(as.vector(beta_hat), 4),\n  lm              = round(unname(coef(lm(y ~ x1 + x2, data = d))), 4),\n  truth           = c(1.5, 2.0, -0.8)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       term normal_equation      lm truth\n1 intercept          1.5735  1.5735   1.5\n2        x1          1.9711  1.9711   2.0\n3        x2         -0.8101 -0.8101  -0.8\n```\n\n\n:::\n:::\n\n\n-   소수점 넷째 자리까지 동일 — `lm()`이 하는 일이 바로 이 계산\n-   실무에서는 수치 안정성을 위해 QR 분해를 사용 (결과는 동일)\n\n------------------------------------------------------------------------\n\n## 3. Gradient Descent ⛰️\n\n### 1) 아이디어\n\n-   닫힌 해가 없거나 데이터가 너무 클 때, **조금씩 내려가며** 최적해에 접근\n-   현재 지점에서 손실이 가장 가파르게 증가하는 방향 = gradient\n-   그 **반대 방향**으로 한 걸음\n\n### 2) 갱신식\n\n$$\\mathbf{w} \\leftarrow \\mathbf{w} - \\eta \\cdot \\frac{\\partial L}{\\partial \\mathbf{w}}, \\qquad\n\\frac{\\partial \\text{MSE}}{\\partial \\mathbf{w}} = \\frac{2}{m}X^{\\mathsf{T}}(X\\mathbf{w} - \\mathbf{y})$$\n\n-   $\\eta$ — learning rate (학습률)\n-   초기값에서 시작해 수렴할 때까지 반복\n\n### 3) 🧪 실습: 직접 구현하고 learning rate 바꿔보기\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngradient_descent <- function(X, y, eta, iters = 60) {\n  w <- rep(0, ncol(X)); loss <- numeric(iters)\n  for (i in 1:iters) {\n    resid  <- as.vector(X %*% w) - y\n    loss[i] <- mean(resid^2)\n    w <- w - eta * (2 / length(y)) * as.vector(t(X) %*% resid)\n  }\n  list(w = w, loss = loss)\n}\n\n# 이론적 발산 임계값: eta > 2/L (L = (2/n)X'X 의 최대 고유값)\nL <- max(eigen((2 / n) * t(X) %*% X)$values)\nround(2 / L, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.993\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nruns <- lapply(c(0.005, 0.1, 1.05), function(e) gradient_descent(X, y, e))\nnames(runs) <- c(\"eta = 0.005 (too small)\", \"eta = 0.1 (good)\", \"eta = 1.05 (diverges)\")\n\ndata.frame(\n  setting   = names(runs),\n  final_MSE = sapply(runs, function(r) signif(r$loss[60], 4)),\n  w_x1      = sapply(runs, function(r) signif(r$w[2], 4)),\n  row.names = NULL\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  setting final_MSE      w_x1\n1 eta = 0.005 (too small) 2.426e+00    0.8732\n2        eta = 0.1 (good) 2.750e-01    1.9710\n3   eta = 1.05 (diverges) 1.195e+06 -361.0000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\ncurve_df <- do.call(rbind, lapply(names(runs), function(nm)\n  data.frame(setting = nm, iter = 1:60, loss = runs[[nm]]$loss)))\ncurve_df$setting <- factor(curve_df$setting, levels = names(runs))\n\nggplot(curve_df, aes(iter, loss, colour = setting)) +\n  geom_line(linewidth = .9) +\n  scale_y_log10() +\n  scale_colour_manual(values = c(\"#7d8597\", \"#2e8b7a\", \"#d1495b\")) +\n  labs(x = \"Iteration\", y = \"MSE (log scale)\", colour = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](05_linear_model_files/figure-html/unnamed-chunk-4-1.png){width=624}\n:::\n:::\n\n\n-   **너무 작으면** — 60번 반복해도 최적해 근처에 못 감 (MSE 2.43)\n-   **적당하면** — 빠르게 수렴, `lm()` 계수와 일치 (MSE 0.275)\n-   **너무 크면** — 매 걸음이 골짜기를 건너뛰며 **발산** (MSE 1.2×10⁶)\n-   임계값 $2/L \\approx 0.993$ — 이론과 실험이 일치\n\n### 4) 변형\n\n| 방식 | 한 걸음에 쓰는 데이터 | 특징 |\n|------|---------------------|------|\n| Batch GD | 전체 | 안정적, 대용량에서 느림 |\n| **SGD** | 1개 | 빠르고 잡음 많음. local minimum 탈출에 유리 |\n| Mini-batch | 32~256개 | 실무 표준, 두 방식의 절충 |\n\n-   Momentum, Adam 등은 **걸음 크기와 방향을 적응적으로** 조절하는 확장\n\n------------------------------------------------------------------------\n\n## 4. 회귀 진단 🔬\n\n### 1) 잔차 플롯\n\n-   **잔차 vs 적합값** — 무작위로 흩어져야 정상\n    -   곡선 패턴 → 비선형 항 누락\n    -   깔때기 모양 → 이분산성 (로그 변환 고려)\n-   **Q-Q plot** — 잔차의 정규성\n-   ⚠️ 정규성 가정은 **계수 추정이 아니라 검정·신뢰구간**에 필요\n\n### 2) 다중공선성\n\n-   feature들이 서로 강하게 상관된 상태\n-   결과 — 계수가 **불안정**, 부호가 뒤집히기도\n-   $X^{\\mathsf{T}}X$ 가 거의 특이행렬이 되는 것이 원인\n-   **VIF (Variance Inflation Factor)** — 보통 5 또는 10 초과 시 주의\n-   대응 — 변수 제거, 주성분 사용(W13), **Ridge 정규화(W6)**\n\n::: {.callout-warning}\n## ⚠️ 오믹스 데이터는 다중공선성이 기본값\n\n-   같은 pathway 유전자들은 강하게 공발현\n-   → 개별 계수의 크기·부호를 해석하는 것은 위험\n-   → **예측 성능과 변수 해석을 분리해서 생각할 것**\n:::\n\n### 3) 영향점\n\n-   **Leverage** — feature 공간에서 극단에 있는 점\n-   **Cook's distance** — 그 점을 뺐을 때 계수가 얼마나 변하는가\n-   영향점은 삭제 대상이 아니라 **확인 대상** — 측정 오류인지 실제 극단값인지\n\n### 4) ⚠️ 목적에 따라 다른 기준\n\n| 목적 | 중요한 것 | 덜 중요한 것 |\n|------|----------|------------|\n| **해석·추론** | 가정 진단, 다중공선성, 신뢰구간 | 예측 성능 |\n| **예측** | 교차검증 성능(W3), 정규화 | 개별 계수의 유의성 |\n\n-   두 목적을 한 모델로 동시에 달성하려다 둘 다 놓치는 경우가 흔함\n\n------------------------------------------------------------------------\n\n## 5. Logistic Regression 🎚️\n\n### 1) 왜 선형회귀를 못 쓰는가\n\n-   $y \\in \\{0, 1\\}$ 인 이진 분류 문제\n-   선형회귀를 그대로 쓰면 — 예측값이 0 미만, 1 초과로 나감\n-   → **확률**을 모델링해야 함. 그리고 학습을 위해 **미분 가능**해야 함\n\n### 2) Odds → logit → sigmoid\n\n-   $y = 1$ 일 확률을 $p$ 라 하면\n\n$$\\text{odds} = \\frac{p}{1-p}, \\qquad \\text{logit}(p) = \\log\\frac{p}{1-p} = \\mathbf{w}^{\\mathsf{T}}\\mathbf{x} + b$$\n\n-   $p$ 는 $[0,1]$ 에 갇혀 있지만, **logit은 실수 전체**를 자유롭게 움직임\n-   역함수를 취하면 **sigmoid**\n\n$$p = \\sigma(z) = \\frac{1}{1 + e^{-z}}, \\qquad z = \\mathbf{w}^{\\mathsf{T}}\\mathbf{x} + b$$\n\n-   logit이 **link function** — 선형 형태와 확률을 잇는 다리\n\n### 3) 계수 해석 — odds ratio\n\n-   $x_j$ 가 1 증가할 때 **logit이 $w_j$ 만큼 증가**\n-   지수화하면 **odds ratio**: $\\text{OR} = e^{w_j}$\n-   OR > 1 — 위험 증가 / OR < 1 — 위험 감소\n-   ⚠️ **odds ratio는 상대위험도(RR)가 아님** — 유병률이 높으면 크게 벌어짐\n\n### 4) 🧪 실습\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nn <- 600\nclin <- data.frame(\n  age       = rnorm(n, 60, 10),\n  biomarker = rnorm(n, 0, 1)\n)\n# 진짜 관계: logit(p) = -3 + 0.04*age + 0.9*biomarker\neta_true  <- -3 + 0.04 * clin$age + 0.9 * clin$biomarker\nclin$event <- rbinom(n, 1, plogis(eta_true))\n\nfit <- glm(event ~ age + biomarker, data = clin, family = binomial)\n\ndata.frame(\n  term       = names(coef(fit)),\n  coef       = round(coef(fit), 3),\n  odds_ratio = round(exp(coef(fit)), 3),\n  OR_lower   = round(exp(confint.default(fit)[, 1]), 3),\n  OR_upper   = round(exp(confint.default(fit)[, 2]), 3),\n  row.names  = NULL\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         term   coef odds_ratio OR_lower OR_upper\n1 (Intercept) -3.858      0.021    0.006    0.073\n2         age  0.051      1.053    1.032    1.074\n3   biomarker  0.974      2.649    2.122    3.305\n```\n\n\n:::\n:::\n\n\n-   `biomarker`의 OR ≈ 2.5 — 1 표준편차 증가 시 발생 odds가 약 2.5배\n-   `age`의 OR ≈ 1.04 — **1살당** 4% 증가. 10살 차이면 $1.04^{10} \\approx 1.5$ 배\n\n::: {.callout-tip}\n## EPV — 변수를 몇 개까지 넣어도 되나\n\n-   **EPV (events per variable)** = 사건 수 / 예측변수 수\n-   경험 규칙 — **EPV ≥ 10** (Peduzzi et al. 1996)\n-   사건이 50건인데 변수 20개 → EPV 2.5 → 계수가 심하게 불안정\n-   완화 가능하다는 후속 연구도 있으나(Vittinghoff & McCulloch 2007), **사건 수가 표본 수보다 중요**하다는 원칙은 동일\n-   EPV가 부족하면 → 변수를 줄이거나 **정규화(W6)**\n:::\n\n------------------------------------------------------------------------\n\n## 6. 왜 MSE가 아니라 log loss인가 ⚖️\n\n### 1) 세 가지 이유\n\n-   **① 통계적 근거** — log loss는 베르누이 likelihood의 **음의 로그**\n    -   즉 log loss 최소화 = **MLE** (W11에서 다시 등장)\n-   **② 볼록성** — log loss는 $\\mathbf{w}$ 에 대해 전역적으로 볼록\n    -   MSE + sigmoid 조합은 **볼록성이 보장되지 않음** → 국소최소 위험\n-   **③ 기울기 소실** — 확신을 갖고 틀렸을 때 MSE는 **학습을 멈춤**\n\n$$L_{\\text{log}} = -\\frac{1}{m}\\sum_{i=1}^{m}\\Big[y_i \\log p_i + (1-y_i)\\log(1-p_i)\\Big]$$\n\n-   $y=1$ 이면 $-\\log p$ 만, $y=0$ 이면 $-\\log(1-p)$ 만 남음\n-   확신을 갖고 틀리면 손실이 **무한대로 발산** → 강하게 교정\n\n### 2) 🧪 실습: 두 손실함수의 지형\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nx  <- rnorm(200)\nyb <- rbinom(200, 1, plogis(2 * x))\nsigmoid <- function(z) 1 / (1 + exp(-z))\n\nws <- seq(-6, 12, length.out = 1200)\nmse_curve <- sapply(ws, function(w) mean((sigmoid(w * x) - yb)^2))\nlog_curve <- sapply(ws, function(w) {\n  p <- pmin(pmax(sigmoid(w * x), 1e-12), 1 - 1e-12)\n  -mean(yb * log(p) + (1 - yb) * log(1 - p))\n})\n\n# 2계 차분이 음수인 구간의 비율 = 오목한(비볼록) 구간\nconcave <- function(v) round(mean(diff(diff(v)) < 0), 3)\n\nland <- rbind(data.frame(loss = \"MSE + sigmoid\", w = ws, value = mse_curve),\n              data.frame(loss = \"Log loss\",      w = ws, value = log_curve))\nland$loss <- factor(land$loss, levels = c(\"MSE + sigmoid\", \"Log loss\"))\n\nggplot(land, aes(w, value)) +\n  geom_line(linewidth = .9, colour = \"#d1495b\") +\n  facet_wrap(~ loss, scales = \"free_y\") +\n  labs(x = \"w\", y = \"Loss\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](05_linear_model_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  loss            = c(\"MSE + sigmoid\", \"Log loss\"),\n  concave_fraction = c(concave(mse_curve), concave(log_curve)),\n  argmin_w        = round(c(ws[which.min(mse_curve)], ws[which.min(log_curve)]), 2),\n  glm_estimate    = round(rep(coef(glm(yb ~ x - 1, family = binomial))[1], 2), 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           loss concave_fraction argmin_w glm_estimate\n1 MSE + sigmoid            0.768     2.06         1.93\n2      Log loss            0.000     1.93         1.93\n```\n\n\n:::\n:::\n\n\n-   **MSE + sigmoid** — 구간의 상당 부분이 오목. 즉 **비볼록**\n    -   최적해에서 멀면 거의 평평 → gradient descent가 기어감\n-   **Log loss** — 오목 구간 0. 전 구간 **볼록**\n-   두 방법의 argmin은 결국 비슷하지만, **도달 과정이 전혀 다름**\n\n### 3) 🧪 실습: 기울기 소실\n\n-   $y=1$ 인데 모델이 $p \\approx 0$ 이라고 확신하는 상황\n-   $z$ 에 대한 기울기를 두 손실에서 비교\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- seq(0.001, 0.999, length.out = 400)\ngrad <- rbind(\n  data.frame(loss = \"MSE + sigmoid\", p = p, g = abs(2 * (p - 1) * p * (1 - p))),\n  data.frame(loss = \"Log loss\",      p = p, g = abs(p - 1))\n)\n\nggplot(grad, aes(p, g, colour = loss)) +\n  geom_line(linewidth = .9) +\n  scale_colour_manual(values = c(\"Log loss\" = \"#2e8b7a\", \"MSE + sigmoid\" = \"#d1495b\")) +\n  labs(x = \"Predicted probability (true label = 1)\",\n       y = \"|dL / dz|\", colour = NULL,\n       caption = \"left edge = confidently wrong\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](05_linear_model_files/figure-html/unnamed-chunk-8-1.png){width=624}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  p_hat   = c(0.01, 0.1, 0.5),\n  MSE     = round(abs(2 * (c(0.01, 0.1, 0.5) - 1) * c(0.01, 0.1, 0.5) *\n                      (1 - c(0.01, 0.1, 0.5))), 4),\n  log_loss = round(abs(c(0.01, 0.1, 0.5) - 1), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p_hat    MSE log_loss\n1  0.01 0.0196     0.99\n2  0.10 0.1620     0.90\n3  0.50 0.2500     0.50\n```\n\n\n:::\n:::\n\n\n-   $p = 0.01$ (완전히 틀림) — MSE의 기울기는 **0.0196**, log loss는 **0.99**\n-   약 **50배 차이**. MSE는 가장 크게 틀린 샘플에서 가장 적게 배움\n-   원인 — MSE의 기울기에 $\\sigma'(z) = p(1-p)$ 가 곱해져 양 끝에서 0으로 소멸\n-   log loss는 이 항이 **정확히 약분됨**\n\n### 4) 그래서 갱신식은 같은 모양\n\n$$\\frac{\\partial L_{\\text{log}}}{\\partial \\mathbf{w}} = \\frac{1}{m}X^{\\mathsf{T}}(\\mathbf{p} - \\mathbf{y})$$\n\n-   선형회귀의 $X^{\\mathsf{T}}(X\\mathbf{w} - \\mathbf{y})$ 와 **형태가 동일**\n-   예측값이 $X\\mathbf{w}$ 에서 $\\sigma(X\\mathbf{w})$ 로 바뀐 것뿐\n-   → 두 모델을 하나의 틀(generalized linear model)로 볼 수 있음\n\n------------------------------------------------------------------------\n\n## 7. 선형 모델의 한계와 확장 🚪\n\n### 1) 한계\n\n-   **결정경계가 직선(초평면)** — W1의 동심원 데이터에서 실패한 이유\n-   feature 간 **상호작용을 자동으로 학습하지 못함** (직접 넣어줘야 함)\n-   $p \\gg n$ 에서 닫힌 해가 존재하지 않음\n-   다중공선성에 취약\n\n### 2) 확장 경로\n\n| 한계 | 해결 | 챕터 |\n|------|------|------|\n| $p \\gg n$, 다중공선성 | Ridge / Lasso / Elastic Net | W6 |\n| 다중 class | OvO, OvR, softmax | W6 |\n| 비선형 경계 | 트리, kernel | W7, W10 |\n| 상호작용 | 트리, ensemble | W7, W9 |\n| 확률의 사전지식 | MAP, prior | W11 |\n\n::: {.callout-important}\n## Where this ends up\n\n-   MSE의 닫힌 해에 벌점 항을 더하면 → **Ridge의 닫힌 해** (W6)\n-   log loss = 음의 로그 likelihood → **MLE** (W11)\n-   여기에 prior를 곱하면 → **MAP = 정규화** (W11)\n-   sigmoid + gradient descent의 확장 → 신경망(별도 과목)\n:::\n\n------------------------------------------------------------------------\n\n## 📝 Summary\n\n-   선형 모델 $f(\\mathbf{x}) = \\mathbf{w}^{\\mathsf{T}}\\mathbf{x} + b$ — 해석 가능하고 닫힌 해가 존재\n-   최소제곱법의 해는 **normal equation**, `lm()`과 소수점까지 일치\n-   $X^{\\mathsf{T}}X$ 의 역행렬이 없으면 실패 → W6 정규화의 출발점\n-   Gradient descent — learning rate가 전부. 임계값 $2/L$ 초과 시 **발산**\n-   진단은 목적에 따라 — 해석이면 잔차·VIF, 예측이면 교차검증\n-   **오믹스는 다중공선성이 기본값** — 개별 계수 해석은 위험\n-   Logistic regression — odds → logit으로 선형화, 계수 지수화 = **odds ratio**\n-   **EPV ≥ 10** — 사건 수가 표본 수보다 중요\n-   log loss를 쓰는 이유 — MLE와 일치 / 볼록 / **기울기가 소실되지 않음**\n-   $p=0.01$ 에서 기울기 차이 약 **50배** — MSE는 가장 틀린 곳에서 가장 적게 배움\n\n## 🔑 Key terms\n\n| 용어 | 정의 |\n|------|------|\n| **MSE / square loss** | 오차 제곱의 평균. 선형회귀의 손실함수 |\n| **Normal equation** | $(X^{\\mathsf{T}}X)^{-1}X^{\\mathsf{T}}\\mathbf{y}$ — 최소제곱법의 닫힌 해 |\n| **Learning rate (η)** | gradient descent의 걸음 크기. 크면 발산, 작으면 느림 |\n| **VIF** | 다중공선성 지표. 보통 5~10 초과 시 주의 |\n| **Odds / logit** | $p/(1-p)$ 와 그 로그. logit이 선형 형태가 되도록 모델링 |\n| **Sigmoid** | logit의 역함수. 실수를 $[0,1]$ 확률로 변환 |\n| **Odds ratio** | $e^{w_j}$. 상대위험도(RR)와 다름 |\n| **Log loss / cross-entropy** | 베르누이 likelihood의 음의 로그. 볼록 |\n| **EPV** | 사건 수 / 예측변수 수. 10 이상 권장 |\n\n## ➕ References\n\n-   Hastie T, Tibshirani R, Friedman J. *The Elements of Statistical Learning.* 2nd ed., Ch. 3–4. Springer, 2009.\n-   James G, Witten D, Hastie T, Tibshirani R. *An Introduction to Statistical Learning.* 2nd ed., Ch. 3–4. Springer, 2021.\n-   Bishop CM. *Pattern Recognition and Machine Learning.* Ch. 4. Springer, 2006.\n-   Harrell FE. *Regression Modeling Strategies.* 2nd ed. Springer, 2015.\n-   Peduzzi P, Concato J, Kemper E, Holford TR, Feinstein AR. A simulation study of the number of events per variable in logistic regression analysis. *Journal of Clinical Epidemiology* 1996;49(12):1373–1379.\n-   Vittinghoff E, McCulloch CE. Relaxing the rule of ten events per variable in logistic and Cox regression. *American Journal of Epidemiology* 2007;165(6):710–718.\n-   Ruder S. An overview of gradient descent optimization algorithms. *arXiv*:1609.04747, 2016.\n\n------------------------------------------------------------------------\n\n[← W4. 성능 척도와 모델 비교](04_metrics.qmd)\n",
    "supporting": [
      "05_linear_model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}