{
  "hash": "5f93439dea4605dd92cac8feb7941244",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"W7. Decision Tree\"\ndescription: \"분할 기준, 가지치기, 결측치, 축에 평행한 경계의 한계\"\nauthor: \"Eunji Ha\"\ndate: today\n\n# ── AI 채팅 위젯 설정 ──────────────────────────────────────────\nformat:\n  html:\n    include-in-header:\n      text: |\n        <meta name=\"ai-title\" content=\"W7. Decision Tree\">\n        <meta name=\"ai-context\" content=\"\n        이 챕터는 의사결정나무를 다룹니다.\n        트리는 divide-and-conquer로 데이터를 재귀 분할하며, root node, internal node,\n        leaf node로 이루어집니다. 분할 기준은 불순도를 얼마나 줄이는가이고,\n        information entropy, Gini index, misclassification error 세 지표가 있습니다.\n        entropy는 p=0.5에서 최대 1 bit, Gini는 최대 0.5이며 Gini는 entropy의\n        이차 근사라 순위가 거의 같고 계산이 빠릅니다.\n        information gain은 다범주 feature를 선호하는 편향이 있습니다.\n        실습에서 14명짜리 표의 환자번호는 gain 0.985로 stage의 0.689보다 크지만,\n        intrinsic value가 3.807이라 gain ratio는 0.259로 stage의 0.689보다 작습니다.\n        즉 gain ratio가 환자번호 같은 무의미한 고유 식별자를 걸러냅니다.\n        가지치기는 pre-pruning과 post-pruning이 있고, CART는 cost-complexity\n        pruning을 씁니다. 실습에서 cp=0으로 키운 16-leaf 트리는 train 0.904 / test 0.837인데,\n        교차검증 오차가 최소인 지점으로 가지치기하면 leaf 5개에 test 0.853으로 오히려 좋아집니다.\n        1-SE 규칙은 leaf 4개, test 0.833으로 조금 손해 보고 단순함을 얻습니다.\n        결측치는 rpart가 surrogate split으로 행을 버리지 않고 처리합니다.\n        실습에서 CRP가 높을수록 결측이 많은 MNAR 상황을 만들면, complete case만 쓸 때\n        표본의 고CRP 비율이 30.4퍼센트에서 14.6퍼센트로 떨어집니다.\n        정확도는 0.837 대 0.857로 차이가 작지만, 학습한 집단 자체가 달라진 것이 문제입니다.\n        트리의 경계는 축에 평행하므로 대각선 경계를 계단으로 근사합니다.\n        실습에서 같은 데이터를 45도 회전시키면 leaf가 9개에서 2개로 줄고\n        test 정확도는 0.90에서 0.94로 오릅니다. 트리는 회전에 불변이 아닙니다.\n        회귀 트리는 leaf의 평균을 예측하므로 계단 함수가 되며,\n        maxdepth 1/3/6에서 leaf 2/8/36, 학습 RMSE 0.385/0.263/0.223으로 계속 떨어집니다.\n        \">\n---\n\n::: {.callout-note}\n## 🎯 Learning objectives\n\n-   트리의 재귀 분할 과정을 설명하고 적합된 트리를 규칙으로 읽을 수 있다\n-   **entropy·Gini·information gain을 손으로 계산할 수 있다**\n-   information gain의 다범주 편향과 gain ratio의 보정을 설명할 수 있다\n-   **가지치기가 왜 test 성능을 올리는지 설명하고 `cp`·1-SE 규칙으로 실행할 수 있다**\n-   결측치를 complete case로 버릴 때 생기는 문제를 말할 수 있다\n-   **축에 평행한 경계의 한계를 알고, 트리가 회전에 불변이 아님을 설명할 수 있다**\n:::\n\n> 🤔 **\"CRP가 10을 넘고 60세 이상이면 반응이 나쁘다.\" — 이 한 문장을 데이터에서 자동으로 찾아낼 수 있을까?**\n\n------------------------------------------------------------------------\n\n## 1. 트리는 어떻게 결정하는가 🌳\n\n### 1) 구조\n\n| 이름 | 개수 | 하는 일 |\n|------|------|---------|\n| **Root node** | 1개 | 모든 데이터가 여기서 시작 |\n| **Internal node** (= decision node) | 여러 개 | 한 feature에 대한 test |\n| **Leaf node** (= terminal node) | 여러 개 | 최종 결정 결과 |\n\n-   root에서 leaf까지의 경로 하나가 **규칙 하나**\n-   leaf의 예측값 — 분류는 그 leaf에 속한 샘플의 다수 class, 회귀는 평균\n\n### 2) Divide-and-conquer\n\n트리 학습은 재귀적입니다.\n\n1.  현재 node의 데이터에서 **가장 좋은 분할 feature와 분할점**을 고른다\n2.  그 기준으로 데이터를 둘(또는 여럿)로 나눈다\n3.  각 부분집합에서 1번을 반복한다\n\n종료 조건은 셋 중 하나입니다.\n\n-   node의 샘플이 모두 **같은 class** → 더 나눌 이유 없음\n-   남은 feature가 없거나 모든 샘플의 feature 값이 **동일** → 나눌 수 없음\n-   node의 샘플 수가 **너무 적음** → 나눠도 의미 없음 (`minsplit`, `minbucket`)\n\n::: {.callout-tip}\n## 탐욕적(greedy) 알고리즘이다\n\n각 단계에서 **지금 가장 좋아 보이는 분할**만 고릅니다. 전체를 놓고 최적의 트리를 찾는 문제는 NP-hard라서, 실용적인 구현은 모두 greedy입니다.\n\n→ 지금 최선이 전체 최선이라는 보장이 없습니다. 같은 데이터를 조금만 바꿔도 트리 구조가 크게 달라지는 **불안정성**의 근원이고, W9의 ensemble이 바로 이 불안정성을 역이용합니다.\n:::\n\n### 3) 🧪 실습: 트리 하나를 끝까지 읽기\n\n진짜 규칙을 심어 둔 데이터를 만들고, 트리가 그 규칙을 되찾는지 봅니다.\n\n-   진짜 규칙 — `(CRP > 10 이고 60세 초과)` **또는** `stage == 4` 이면 반응 확률 0.90, 아니면 0.12\n-   feature 4개(age, crp, stage, sex), 환자 800명 중 500명으로 학습\n\n::: {.panel-tabset}\n\n### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rpart)\n\nset.seed(2026)\nn <- 800\nd <- data.frame(\n  age   = round(rnorm(n, 58, 12)),\n  crp   = round(rexp(n, 1/8), 1),\n  stage = sample(1:4, n, TRUE),\n  sex   = factor(sample(c(\"F\", \"M\"), n, TRUE))\n)\ntrue_rule  <- with(d, (crp > 10 & age > 60) | stage == 4)\nd$response <- factor(rbinom(n, 1, ifelse(true_rule, 0.90, 0.12)),\n                     labels = c(\"No\", \"Yes\"))\n\nset.seed(11)\nidx   <- sample(nrow(d), 500)\ntrain <- d[idx, ]; test <- d[-idx, ]\n\nfit <- rpart(response ~ age + crp + stage + sex, data = train, method = \"class\")\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn= 500 \n\nnode), split, n, loss, yval, (yprob)\n      * denotes terminal node\n\n 1) root 500 197 No (0.60600000 0.39400000)  \n   2) stage< 3.5 378  85 No (0.77513228 0.22486772)  \n     4) crp< 8.45 248  26 No (0.89516129 0.10483871) *\n     5) crp>=8.45 130  59 No (0.54615385 0.45384615)  \n      10) age< 60.5 73  10 No (0.86301370 0.13698630) *\n      11) age>=60.5 57   8 Yes (0.14035088 0.85964912) *\n   3) stage>=3.5 122  10 Yes (0.08196721 0.91803279) *\n```\n\n\n:::\n:::\n\n\n### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np, pandas as pd\nfrom sklearn.tree import DecisionTreeClassifier, export_text\nfrom sklearn.model_selection import train_test_split\n\nrng = np.random.default_rng(2026)\nn = 800\nd = pd.DataFrame({\n    \"age\":   rng.normal(58, 12, n).round(),\n    \"crp\":   rng.exponential(8, n).round(1),\n    \"stage\": rng.integers(1, 5, n),\n    \"sex\":   rng.choice([0, 1], n),          # sklearn은 숫자만 받는다\n})\ntrue_rule = ((d.crp > 10) & (d.age > 60)) | (d.stage == 4)\nd[\"response\"] = rng.binomial(1, np.where(true_rule, 0.90, 0.12))\n\nX, y = d.drop(columns=\"response\"), d.response\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, train_size=500, random_state=11)\n\n# sklearn에는 rpart의 cp가 없다. 대신 깊이/leaf 크기로 제어한다\nfit = DecisionTreeClassifier(criterion=\"gini\", min_samples_leaf=20,\n                             random_state=0).fit(X_tr, y_tr)\nprint(export_text(fit, feature_names=list(X.columns)))\n```\n:::\n\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar = c(1, 1, 3, 1), xpd = NA)\nplot(fit, uniform = TRUE, branch = 1, compress = FALSE, margin = 0.16)\ntext(fit, use.n = TRUE, all = FALSE, cex = 0.9, col = \"grey15\")\ntitle(\"Classification tree (rpart default, cp = 0.01)\", line = 1)\n```\n\n::: {.cell-output-display}\n![](07_decision_tree_files/figure-html/unnamed-chunk-3-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc <- function(m, dat) mean(predict(m, dat, type = \"class\") == dat$response)\ndata.frame(\n  leaves    = sum(fit$frame$var == \"<leaf>\"),\n  train_acc = round(acc(fit, train), 3),\n  test_acc  = round(acc(fit, test), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  leaves train_acc test_acc\n1      4     0.892    0.833\n```\n\n\n:::\n:::\n\n\n트리가 찾아낸 규칙을 그대로 읽으면 이렇습니다.\n\n| 경로 | n | Yes 비율 | 해석 |\n|------|---|---------|------|\n| `stage >= 3.5` | 122 | 0.918 | 진짜 규칙의 `stage == 4` 가지 |\n| `stage < 3.5` & `crp >= 8.45` & `age >= 60.5` | 57 | 0.860 | 진짜 규칙의 `crp > 10 & age > 60` 가지 |\n| `stage < 3.5` & `crp >= 8.45` & `age < 60.5` | 73 | 0.137 | 나이가 안 되면 반응 없음 |\n| `stage < 3.5` & `crp < 8.45` | 248 | 0.105 | 나머지 |\n\n-   leaf 4개로 **두 가지 규칙을 모두 되찾았습니다**\n-   분할점은 10이 아니라 **8.45**, 60이 아니라 **60.5** — 트리는 진짜 임계값을 아는 게 아니라 **관측된 데이터에서 가장 잘 나누는 지점**을 고릅니다\n-   ⚠️ 그러니 분할점을 임상적 컷오프처럼 해석하면 안 됩니다. 데이터를 조금만 바꿔도 8.45는 흔들립니다\n\n### 4) 왜 아직도 쓰는가\n\n-   **샘플 단위로 설명 가능** — \"이 환자는 stage 4라서 Yes\"라고 경로 하나로 말할 수 있음\n-   **전처리가 거의 필요 없음** — 스케일링 불필요, 단조변환(log 등)에 **불변**, 범주형을 그대로 취급\n-   **비선형과 상호작용을 자동으로** — 위 실습의 `crp`와 `age` 상호작용을 따로 지정하지 않았습니다\n-   계산복잡성 대비 예측 성능이 좋고, 결측치도 버리지 않음(4절)\n\n::: {.callout-tip}\n## 그림은 `rpart.plot`이 훨씬 낫습니다\n\n이 사이트는 CI 의존성을 줄이려고 base `plot.rpart`를 쓰지만, 직접 분석할 때는 `rpart.plot::rpart.plot(fit, extra = 104)` 를 쓰면 각 node의 확률과 샘플 비율까지 한눈에 들어옵니다.\n:::\n\n------------------------------------------------------------------------\n\n## 2. 분할 기준 ✂️\n\n### 1) Purity\n\n-   분할 후의 node가 **최대한 같은 class끼리 모이도록** 하는 것이 목표\n-   node의 purity ↑ = uncertainty ↓\n-   \"얼마나 섞여 있는가\"를 재는 것이 **불순도(impurity)** 지표\n\n### 2) Information entropy\n\n$$\\mathrm{Ent}(D) = -\\sum_{k=1}^{|\\mathcal{Y}|} p_k \\log_2 p_k$$\n\n-   $p_k$ — node $D$ 에서 $k$ 번째 class의 비율\n-   값이 **작을수록 purity가 높음**. 한 class만 있으면 0\n-   이진 분류에서 $p = 0.5$ 일 때 최대 **1 bit**\n\n### 3) Gini index\n\n$$\\mathrm{Gini}(D) = 1 - \\sum_{k=1}^{|\\mathcal{Y}|} p_k^2$$\n\n-   \"이 node에서 임의로 두 샘플을 뽑았을 때 class가 다를 확률\"\n-   이진에서 최대 **0.5** ($p = 0.5$)\n-   $\\log$ 가 없어 **계산이 빠름**. CART와 `rpart`의 기본값\n\n### 4) Information gain\n\n분할 전 불순도에서 분할 후 **가중평균** 불순도를 뺀 값입니다.\n\n$$\\mathrm{Gain}(D, a) = \\mathrm{Ent}(D) - \\sum_{v=1}^{V} \\frac{|D^v|}{|D|}\\,\\mathrm{Ent}(D^v)$$\n\n-   $V$ — feature $a$ 로 나눴을 때 생기는 가지 수, $D^v$ — $v$ 번째 가지의 샘플\n-   **gain이 가장 큰 feature로 분할** (ID3의 기준)\n-   가중치 $|D^v|/|D|$ 가 핵심 — 샘플이 많은 가지의 불순도가 더 중요\n\n### 5) 🧪 실습: 불순도 세 지표\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\np <- seq(0.001, 0.999, length.out = 300)\nimp <- data.frame(\n  p       = rep(p, 3),\n  value   = c(-p * log2(p) - (1 - p) * log2(1 - p),   # entropy\n              2 * p * (1 - p),                         # Gini\n              pmin(p, 1 - p)),                         # misclassification\n  measure = rep(c(\"Entropy (bits)\", \"Gini\", \"Misclassification\"), each = length(p))\n)\n\nggplot(imp, aes(p, value, colour = measure)) +\n  geom_line(linewidth = .9) +\n  scale_colour_manual(values = c(\"Entropy (bits)\"    = \"#d1495b\",\n                                 \"Gini\"              = \"#2e8b7a\",\n                                 \"Misclassification\" = \"#7d8597\")) +\n  labs(x = \"Proportion of class 1\", y = \"Impurity\",\n       colour = NULL,\n       caption = \"all three peak at p = 0.5 and vanish at p = 0 or 1\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_decision_tree_files/figure-html/unnamed-chunk-5-1.png){width=624}\n:::\n:::\n\n\n-   셋 다 $p = 0.5$ 에서 최대, 순수한 node(0 또는 1)에서 0\n-   **Gini는 entropy의 이차 근사** — 모양이 거의 같아 실제로 선택 순위가 잘 바뀌지 않음. 그래서 빠른 Gini가 기본값\n-   **misclassification error는 뾰족하고 평평** — 불순도가 줄어도 값이 안 변하는 구간이 있어 **분할 기준으로는 부적합**. 가지치기 단계에서만 씁니다\n\n### 6) Gain ratio — 다범주 편향\n\ninformation gain에는 **가지를 많이 만드는 feature를 편애하는 편향**이 있습니다. 극단적으로 환자번호로 나누면 모든 leaf가 순수해져 gain이 최대가 됩니다. 물론 쓸모는 0입니다.\n\n$$\\mathrm{Gain\\_ratio}(D,a) = \\frac{\\mathrm{Gain}(D,a)}{\\mathrm{IV}(a)}, \\qquad\n\\mathrm{IV}(a) = -\\sum_{v=1}^{V} \\frac{|D^v|}{|D|} \\log_2 \\frac{|D^v|}{|D|}$$\n\n-   **IV (intrinsic value)** — feature 자체가 데이터를 얼마나 잘게 쪼개는가. 가지가 많을수록 큼\n-   가지를 많이 만들수록 분모가 커져 **자동으로 벌점**\n-   C4.5의 기준. 단, gain ratio는 반대로 가지가 적은 feature를 편애하므로, C4.5는 **gain이 평균 이상인 후보 중에서** gain ratio가 최대인 것을 고릅니다\n\n### 7) 🧪 실습: gain은 환자번호를 고른다\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD <- data.frame(\n  sample_id = sprintf(\"S%02d\", 1:14),\n  stage     = c(\"early\",\"early\",\"late\",\"late\",\"late\",\"early\",\"late\",\n                \"early\",\"early\",\"late\",\"early\",\"late\",\"late\",\"early\"),\n  outcome   = c(\"No\",\"No\",\"Yes\",\"Yes\",\"Yes\",\"No\",\"Yes\",\n                \"No\",\"No\",\"Yes\",\"Yes\",\"Yes\",\"Yes\",\"No\")\n)\n\nent  <- function(y) { p <- table(y) / length(y); p <- p[p > 0]; -sum(p * log2(p)) }\ngain <- function(x, y) ent(y) - sum(tapply(y, x, function(s) length(s)/length(y) * ent(s)))\niv   <- function(x) { p <- table(x) / length(x); -sum(p * log2(p)) }\n\ng <- c(gain(D$stage, D$outcome), gain(D$sample_id, D$outcome))\nv <- c(iv(D$stage), iv(D$sample_id))\n\ndata.frame(\n  feature         = c(\"stage\", \"sample_id\"),\n  gain            = round(g, 4),\n  intrinsic_value = round(v, 4),\n  gain_ratio      = round(g / v, 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    feature   gain intrinsic_value gain_ratio\n1     stage 0.6894          1.0000     0.6894\n2 sample_id 0.9852          3.8074     0.2588\n```\n\n\n:::\n:::\n\n\n-   전체 불순도 $\\mathrm{Ent}(D) = 0.9852$\n-   **gain 기준** — `sample_id` 0.9852 > `stage` 0.6894 → **환자번호를 고른다**\n-   환자번호는 14개 가지를 만들어 IV가 $\\log_2 14 = 3.807$\n-   **gain ratio 기준** — `stage` 0.6894 > `sample_id` 0.2588 → **제대로 고른다**\n\n::: {.callout-warning}\n## 오믹스 데이터에서 실제로 일어나는 일\n\n샘플 ID, 배치 번호, 채취 날짜, 플레이트 위치처럼 **고유값이 많은 열**을 실수로 feature에 남겨두면, 트리는 그것을 먼저 고릅니다. 학습 정확도는 1.0이 되고 test에서 무너집니다.\n\n→ 모델에 넣기 전 feature 목록을 눈으로 확인할 것. 그리고 `rpart`는 gain ratio를 쓰지 않으므로(Gini 기본) 이 방어막이 없습니다.\n:::\n\n------------------------------------------------------------------------\n\n## 3. 가지치기 🪓\n\n### 1) Full tree는 반드시 과적합한다\n\n-   끝까지 키우면 모든 leaf의 purity가 100%\n-   training error는 0에 수렴하지만 **validation error는 감소하다 다시 증가**\n-   그 변곡점에서 가지를 **되돌려 붙이는 것**이 가지치기\n\n### 2) Pre-pruning vs post-pruning\n\n| | **Pre-pruning** | **Post-pruning** |\n|---|---|---|\n| 시점 | 분할 **전**에 중단 판단 | 일단 다 키운 **뒤** 잘라냄 |\n| 기준 | 이 분할이 validation 성능을 올리는가 | 이 가지를 없애면 성능이 나빠지는가 |\n| 계산량 | 적음 | 많음 |\n| 위험 | **지평선 효과** — 지금은 이득이 없어도 한 번 더 나누면 좋아질 분할을 미리 차단 | — |\n| 일반적 성능 | 과소적합 쪽으로 기울기 쉬움 | 보통 더 좋음 |\n| R 구현 | `minsplit`, `minbucket`, `maxdepth` | `prune()` + `cp` |\n\n### 3) Cost-complexity pruning (CART)\n\n`rpart`가 쓰는 방식입니다. leaf 수에 벌점을 매겨 **오차와 복잡도를 함께** 최소화합니다.\n\n$$R_\\alpha(T) = R(T) + \\alpha\\,|T|$$\n\n-   $R(T)$ — 트리 $T$ 의 오분류율, $|T|$ — leaf 수, $\\alpha$ — 복잡도 벌점\n-   $\\alpha$ 를 0에서 키우면 **가지가 순서대로 잘려나가는 중첩된 트리 열**이 생김\n-   `rpart`의 `cp` 는 이 $\\alpha$ 를 root 오차로 나눈 상대값\n-   적절한 $\\alpha$ 는 **교차검증(`xerror`)으로 선택** — W6의 λ 선택과 완전히 같은 구조\n\n::: {.callout-tip}\n## 1-SE 규칙\n\n`xerror`가 최소인 지점 대신, **최소값 + 표준오차 1개(`xstd`) 이내에서 가장 단순한 트리**를 고르는 관례입니다. W6의 `lambda.1se`와 같은 발상 — 교차검증 오차 자체가 추정치라서, 최소점을 그대로 믿으면 CV 잡음에 과적합합니다.\n:::\n\n### 4) 🧪 실습: 가지치기가 test 성능을 올린다\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nbig <- rpart(response ~ age + crp + stage + sex, data = train, method = \"class\",\n             control = rpart.control(cp = 0, minsplit = 10, minbucket = 5, xval = 10))\n\ncpt   <- big$cptable\ni_min <- which.min(cpt[, \"xerror\"])\nthr   <- cpt[i_min, \"xerror\"] + cpt[i_min, \"xstd\"]     # 1-SE 기준선\ni_1se <- which(cpt[, \"xerror\"] <= thr)[1]\n\np_min <- prune(big, cp = cpt[i_min, \"CP\"])\np_1se <- prune(big, cp = cpt[i_1se, \"CP\"])\n\ndata.frame(\n  tree      = c(\"Full (cp = 0)\", \"Min xerror\", \"1-SE rule\"),\n  leaves    = c(sum(big$frame$var   == \"<leaf>\"),\n                sum(p_min$frame$var == \"<leaf>\"),\n                sum(p_1se$frame$var == \"<leaf>\")),\n  train_acc = round(c(acc(big, train), acc(p_min, train), acc(p_1se, train)), 3),\n  test_acc  = round(c(acc(big, test),  acc(p_min, test),  acc(p_1se, test)),  3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           tree leaves train_acc test_acc\n1 Full (cp = 0)     16     0.904    0.837\n2    Min xerror      5     0.896    0.853\n3     1-SE rule      4     0.892    0.833\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncp_df <- data.frame(nsplit = cpt[, \"nsplit\"], xerror = cpt[, \"xerror\"],\n                    xstd   = cpt[, \"xstd\"])\n\nggplot(cp_df, aes(nsplit, xerror)) +\n  geom_errorbar(aes(ymin = xerror - xstd, ymax = xerror + xstd),\n                width = .25, colour = \"grey60\") +\n  geom_line(linewidth = .8, colour = \"#d1495b\") +\n  geom_point(size = 1.8, colour = \"#d1495b\") +\n  geom_hline(yintercept = thr, linetype = 2) +\n  labs(x = \"Number of splits\", y = \"Cross-validated error (xerror)\",\n       caption = \"dashed = minimum xerror + 1 SE\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_decision_tree_files/figure-html/unnamed-chunk-8-1.png){width=624}\n:::\n:::\n\n\n-   **Full tree** — leaf 16개. train 0.904인데 test 0.837 (전형적 과적합)\n-   **Min xerror** — leaf 5개로 잘라내니 test가 오히려 **0.853으로 상승**\n-   **1-SE** — leaf 4개, test 0.833. 정확도를 조금 내주고 **가장 단순한 트리**를 얻음\n-   가지를 4개 이상 만들어도 `xerror`가 더 떨어지지 않습니다. 그 뒤는 전부 노이즈 학습\n\n------------------------------------------------------------------------\n\n## 4. 연속형 값과 결측치 🔢\n\n### 1) 연속형 값 — bi-partitioning\n\n-   연속형 feature는 후보 분할점 $t$ 를 정해 $\\{x \\le t\\}$ / $\\{x > t\\}$ 둘로 나눔\n-   후보 $t$ — 정렬한 값들의 **인접한 두 값의 중점**. $n$ 개 값이면 후보는 최대 $n-1$ 개\n-   각 후보의 information gain(또는 Gini 감소)을 모두 계산해 **최대인 곳**을 선택\n-   ⚠️ 이산형 feature는 한 번 쓰면 끝이지만, **연속형은 하위 node에서 또 쓸 수 있습니다** (위 실습에서 `crp`가 두 번 등장)\n\n### 2) 결측치 — 버리지 않는 두 가지 방법\n\n**① 비율 보정 information gain (C4.5)**\n\n$$\\mathrm{Gain}(D, a) = \\rho \\times \\left( \\mathrm{Ent}(\\tilde{D}) - \\sum_{v=1}^{V} \\tilde{r}_v\\,\\mathrm{Ent}(\\tilde{D}^v) \\right)$$\n\n-   $\\rho$ — feature $a$ 의 **값이 있는 샘플의 비율**, $\\tilde{D}$ — 값이 있는 샘플만 모은 집합\n-   결측이 많은 feature는 $\\rho$ 가 작아 **gain이 자동으로 깎임**\n-   분할할 때 결측 샘플은 **모든 가지에 가중치를 나눠** 내려보냄\n\n**② Surrogate split (CART, `rpart`의 기본)**\n\n-   1순위 분할 feature가 결측인 샘플을 위해, **그 분할을 가장 비슷하게 재현하는 대체 feature**를 미리 찾아둠\n-   예: `crp`가 결측이면 이전 방문의 `crp`나 다른 염증 지표로 대신 판정\n-   `summary(fit)` 의 `Surrogate splits` 항목에서 확인할 수 있음\n-   ⚠️ 대체 feature가 **원래 feature와 상관이 있어야** 작동합니다. 상관이 없으면 다수 가지로 보낼 뿐\n\n### 3) 🧪 실습: complete case가 조용히 바꾸는 것\n\n-   **CRP가 높을수록 검사 결측이 많은** 상황 (염증이 심해 검체 품질이 나쁜 경우 — MNAR)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(5)\ntr_na <- train\ntr_na$crp[runif(nrow(tr_na)) < ifelse(tr_na$crp > 10, 0.65, 0.10)] <- NA\ncc <- na.omit(tr_na)\n\ndata.frame(\n  dataset  = c(\"Full training set\", \"Complete cases only\"),\n  n        = c(nrow(tr_na), nrow(cc)),\n  high_crp = round(c(mean(train$crp > 10), mean(cc$crp > 10)), 3),\n  mean_age = round(c(mean(tr_na$age), mean(cc$age)), 1)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              dataset   n high_crp mean_age\n1   Full training set 500    0.304     57.9\n2 Complete cases only 363    0.146     57.8\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_cc  <- rpart(response ~ age + crp + stage + sex, data = cc,    method = \"class\")\nm_sur <- rpart(response ~ age + crp + stage + sex, data = tr_na, method = \"class\")\n\ndata.frame(\n  model    = c(\"Trained on complete cases\", \"Trained on all rows (surrogate)\"),\n  n_used   = c(nrow(cc), nrow(tr_na)),\n  leaves   = c(sum(m_cc$frame$var == \"<leaf>\"), sum(m_sur$frame$var == \"<leaf>\")),\n  test_acc = round(c(acc(m_cc, test), acc(m_sur, test)), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            model n_used leaves test_acc\n1       Trained on complete cases    363      4    0.837\n2 Trained on all rows (surrogate)    500      4    0.857\n```\n\n\n:::\n:::\n\n\n-   500명 중 137명의 CRP가 사라졌고, complete case는 363명\n-   **고CRP 환자 비율이 0.304 → 0.146으로 반토막** — 나이 분포는 그대로인데 관심 있는 집단만 빠졌습니다\n-   test 정확도는 0.837 vs 0.857로 차이가 작습니다. **이게 함정입니다**\n-   ✅ 진짜 손해는 정확도가 아니라 **모형이 학습한 집단이 달라졌다**는 것. 이 모형의 결론을 원래 코호트에 일반화할 수 없습니다\n-   논문에 쓴다면 — 결측 비율, 결측 메커니즘, 어떻게 처리했는지를 **반드시 보고** (W14의 TRIPOD+AI)\n\n------------------------------------------------------------------------\n\n## 5. 축에 평행한 경계 📐\n\n### 1) 한계\n\n-   각 분할은 `feature < 값` 형태라, 경계는 항상 **한 축에 수직**\n-   진짜 경계가 대각선이면 트리는 **계단으로 근사**할 수밖에 없음\n-   계단을 촘촘히 만들수록 분할이 많아지고 → 과적합, 그리고 해석력도 사라짐\n\n### 2) 🧪 실습: 45도만 돌려도 트리가 달라진다\n\n진짜 경계가 $x_1 + x_2 = 0$ 인 데이터를, **원래 축**과 **45도 회전한 축**에서 각각 학습합니다. 데이터는 완전히 같고 좌표계만 다릅니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nm  <- 600\ngd <- data.frame(x1 = runif(m, -3, 3), x2 = runif(m, -3, 3))\ngd$y <- factor(ifelse(gd$x1 + gd$x2 + rnorm(m, 0, .4) > 0, \"B\", \"A\"))\n\nth <- pi / 4                                   # 45도 회전한 좌표\ngd$r1 <-  gd$x1 * cos(th) + gd$x2 * sin(th)\ngd$r2 <- -gd$x1 * sin(th) + gd$x2 * cos(th)\n\nti <- 1:400; te2 <- 401:m\nt_orig <- rpart(y ~ x1 + x2, data = gd[ti, ], method = \"class\")\nt_rot  <- rpart(y ~ r1 + r2, data = gd[ti, ], method = \"class\")\n\na2 <- function(mod, dat) mean(predict(mod, dat, type = \"class\") == dat$y)\ndata.frame(\n  axes     = c(\"Original (x1, x2)\", \"Rotated 45 deg (r1, r2)\"),\n  leaves   = c(sum(t_orig$frame$var == \"<leaf>\"), sum(t_rot$frame$var == \"<leaf>\")),\n  test_acc = round(c(a2(t_orig, gd[te2, ]), a2(t_rot, gd[te2, ])), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     axes leaves test_acc\n1       Original (x1, x2)      9     0.90\n2 Rotated 45 deg (r1, r2)      2     0.94\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- expand.grid(x1 = seq(-3, 3, length.out = 160),\n                    x2 = seq(-3, 3, length.out = 160))\ngrid$r1 <-  grid$x1 * cos(th) + grid$x2 * sin(th)\ngrid$r2 <- -grid$x1 * sin(th) + grid$x2 * cos(th)\n\nmk <- function(mod, nm) {\n  g <- grid; g$pred <- predict(mod, g, type = \"class\"); g$panel <- nm; g\n}\nregions <- rbind(mk(t_orig, \"Tree on x1, x2\"),\n                 mk(t_rot,  \"Tree on rotated axes\"))\nregions$panel <- factor(regions$panel,\n                        levels = c(\"Tree on x1, x2\", \"Tree on rotated axes\"))\n\nggplot(regions, aes(x1, x2)) +\n  geom_raster(aes(fill = pred), alpha = .35) +\n  geom_point(data = gd[te2, ], aes(colour = y), size = .7) +\n  scale_fill_manual(values   = c(A = \"#2e8b7a\", B = \"#d1495b\")) +\n  scale_colour_manual(values = c(A = \"#2e8b7a\", B = \"#d1495b\")) +\n  facet_wrap(~ panel) +\n  labs(fill = \"Predicted\", colour = \"Actual\",\n       caption = \"same data, same algorithm - only the coordinate system differs\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_decision_tree_files/figure-html/unnamed-chunk-12-1.png){width=768}\n:::\n:::\n\n\n-   **원래 축** — leaf 9개로 대각선을 계단으로 근사. test 0.900\n-   **회전한 축** — leaf **2개**, 즉 분할 한 번. test 0.940\n-   같은 데이터인데 좌표계만 바꿔 성능과 복잡도가 모두 나아졌습니다\n-   ✅ **트리는 회전에 불변이 아닙니다.** 스케일링에는 불변인데 회전에는 아닙니다\n-   → 그래서 PCA 등으로 축을 돌린 뒤 트리를 쓰면 좋아질 때가 있습니다. 대신 축의 해석력을 잃습니다 (W13)\n\n### 3) Multivariate (oblique) decision tree\n\n-   각 node에서 feature 하나가 아니라 **선형 결합**으로 분할\n\n$$\\sum_{i=1}^{d} w_i a_i \\le t$$\n\n-   경계가 축에 평행할 필요가 없어져 **대각선을 한 번에** 자름\n-   node마다 작은 선형 분류기를 학습하는 셈 — 트리가 훨씬 작아짐\n-   단점 — 계산량이 크고, `-0.800 × CRP - 0.444 × 나이 ≤ -0.313` 같은 조건은 **해석력이 사라짐**\n-   실무에서는 oblique tree보다 **ensemble(W9)** 로 가는 편이 일반적입니다\n\n------------------------------------------------------------------------\n\n## 6. 알고리즘 계열과 회귀 트리 🧬\n\n### 1) 계열 정리\n\n| | **ID3** | **C4.5** | **CART** | **CHAID** |\n|---|---|---|---|---|\n| 분할 기준 | Information gain | Gain ratio | **Gini** (분류) / SSE (회귀) | 카이제곱 검정 |\n| 분할 형태 | 다지 분할 | 다지 분할 | **항상 이진 분할** | 다지 분할 |\n| 연속형 | 불가 | 가능 | 가능 | 구간화 필요 |\n| 결측치 | 불가 | 비율 보정 | **Surrogate split** | 별도 범주 |\n| 가지치기 | 없음 | 오차 기반 | **Cost-complexity** | 사전 중단 |\n| 회귀 | 불가 | 불가 | **가능** | 가능 |\n| 구현 | — | `RWeka::J48` | **`rpart`**, `sklearn` | `CHAID` |\n\n-   `rpart`와 `sklearn.tree`는 모두 **CART 계열**입니다. 그래서 gain ratio 옵션이 없습니다\n-   `sklearn`은 `criterion=\"entropy\"` 를 줄 수 있지만 분할은 여전히 이진입니다\n\n### 2) 회귀 트리\n\n-   분할 기준을 불순도 대신 **오차제곱합(SSE)** 으로 바꾸면 그대로 회귀에 씁니다\n\n$$\\text{SSE} = \\sum_{v} \\sum_{i \\in D^v} (y_i - \\bar{y}_v)^2$$\n\n-   leaf의 예측값 = 그 leaf에 속한 샘플의 **평균**\n-   따라서 예측은 **계단 함수** — 구간 안에서는 모두 같은 값\n-   ⚠️ **외삽이 불가능합니다.** 학습 데이터 범위 밖은 가장 가까운 leaf의 평균을 그대로 반복\n\n### 3) 🧪 실습: 깊이가 만드는 계단\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\nrd <- data.frame(x = sort(runif(250, 0, 6)))\nrd$y <- sin(rd$x) + rnorm(250, 0, .25)\n\nsteps <- do.call(rbind, lapply(c(1, 3, 6), function(dp) {\n  rt <- rpart(y ~ x, data = rd, method = \"anova\",\n              control = rpart.control(maxdepth = dp, cp = 0, minsplit = 5, xval = 0))\n  data.frame(x = rd$x, fit = predict(rt),\n             panel = sprintf(\"maxdepth = %d  (%d leaves)\",\n                             dp, sum(rt$frame$var == \"<leaf>\")))\n}))\n\nggplot(rd, aes(x, y)) +\n  geom_point(size = .7, colour = \"grey55\") +\n  geom_line(data = steps, aes(x, fit), linewidth = .9, colour = \"#d1495b\") +\n  facet_wrap(~ panel) +\n  labs(caption = \"leaf prediction = mean of that leaf -> piecewise constant\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](07_decision_tree_files/figure-html/unnamed-chunk-13-1.png){width=768}\n:::\n:::\n\n\n-   `maxdepth = 1` — 분할 한 번, 계단 2칸. 곡선을 전혀 못 따라감\n-   `maxdepth = 3` — 8칸. 사인 곡선의 모양이 보이기 시작\n-   `maxdepth = 6` — 36칸. **노이즈까지 따라가기 시작** (학습 RMSE 0.385 → 0.263 → 0.223으로 계속 떨어지지만, 그건 과적합의 증상입니다)\n-   부드러운 함수를 트리로 근사하려면 계단이 아주 많이 필요합니다 → 회귀는 선형 모델이나 ensemble이 보통 낫습니다\n\n::: {.callout-warning}\n## ⚠️ 트리를 쓸 때 반드시 확인할 것\n\n-   **고유값이 많은 열**(ID, 배치, 날짜)이 feature에 섞여 있지 않은가 — 트리가 가장 먼저 집어 듭니다\n-   **가지치기를 했는가** — `rpart` 기본값(`cp = 0.01`)은 가벼운 사전 가지치기일 뿐, 교차검증 기반이 아닙니다\n-   **분할점을 임상 컷오프로 해석하지 않았는가** — 데이터가 조금만 바뀌어도 흔들립니다\n-   **단일 트리의 성능을 그대로 보고하지 않았는가** — 트리는 불안정합니다. 반복 분할로 분산을 함께 보고할 것\n-   트리의 변수 중요도는 **상관된 feature에서 왜곡**됩니다 (W14)\n:::\n\n::: {.callout-important}\n## Where this ends up\n\n-   트리의 **불안정성을 역이용**하는 bagging과 random forest → W9\n-   잔차를 순차적으로 맞추는 gradient boosting, XGBoost → W9\n-   축에 평행한 경계를 **kernel로 우회**하는 방법 → W10\n-   PCA로 축을 돌린 뒤 트리를 쓰는 전략 → W13\n-   트리 기반 변수 중요도와 SHAP → W14\n:::\n\n------------------------------------------------------------------------\n\n## 📝 Summary\n\n-   트리는 **greedy 재귀 분할** — 매 단계에서 불순도를 가장 많이 줄이는 분할을 고름\n-   불순도는 **entropy**(최대 1 bit) / **Gini**(최대 0.5) / misclassification. Gini는 entropy의 이차 근사라 빠르고 순위가 거의 같음\n-   **information gain은 가지를 많이 만드는 feature를 편애** — 환자번호가 gain 0.985로 stage의 0.689를 이김. gain ratio는 IV 3.807로 나눠 0.259로 끌어내림\n-   **full tree는 반드시 과적합** — leaf 16개 train 0.904 / test 0.837 → 가지치기 후 leaf 5개 test **0.853**\n-   $\\alpha$(= `cp`)는 **교차검증으로 선택**, 단순함을 원하면 **1-SE 규칙** (W6의 `lambda.1se`와 같은 구조)\n-   연속형은 인접 값의 중점을 후보로 bi-partitioning, **하위 node에서 다시 쓸 수 있음**\n-   결측치는 **버리지 말 것** — complete case로 고CRP 비율이 0.304 → 0.146으로 바뀜. 정확도 차이는 작아도 **학습한 집단이 달라짐**\n-   **트리는 회전에 불변이 아니다** — 같은 데이터를 45도 돌리면 leaf 9개 → 2개, test 0.900 → 0.940\n-   회귀 트리는 leaf 평균을 예측하는 **계단 함수**이고 **외삽이 불가능**\n\n## 🔑 Key terms\n\n| 용어 | 정의 |\n|------|------|\n| **Divide-and-conquer** | node를 재귀적으로 분할해 트리를 키우는 전략 |\n| **Purity / impurity** | node 안 class가 얼마나 한쪽으로 모여 있는가 |\n| **Information entropy** | $-\\sum p_k \\log_2 p_k$. 이진에서 최대 1 bit |\n| **Gini index** | $1 - \\sum p_k^2$. 두 샘플의 class가 다를 확률. CART 기본 |\n| **Information gain** | 분할 전 불순도 − 분할 후 가중평균 불순도 |\n| **Intrinsic value (IV)** | feature가 데이터를 얼마나 잘게 쪼개는가. gain ratio의 분모 |\n| **Gain ratio** | gain / IV. 다범주 편향을 보정 (C4.5) |\n| **Pre-pruning** | 분할하기 전에 중단. 빠르지만 지평선 효과 |\n| **Post-pruning** | 다 키운 뒤 잘라냄. 계산량이 크지만 보통 더 좋음 |\n| **Cost-complexity (`cp`)** | $R(T) + \\alpha|T|$ 를 최소화하는 CART의 가지치기 |\n| **Surrogate split** | 1순위 feature가 결측일 때 대신 쓰는 대체 분할 |\n| **Axis-parallel boundary** | 한 축에 수직인 결정 경계. 대각선은 계단으로 근사 |\n| **Oblique tree** | $\\sum w_i a_i \\le t$ 로 분할하는 다변량 트리 |\n\n## ➕ References\n\n-   Quinlan JR. Induction of decision trees. *Machine Learning* 1986;1(1):81–106.\n-   Quinlan JR. *C4.5: Programs for Machine Learning*. Morgan Kaufmann, 1993.\n-   Breiman L, Friedman J, Olshen R, Stone C. *Classification and Regression Trees*. Wadsworth, 1984.\n-   Therneau TM, Atkinson EJ. *An Introduction to Recursive Partitioning Using the RPART Routines*. Mayo Foundation technical report, 2022.\n-   Hastie T, Tibshirani R, Friedman J. *The Elements of Statistical Learning*, 2nd ed. Springer, 2009. Ch. 9.2.\n-   Strobl C, Boulesteix AL, Augustin T. Unbiased split selection for classification trees based on the Gini index. *Computational Statistics & Data Analysis* 2007;52(1):483–501.\n-   Loh WY. Fifty years of classification and regression trees. *International Statistical Review* 2014;82(3):329–348.\n\n------------------------------------------------------------------------\n\n[← W6. 정규화 · LDA · 다중분류 · 불균형](06_regularization.qmd)\n",
    "supporting": [
      "07_decision_tree_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}