{
  "hash": "2736fd1015a14ce252df6cffe9c0b709",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"W12. Clustering\"\ndescription: \"성능 척도, 거리, k-means와 GMM, DBSCAN, 계층적 군집, 그래프 기반 군집(Louvain)\"\nauthor: \"Eunji Ha\"\ndate: today\n\n# ── AI 채팅 위젯 설정 ──────────────────────────────────────────\nformat:\n  html:\n    include-in-header:\n      text: |\n        <meta name=\"ai-title\" content=\"W12. Clustering\">\n        <meta name=\"ai-context\" content=\"\n        이 챕터는 label 없이 데이터의 구조를 찾는 군집화를 다룹니다.\n        군집화에는 정답이 없고 알고리즘마다 군집의 정의가 다릅니다.\n        외부 지표는 정답 label과 비교하는 것으로 샘플 쌍을 a SS, b SD, c DS, d DD 네 종류로 셉니다.\n        Jaccard, FM index, Rand index가 있고 Rand index는 무작위 label에도 높게 나옵니다.\n        실습에서 무작위 label의 군집 수를 50개로 늘리면 RI가 0.7417까지 오르지만 ARI는 0 근처입니다.\n        그래서 우연 수준을 보정한 adjusted Rand index를 씁니다.\n        내부 지표는 정답 없이 군집 내 응집과 군집 간 분리를 봅니다.\n        Davies-Bouldin은 작을수록, Dunn과 silhouette은 클수록 좋습니다.\n        blob 4개 데이터에서 세 지표가 모두 k=4를 고릅니다.\n        거리는 비음성, 동일성, 대칭성, 삼각부등식을 만족해야 합니다.\n        Minkowski p가 바뀌면 가장 가까운 이웃이 바뀝니다.\n        단위가 다른 feature는 표준화하지 않으면 큰 단위가 거리를 지배해 ARI가 0.0045였다가 표준화하면 1이 됩니다.\n        범주형은 VDM으로 값 사이 거리를 정의합니다.\n        발현 데이터에서는 correlation distance가 크기가 아니라 패턴으로 묶습니다.\n        cosine distance와 1 빼기 상관은 삼각부등식을 어기는 비척도 거리입니다.\n        k-means는 군집 내 제곱합을 최소화하고 Lloyd 알고리즘은 국소해만 보장합니다.\n        blob 8개에서 무작위 초기화는 200번 중 25.5퍼센트만 전역해에 도달하고 k-means++는 36퍼센트입니다.\n        k 선택은 elbow, silhouette, gap statistic으로 하는데 서로 다른 답을 줄 수 있습니다.\n        k-means는 구형 군집을 가정해서 길쭉한 군집에서 ARI 0.5953에 그치고\n        full covariance GMM을 EM으로 풀면 0.9933입니다.\n        DBSCAN은 밀도로 군집을 정의하고 core, border, noise 점을 구분합니다.\n        반달 두 개에서 k-means ARI 0.2791, DBSCAN 0.9657입니다.\n        그러나 eps에 극도로 민감하고 밀도가 다른 군집이 섞이면 eps 하나로는 안 됩니다. 그래서 HDBSCAN이 나왔습니다.\n        계층적 군집에서 single linkage는 다리 하나로 두 군집을 사슬처럼 잇습니다.\n        그래프 기반 군집은 kNN 그래프를 만들고 modularity를 최대화하는 Louvain이나 Leiden으로 나눕니다.\n        단일세포 모사 데이터에서 k-means k=5는 큰 유형을 쪼개고 희귀 유형을 합쳐 ARI 0.7732입니다.\n        Louvain은 군집 수 4개를 스스로 정하고 ARI 0.9860이지만 20개짜리 희귀 유형은 가까운 유형에 합쳐집니다.\n        resolution을 올리면 희귀 유형보다 큰 군집이 먼저 쪼개집니다.\n        합쳐진 군집만 떼어 다시 PCA를 하고 sub-clustering하면 희귀 유형이 분리되지만 균질한 유형도 여러 조각으로 쪼개집니다.\n        \">\n---\n\n::: {.callout-note}\n## 🎯 Learning objectives\n\n-   **군집화에 \"정답\"이 없다는 것이 무슨 뜻인지 설명할 수 있다**\n-   외부 지표(JC·FMI·RI·**ARI**)와 내부 지표(DB·Dunn·**silhouette**)를 계산하고 한계를 말할 수 있다\n-   **거리의 선택이 군집 결과를 결정한다**는 것을 예로 보일 수 있다 — 스케일, Minkowski $p$, correlation\n-   k-means의 목적함수와 Lloyd 알고리즘을 설명하고, 초깃값·$k$ 선택의 문제를 다룰 수 있다\n-   k-means가 실패하는 데이터 모양을 알고 GMM·DBSCAN·계층적 군집 중 대안을 고를 수 있다\n-   linkage에 따라 덴드로그램이 어떻게 달라지는지 설명할 수 있다\n-   **kNN 그래프와 Louvain/Leiden의 원리를 말하고, 단일세포 군집화에서 resolution의 의미를 해석할 수 있다**\n:::\n\n> 🤔 **\"이 데이터에는 세포 유형이 몇 개인가?\" — 그 숫자는 데이터가 알려주는 것일까, 우리가 정하는 것일까?**\n\n------------------------------------------------------------------------\n\n## 1. Clustering 학습 문제 🧩\n\n### 1) label 없이 구조를 찾는다\n\n-   학습 샘플에 **label이 없습니다.** 데이터 안에 내재된 특성과 규칙만으로 샘플을 묶습니다\n-   각 군집은 보통 **서로 겹치지 않습니다**(mutually exclusive, hard clustering). 4절의 GMM처럼 **소속 확률**을 주는 soft clustering도 있습니다\n-   그 자체가 목적이기도 하지만(세포 유형 발견, 환자 아형 분류), **다른 분석의 전 단계**로도 쓰입니다(군집별 차등발현, 층화 분석)\n\n### 2) 정답이 없다는 것\n\n지도학습에서는 test set의 정답이 \"잘했는가\"를 판정합니다. 군집화에는 그런 심판이 없습니다.\n\n| 알고리즘 | \"군집\"의 정의 |\n|---|---|\n| **k-means** | 중심점까지의 거리가 가장 가까운 점들 — 구형, 비슷한 크기 |\n| **GMM** | 같은 정규분포에서 나왔을 법한 점들 — 타원형 |\n| **DBSCAN** | 밀도가 이어진 점들 — 모양 무관, 잡음 분리 |\n| **계층적** | 병합 기준(linkage)에 따라 달라지는 트리 |\n| **Louvain/Leiden** | 그래프에서 안쪽 연결이 기대보다 조밀한 점들 |\n\n✅ **같은 데이터에 다른 알고리즘을 쓰면 다른 답이 나오고, 그 어느 것도 \"틀린\" 것이 아닙니다.** W1의 inductive bias가 가장 노골적으로 드러나는 곳입니다. 그래서 **어떤 정의가 내 생물학적 질문에 맞는가**를 먼저 물어야 합니다.\n\n------------------------------------------------------------------------\n\n## 2. 성능 척도 (validity index) 📏\n\n목표는 하나입니다 — **군집 내 유사도는 높게, 군집 간 유사도는 낮게.**\n\n### 1) External index — 정답(reference)이 있을 때\n\n예측 군집 $C$ 와 기준 군집 $C^*$ 가 있을 때, **모든 샘플 쌍 $(\\mathbf{x}_i, \\mathbf{x}_j)$ 을 네 종류로 셉니다.**\n\n| | 기준에서 같은 군집 | 기준에서 다른 군집 |\n|---|---|---|\n| **예측에서 같은 군집** | $a = \\|SS\\|$ (TP) | $b = \\|SD\\|$ (FP) |\n| **예측에서 다른 군집** | $c = \\|DS\\|$ (FN) | $d = \\|DD\\|$ (TN) |\n\n$a + b + c + d = \\binom{m}{2}$ 입니다.\n\n::: {.callout-note}\n## 원자료 표기 정정\n\n원자료에는 DS가 TN으로 적혀 있지만, **DS는 \"정답에서는 같은데 예측이 갈라놓은 쌍\"이므로 FN**입니다. TN은 DD 하나뿐입니다.\n:::\n\n$$\\text{JC} = \\frac{a}{a+b+c}, \\qquad\n\\text{FMI} = \\sqrt{\\frac{a}{a+b}\\cdot\\frac{a}{a+c}}, \\qquad\n\\text{RI} = \\frac{2(a+d)}{m(m-1)}$$\n\n세 지표 모두 0~1이고 클수록 좋습니다. 그리고 **Adjusted Rand Index(ARI)**는 RI에서 **우연히 맞을 기댓값을 빼고** 정규화한 것입니다.\n\n$$\\text{ARI} = \\frac{\\text{RI} - \\mathbb{E}[\\text{RI}]}{\\max(\\text{RI}) - \\mathbb{E}[\\text{RI}]}$$\n\n무작위면 0, 완벽하면 1. 음수도 나올 수 있습니다.\n\n### 2) 🧪 실습: 쌍을 직접 세기\n\n\n::: {.cell}\n\n```{.r .cell-code}\npair_counts <- function(pred, ref) {\n  ct <- table(pred, ref)\n  ss <- sum(choose(ct, 2))                    # 예측도 같고 정답도 같은 쌍\n  sp <- sum(choose(rowSums(ct), 2))           # 예측에서 같은 쌍\n  sr <- sum(choose(colSums(ct), 2))           # 정답에서 같은 쌍\n  c(a = ss, b = sp - ss, c = sr - ss, d = choose(length(pred), 2) - sp - sr + ss)\n}\next_index <- function(pred, ref) {\n  p <- pair_counts(pred, ref); a <- p[[\"a\"]]; b <- p[[\"b\"]]; c <- p[[\"c\"]]; d <- p[[\"d\"]]\n  m <- length(pred); ct <- table(pred, ref)\n  sa <- sum(choose(rowSums(ct), 2)); sb <- sum(choose(colSums(ct), 2))\n  ea <- sa * sb / choose(m, 2); mx <- (sa + sb) / 2          # ARI의 기댓값과 최댓값\n  c(JC = a/(a+b+c), FMI = sqrt(a/(a+b) * a/(a+c)), RI = 2*(a+d)/(m*(m-1)),\n    ARI = (a - ea) / (mx - ea))\n}\nmake_blobs <- function(n_each, centers, sd, seed) {\n  set.seed(seed)\n  X <- do.call(rbind, lapply(seq_len(nrow(centers)), function(k)\n    cbind(rnorm(n_each[k], centers[k,1], sd[k]), rnorm(n_each[k], centers[k,2], sd[k]))))\n  list(X = X, y = rep(seq_len(nrow(centers)), n_each))\n}\nbl <- make_blobs(rep(100, 4), rbind(c(0,0), c(4,0), c(0,4), c(4,4)), rep(1, 4), 12)\n\nset.seed(1)\nkm4 <- kmeans(bl$X, 4, nstart = 20)\npair_counts(km4$cluster, bl$y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    a     b     c     d \n18170  1664  1630 58336 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(ext_index(km4$cluster, bl$y), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    JC    FMI     RI    ARI \n0.8465 0.9169 0.9587 0.8894 \n```\n\n\n:::\n:::\n\n\n-   400개 샘플의 쌍은 $\\binom{400}{2} = 79{,}800$ 개. 대부분이 $d$ (58,336)입니다 — **다른 군집끼리 다르게 묶인 쌍은 원래 많습니다**\n-   이 $d$ 가 RI를 부풀립니다. 다음 실습에서 확인합니다\n\n### 3) 🧪 실습: 무작위 label에 속는 지표\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2)\ndo.call(rbind, lapply(c(2, 4, 10, 50), function(k) {\n  r <- replicate(20, ext_index(sample(k, 400, TRUE), bl$y))   # 완전히 무작위 군집\n  data.frame(k_random = k, JC = round(mean(r[\"JC\",]), 4), FMI = round(mean(r[\"FMI\",]), 4),\n             RI = round(mean(r[\"RI\",]), 4), ARI = round(mean(r[\"ARI\",]), 4))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  k_random     JC    FMI     RI     ARI\n1        2 0.1990 0.3526 0.5000  0.0004\n2        4 0.1429 0.2500 0.6265  0.0014\n3       10 0.0767 0.1573 0.7013 -0.0003\n4       50 0.0189 0.0702 0.7417 -0.0002\n```\n\n\n:::\n:::\n\n\n-   **아무 의미 없는** 무작위 label인데, 군집 수를 늘리면 RI가 0.5000 → **0.7417**까지 오릅니다\n-   군집이 잘게 쪼개질수록 \"다른 군집에 흩어진 쌍\"($d$)이 자동으로 늘어나기 때문입니다\n-   ARI는 어느 경우든 **0 근처**입니다\n-   ✅ **논문에서 군집 일치도를 보고할 때는 ARI(또는 NMI)를 쓰세요.** RI 0.74는 아무것도 증명하지 않습니다\n\n### 4) Internal index — 정답이 없을 때\n\n실제 상황에서는 정답이 없습니다. 군집 자체의 모양만 봅니다.\n\n**Davies–Bouldin (작을수록 좋음)** — $\\sigma_i$ 는 군집 $i$ 의 점들이 중심까지 떨어진 평균 거리\n\n$$\\text{DB} = \\frac{1}{n}\\sum_{i=1}^{n}\\max_{j\\ne i}\\left(\\frac{\\sigma_i + \\sigma_j}{d(c_i, c_j)}\\right)$$\n\n분자는 **군집 내 퍼짐**, 분모는 **군집 간 거리**입니다.\n\n**Dunn (클수록 좋음)**\n\n$$D = \\frac{\\min_{i<j} d(i,j)}{\\max_{k} d'(k)}$$\n\n가장 가까운 두 군집 사이 거리 ÷ 가장 넓은 군집의 지름. ⚠️ 분모가 **최대값 하나**라서 이상치 하나에 크게 흔들립니다.\n\n**Silhouette (클수록 좋음)** `[신규]` — 샘플마다 계산할 수 있어 가장 많이 씁니다\n\n$$s(i) = \\frac{b(i) - a(i)}{\\max\\{a(i), b(i)\\}}$$\n\n$a(i)$ = 자기 군집 안의 평균 거리, $b(i)$ = 가장 가까운 **다른** 군집까지의 평균 거리. $s(i) \\approx 1$ 이면 잘 들어맞고, $\\approx 0$ 이면 경계, **음수면 잘못 배정**된 것입니다.\n\n### 5) 🧪 실습: 세 지표로 $k$ 고르기\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsilhouette_avg <- function(X, cl) {\n  D <- as.matrix(dist(X)); ks <- sort(unique(cl))\n  mean(vapply(seq_len(nrow(X)), function(i) {\n    own <- cl == cl[i]; if (sum(own) == 1) return(0)\n    a <- sum(D[i, own]) / (sum(own) - 1)\n    b <- min(vapply(ks[ks != cl[i]], function(k) mean(D[i, cl == k]), numeric(1)))\n    (b - a) / max(a, b)\n  }, numeric(1)))\n}\ndb_index <- function(X, cl) {\n  ks <- sort(unique(cl))\n  C  <- t(sapply(ks, function(k) colMeans(X[cl == k, , drop = FALSE])))\n  sg <- sapply(seq_along(ks), function(j)\n    mean(sqrt(rowSums(sweep(X[cl == ks[j], , drop = FALSE], 2, C[j, ])^2))))\n  dc <- as.matrix(dist(C))\n  mean(sapply(seq_along(ks), function(i) max((sg[i] + sg[-i]) / dc[i, -i])))\n}\ndunn_index <- function(X, cl) {                 # 원자료 정의: 군집 간 거리는 centroid 기준\n  ks <- sort(unique(cl)); D <- as.matrix(dist(X))\n  C  <- t(sapply(ks, function(k) colMeans(X[cl == k, , drop = FALSE])))\n  min(dist(C)) / max(sapply(ks, function(k) max(D[cl == k, cl == k])))\n}\nset.seed(3)\nint_res <- do.call(rbind, lapply(2:8, function(k) {\n  cl <- kmeans(bl$X, k, nstart = 20)$cluster\n  data.frame(k = k, silhouette = round(silhouette_avg(bl$X, cl), 4),\n             DB = round(db_index(bl$X, cl), 4), Dunn = round(dunn_index(bl$X, cl), 4),\n             ARI_vs_truth = round(ext_index(cl, bl$y)[[\"ARI\"]], 4))\n}))\nint_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  k silhouette     DB   Dunn ARI_vs_truth\n1 2     0.4085 1.0966 0.4327       0.4544\n2 3     0.4391 0.7657 0.5055       0.6259\n3 4     0.5338 0.5859 0.7473       0.8894\n4 5     0.4743 0.7837 0.3499       0.8019\n5 6     0.4146 0.9647 0.3539       0.7009\n6 7     0.4105 0.8603 0.4166       0.6537\n7 8     0.3650 0.9458 0.3827       0.5399\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nil <- rbind(data.frame(k = int_res$k, v = int_res$silhouette, index = \"silhouette (higher)\"),\n            data.frame(k = int_res$k, v = int_res$DB,         index = \"Davies-Bouldin (lower)\"),\n            data.frame(k = int_res$k, v = int_res$Dunn,       index = \"Dunn (higher)\"))\nil$index <- factor(il$index, levels = c(\"silhouette (higher)\", \"Davies-Bouldin (lower)\", \"Dunn (higher)\"))\nggplot(il, aes(k, v)) +\n  geom_vline(xintercept = 4, linetype = 2, colour = \"#d1495b\") +\n  geom_line(colour = \"#2e8b7a\", linewidth = .9) + geom_point(colour = \"#2e8b7a\", size = 1.8) +\n  facet_wrap(~ index, scales = \"free_y\") +\n  labs(x = \"number of clusters k\", y = NULL, caption = \"dashed = true k\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-4-1.png){width=729.6}\n:::\n:::\n\n\n-   세 지표가 모두 **$k = 4$ 를 가리킵니다** (silhouette 0.5338 최대, DB 0.5859 최소, Dunn 0.7473 최대)\n-   정답과의 ARI도 $k = 4$ 에서 0.8894로 최대 — 이 데이터에서는 내부 지표가 정직했습니다\n-   ⚠️ 이건 **구형 blob이라서**입니다. silhouette·DB·Dunn은 모두 **중심·거리 기반**이라 k-means와 같은 편향을 공유합니다. 5절의 반달 모양에서 silhouette이 틀린 답을 더 좋아하는 것을 확인합니다\n\n------------------------------------------------------------------------\n\n## 3. 거리 계산법 📐\n\n**군집화 결과의 절반은 거리를 고르는 순간 정해집니다.**\n\n### 1) 거리 척도의 네 가지 성질\n\n1.  **비음성** $\\;\\text{dist}(\\mathbf{x}_i, \\mathbf{x}_j) \\ge 0$\n2.  **동일성** $\\;\\text{dist}(\\mathbf{x}_i, \\mathbf{x}_j) = 0 \\iff \\mathbf{x}_i = \\mathbf{x}_j$\n3.  **대칭성** $\\;\\text{dist}(\\mathbf{x}_i, \\mathbf{x}_j) = \\text{dist}(\\mathbf{x}_j, \\mathbf{x}_i)$\n4.  **삼각부등식** $\\;\\text{dist}(\\mathbf{x}_i, \\mathbf{x}_j) \\le \\text{dist}(\\mathbf{x}_i, \\mathbf{x}_k) + \\text{dist}(\\mathbf{x}_k, \\mathbf{x}_j)$\n\n### 2) Minkowski 가족\n\n$$\\text{dist}_p(\\mathbf{x}, \\mathbf{y}) = \\left(\\sum_{u=1}^{n} |x_u - y_u|^p\\right)^{1/p}$$\n\n| $p$ | 이름 | 의미 |\n|---|---|---|\n| 1 | **Manhattan (L1)** | 격자를 따라 걷는 거리. 이상치에 덜 민감 |\n| 2 | **Euclidean (L2)** | 직선 거리 |\n| $\\infty$ | **Chebyshev** | 가장 크게 차이 나는 좌표 하나 |\n\n원자료의 \"p = 1 → L1, p = 2 → L2 (뭔가 이상한 거 같은데)\"는 맞게 적은 것입니다 — L$p$ 의 $p$ 가 곧 Minkowski의 $p$ 입니다. 순서가 있는 범주(ordinal)에도 숫자로 바꿔 쓸 수 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmink <- function(x, y, p) if (is.infinite(p)) max(abs(x - y)) else sum(abs(x - y)^p)^(1/p)\nq <- c(0, 0)\nP <- rbind(A = c(3, 0), B = c(2.2, 2.2), C = c(1.5, 2.8))\ntab <- sapply(c(1, 2, 4, Inf), function(p) apply(P, 1, function(r) mink(q, r, p)))\ncolnames(tab) <- c(\"p=1\", \"p=2\", \"p=4\", \"p=Inf\")\nround(tab, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p=1   p=2   p=4 p=Inf\nA 3.0 3.000 3.000   3.0\nB 4.4 3.111 2.616   2.2\nC 4.3 3.176 2.856   2.8\n```\n\n\n:::\n\n```{.r .cell-code}\napply(tab, 2, function(z) rownames(tab)[which.min(z)])    # q 에서 가장 가까운 점\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p=1   p=2   p=4 p=Inf \n  \"A\"   \"A\"   \"B\"   \"B\" \n```\n\n\n:::\n:::\n\n\n-   $p = 1, 2$ 에서는 **A**가, $p = 4, \\infty$ 에서는 **B**가 가장 가깝습니다\n-   A는 한 축으로만 멀고, B는 두 축에 고르게 떨어져 있습니다. $p$ 가 클수록 **\"가장 크게 벗어난 한 축\"**을 중시합니다\n-   ✅ 이웃이 바뀌면 kNN·DBSCAN·계층적 군집의 결과가 전부 바뀝니다\n\n### 3) 🧪 실습: 스케일 — 단위가 거리를 지배한다\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(5)\nXs <- rbind(cbind(age = rnorm(50, 45, 8), crp = rnorm(50, 1.0, .3)),   # 두 집단은 CRP로만 갈린다\n            cbind(age = rnorm(50, 47, 8), crp = rnorm(50, 3.0, .3)))\nys <- rep(1:2, each = 50)\nset.seed(6)\nc(sd_age = round(sd(Xs[,1]), 2), sd_crp = round(sd(Xs[,2]), 2),\n  ARI_raw    = round(ext_index(kmeans(Xs, 2, nstart = 20)$cluster, ys)[[\"ARI\"]], 4),\n  ARI_scaled = round(ext_index(kmeans(scale(Xs), 2, nstart = 20)$cluster, ys)[[\"ARI\"]], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sd_age     sd_crp    ARI_raw ARI_scaled \n    8.6800     1.0500     0.0045     1.0000 \n```\n\n\n:::\n:::\n\n\n-   나이의 표준편차는 8.68, CRP는 1.05. 표준화 없이 거리를 재면 **나이가 거리를 독차지**합니다\n-   진짜 차이는 CRP에 있는데 k-means는 나이로 반을 갈라 **ARI 0.0045**. 표준화하면 **1**\n-   ⚠️ 발현 데이터에서는 **발현량이 높은 유전자가 거리를 지배**합니다. 그래서 log 변환 + 유전자별 표준화(또는 PCA)를 먼저 합니다 (W2)\n\n### 4) 범주형: VDM, 혼합형, 가중\n\n순서 없는 범주(조직, 혈액형)에는 숫자 차이를 쓸 수 없습니다. **VDM(Value Difference Metric)**은 \"두 값이 군집들에 **비슷하게 분포**하면 가깝다\"고 정의합니다.\n\n$$\\text{VDM}_p(a, b) = \\sum_{i=1}^{k}\\left|\\frac{m_{u,a,i}}{m_{u,a}} - \\frac{m_{u,b,i}}{m_{u,b}}\\right|^p$$\n\n$m_{u,a}$ = feature $u$ 가 $a$ 인 샘플 수, $m_{u,a,i}$ = 그중 군집 $i$ 에 속한 수.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvdm <- function(x, cl, a, b, p = 2) {\n  ma <- sum(x == a); mb <- sum(x == b)\n  sum(sapply(unique(cl), function(i) abs(sum(x == a & cl == i)/ma - sum(x == b & cl == i)/mb)^p))\n}\ntissue <- rep(c(\"liver\", \"kidney\", \"brain\", \"spinal\"), each = 30)\nclv    <- c(rep(1,25), rep(2,5),  rep(1,20), rep(2,10),     # liver, kidney\n            rep(3,27), rep(2,3),  rep(3,24), rep(2,6))      # brain, spinal\nlv <- c(\"liver\", \"kidney\", \"brain\", \"spinal\")\nM <- outer(lv, lv, Vectorize(function(a, b) vdm(tissue, clv, a, b)))\ndimnames(M) <- list(lv, lv)\nround(M, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        liver kidney  brain spinal\nliver  0.0000 0.0556 1.5089 1.3356\nkidney 0.0556 0.0000 1.3089 1.1022\nbrain  1.5089 1.3089 0.0000 0.0200\nspinal 1.3356 1.1022 0.0200 0.0000\n```\n\n\n:::\n:::\n\n\n-   liver–kidney는 **0.0556**, brain–spinal은 **0.0200**으로 가깝고, 그 사이는 1.1~1.5로 멉니다\n-   이름만 봐서는 알 수 없는 \"비슷함\"을 **군집 분포에서 학습**한 셈입니다\n\n연속형과 범주형이 섞이면 둘을 더합니다(**MinkovDM**). feature마다 중요도가 다르면 가중치를 곱합니다.\n\n$$\\text{MinkovDM}_p(\\mathbf{x}_i, \\mathbf{x}_j) = \\left(\\sum_{u=1}^{n_c}|x_{iu}-x_{ju}|^p + \\sum_{u=n_c+1}^{n}\\text{VDM}_p(x_{iu}, x_{ju})\\right)^{1/p}, \\qquad\n\\text{dist}_{\\text{wmk}} = \\left(\\sum_u w_u |x_{iu} - x_{ju}|^p\\right)^{1/p}$$\n\n### 5) 🧪 실습: correlation distance — 크기가 아니라 모양 `[신규]`\n\n발현 데이터에서 실제로 가장 많이 쓰는 거리입니다. **시간에 따른 발현 패턴**이 같은 유전자를 묶고 싶을 때, 발현량의 절대 크기는 방해가 됩니다.\n\n$$d_{\\text{cor}}(\\mathbf{x}, \\mathbf{y}) = 1 - r(\\mathbf{x}, \\mathbf{y}), \\qquad d_{\\text{cos}}(\\mathbf{x}, \\mathbf{y}) = 1 - \\frac{\\mathbf{x}^{\\mathsf{T}}\\mathbf{y}}{\\|\\mathbf{x}\\|\\|\\mathbf{y}\\|}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\ntp <- 1:8\nshapeA <- sin(tp/8*2*pi); shapeB <- -sin(tp/8*2*pi)\nmkg <- function(shape, level, n) t(replicate(n, level + shape + rnorm(8, 0, .25)))\nG <- rbind(mkg(shapeA, 2, 10), mkg(shapeA, 8, 10), mkg(shapeB, 2, 10), mkg(shapeB, 8, 10))\npat <- rep(c(\"up-down\", \"up-down\", \"down-up\", \"down-up\"), each = 10)\nlvl <- rep(c(\"low\", \"high\", \"low\", \"high\"), each = 10)\n\nce <- cutree(hclust(dist(G), \"average\"), 2)                     # Euclidean\ncc <- cutree(hclust(as.dist(1 - cor(t(G))), \"average\"), 2)      # 1 - Pearson r\ndata.frame(distance = c(\"Euclidean\", \"1 - correlation\"),\n           ARI_vs_pattern = round(c(ext_index(ce, pat)[[\"ARI\"]], ext_index(cc, pat)[[\"ARI\"]]), 4),\n           ARI_vs_level   = round(c(ext_index(ce, lvl)[[\"ARI\"]], ext_index(cc, lvl)[[\"ARI\"]]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         distance ARI_vs_pattern ARI_vs_level\n1       Euclidean        -0.0263       1.0000\n2 1 - correlation         1.0000      -0.0263\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngl <- do.call(rbind, lapply(seq_len(nrow(G)), function(i) rbind(\n  data.frame(gene = i, t = tp, expr = G[i, ], pattern = pat[i],\n             distance = \"Euclidean\", cluster = paste(\"cluster\", ce[i])),\n  data.frame(gene = i, t = tp, expr = G[i, ], pattern = pat[i],\n             distance = \"1 - correlation\", cluster = paste(\"cluster\", cc[i])))))\ngl$distance <- factor(gl$distance, levels = c(\"Euclidean\", \"1 - correlation\"))\nggplot(gl, aes(t, expr, group = gene, colour = pattern)) +\n  geom_line(alpha = .7, linewidth = .5) +\n  facet_grid(distance ~ cluster) +\n  scale_colour_manual(values = c(\"up-down\" = \"#d1495b\", \"down-up\" = \"#2e8b7a\")) +\n  labs(x = \"time point\", y = \"log expression\", colour = \"true pattern\") +\n  theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-9-1.png){width=710.4}\n:::\n:::\n\n\n-   Euclidean은 **발현량(low / high)**으로 나눕니다 — 두 패턴이 한 군집에 섞였습니다 (패턴 기준 ARI -0.0263)\n-   1 − correlation은 **패턴**으로 나눕니다 — 발현량은 섞였지만 패턴은 완벽히 분리 (ARI **1**)\n-   ✅ **\"무엇이 비슷한가\"는 질문이 정합니다.** 공동조절 유전자 모듈(WGCNA 등)을 찾는다면 correlation, 발현 수준 그룹을 찾는다면 Euclidean\n\n### 6) 🧪 실습: 삼각부등식을 어기는 거리\n\n원자료의 인간–켄타우로스–말 그림처럼, **유사도에서 온 거리는 척도의 성질을 다 만족하지 않을 수 있습니다**(non-metric distance).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nang <- c(0, 60, 120) * pi/180                 # x, y, z 가 60도씩 벌어진 세 벡터\nV <- cbind(cos(ang), sin(ang))\ncosd <- function(u, v) 1 - sum(u*v) / sqrt(sum(u^2) * sum(v^2))\nc(d_xy = cosd(V[1,], V[2,]), d_yz = cosd(V[2,], V[3,]),\n  d_xy_plus_d_yz = cosd(V[1,], V[2,]) + cosd(V[2,], V[3,]), d_xz = cosd(V[1,], V[3,]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          d_xy           d_yz d_xy_plus_d_yz           d_xz \n           0.5            0.5            1.0            1.5 \n```\n\n\n:::\n:::\n\n\n-   $d(x,y) + d(y,z) = 1.0 < d(x,z) = 1.5$ — **삼각부등식 위반**\n-   x와 y는 비슷하고, y와 z도 비슷한데, x와 z는 \"아주 다르다\" — 켄타우로스 문제 그대로입니다\n-   ⚠️ **cosine 거리와 $1 - r$ 은 엄밀한 거리 척도가 아닙니다.** $\\sqrt{2(1-r)}$ (표준화 벡터의 Euclidean)이나 각도 $\\arccos r$ 로 바꾸면 척도가 됩니다. 삼각부등식을 이용해 탐색을 가속하는 알고리즘(ball tree 등)에 넣을 때 주의\n\n### 7) Distance metric learning\n\n거리를 미리 정하지 않고 **데이터로 학습**하는 방법입니다 — 같은 군집이어야 할 쌍은 가깝게, 다른 쌍은 멀게 되는 가중치(또는 선형변환)를 찾습니다. Mahalanobis 거리가 가장 단순한 예이고, W13에서 차원축소와 함께 다시 다룹니다.\n\n------------------------------------------------------------------------\n\n## 4. Prototype-based clustering 🎯\n\n**가정** — 군집 구조를 대표점(prototype) 몇 개로 나타낼 수 있다. 대표점을 초기화하고 → 반복 갱신하다가 → 수렴하면 끝.\n\n### 1) k-means\n\n$$\\arg\\min_{r, \\mathbf{c}} \\sum_{n=1}^{N}\\sum_{k=1}^{K} r_{nk}\\,\\|\\mathbf{x}_n - \\mathbf{c}_k\\|^2$$\n\n$r_{nk}$ = 샘플 $n$ 이 군집 $k$ 에 속하면 1, 아니면 0. $\\mathbf{c}_k$ = centroid.\n\n**Lloyd 알고리즘**\n\n1.  **Initialization** — $\\mathbf{c}_k$ 초기화 (무작위 / Forgy / MacQueen)\n2.  **Assignment** — 각 샘플을 가장 가까운 centroid에 배정 ($\\mathbf{c}$ 고정, $r$ 최적화)\n3.  **Update** — 배정된 샘플의 평균으로 centroid 갱신 ($r$ 고정, $\\mathbf{c}$ 최적화)\n4.  목적함수가 더 줄지 않으면 중지\n\n두 단계가 각각 목적함수를 줄이므로 **반드시 수렴**하지만, **국소 최적**입니다. 전역 최적해를 찾는 것은 NP-hard입니다.\n\n### 2) 🧪 실습: Lloyd를 직접 구현하면 `kmeans()`와 같은가\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlloyd <- function(X, centers, max_iter = 100) {\n  C <- centers; hist <- numeric(0)\n  for (it in 1:max_iter) {\n    D  <- sapply(seq_len(nrow(C)), function(k) rowSums(sweep(X, 2, C[k, ])^2))  # n x K\n    cl <- max.col(-D)                                                            # assignment\n    hist <- c(hist, sum(D[cbind(seq_len(nrow(X)), cl)]))\n    Cn <- t(sapply(seq_len(nrow(C)), function(k)                                 # update\n      if (any(cl == k)) colMeans(X[cl == k, , drop = FALSE]) else C[k, ]))\n    if (max(abs(Cn - C)) < 1e-10) break\n    C <- Cn\n  }\n  list(cluster = cl, centers = C, sse = tail(hist, 1), hist = hist, iter = it)\n}\nset.seed(21)\ninit <- bl$X[sample(nrow(bl$X), 4), ]\nfit  <- lloyd(bl$X, init)\nref  <- kmeans(bl$X, init, algorithm = \"Lloyd\", iter.max = 100)\nround(fit$hist, 2)                     # 반복마다의 SSE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 2439.08 1370.37 1347.81 1316.76 1228.40  957.48  705.92  671.12  669.79\n[10]  669.48\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(iterations = fit$iter, SSE_mine = round(fit$sse, 4),\n           SSE_stats_kmeans = round(ref$tot.withinss, 4),\n           ARI_between_them = ext_index(fit$cluster, ref$cluster)[[\"ARI\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  iterations SSE_mine SSE_stats_kmeans ARI_between_them\n1         10 669.4789         669.4789                1\n```\n\n\n:::\n:::\n\n\n-   10번 반복에 수렴, 목적함수가 2439.08 → 669.48로 **한 번도 늘지 않습니다**\n-   `stats::kmeans()`와 SSE·군집이 **완전히 일치**합니다\n\n### 3) 🧪 실습: 초깃값 민감성과 k-means++ `[신규]`\n\n**k-means++** — 첫 centroid는 무작위, 이후는 **기존 centroid에서 먼 점일수록 높은 확률**($\\propto D(x)^2$)로 뽑습니다. 초기 centroid들이 흩어지게 만드는 것입니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncen8 <- rbind(c(0,0), c(5,0), c(10,0), c(0,5), c(5,5), c(10,5), c(0,10), c(10,10))\nbl8  <- make_blobs(rep(60, 8), cen8, rep(0.9, 8), 13)        # 군집 8개 -> 국소해가 많다\nkpp_init <- function(X, K) {\n  C <- X[sample(nrow(X), 1), , drop = FALSE]\n  while (nrow(C) < K) {\n    d2 <- apply(sapply(seq_len(nrow(C)), function(k) rowSums(sweep(X, 2, C[k, ])^2)), 1, min)\n    C  <- rbind(C, X[sample(nrow(X), 1, prob = d2), ])\n  }\n  C\n}\nset.seed(22)\nsse_rand <- replicate(200, lloyd(bl8$X, bl8$X[sample(nrow(bl8$X), 8), ])$sse)\nsse_kpp  <- replicate(200, lloyd(bl8$X, kpp_init(bl8$X, 8))$sse)\nbest <- min(c(sse_rand, sse_kpp))\ndata.frame(init = c(\"random (Forgy)\", \"k-means++\"),\n  best_SSE   = round(c(min(sse_rand), min(sse_kpp)), 1),\n  median_SSE = round(c(median(sse_rand), median(sse_kpp)), 1),\n  worst_SSE  = round(c(max(sse_rand), max(sse_kpp)), 1),\n  hit_global = c(mean(sse_rand < best + 1e-6), mean(sse_kpp < best + 1e-6)),\n  within_1pct_of_best = c(mean(sse_rand < best * 1.01), mean(sse_kpp < best * 1.01)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            init best_SSE median_SSE worst_SSE hit_global within_1pct_of_best\n1 random (Forgy)      760     1330.2    4494.4      0.255               0.455\n2      k-means++      760      760.3    2049.3      0.360               0.640\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd8 <- rbind(data.frame(sse = sse_rand, init = \"random (Forgy)\"),\n             data.frame(sse = sse_kpp,  init = \"k-means++\"))\nsd8$init <- factor(sd8$init, levels = c(\"random (Forgy)\", \"k-means++\"))\nggplot(sd8, aes(sse, fill = init)) +\n  geom_histogram(bins = 40, colour = \"white\", linewidth = .2) +\n  geom_vline(xintercept = best, linetype = 2, colour = \"grey30\") +\n  facet_wrap(~ init, ncol = 1) +\n  scale_fill_manual(values = c(\"random (Forgy)\" = \"#7d8597\", \"k-means++\" = \"#2e8b7a\"), guide = \"none\") +\n  scale_x_log10() +\n  labs(x = \"final SSE (log scale)\", y = \"runs out of 200\", caption = \"dashed = best SSE found\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n-   무작위 초기화는 200번 중 **25.5%**만 전역해(SSE 760)에 정확히 도달하고, 중앙값 1330.2, 최악 4494.4\n-   k-means++는 **36.0%** 도달, 중앙값 **760.3**, 최악 2049.3\n-   전역해와 SSE가 1% 이내인 \"사실상 같은 해\"까지 세면 **45.5% vs 64.0%**. 나머지는 히스토그램 가운데 덩어리의 **나쁜 국소해**입니다\n-   ⚠️ k-means++도 **한 번으로는 부족**합니다. `kmeans(..., nstart = 20)` 처럼 여러 번 돌려 SSE가 가장 낮은 것을 고르세요 (R의 기본 `nstart = 1`은 위험)\n\n### 4) 🧪 실습: $k$ 는 몇 개인가 — elbow, silhouette, gap `[신규]`\n\n-   **Elbow** — $k$ 에 따른 SSE가 급격히 꺾이는 곳. 주관적\n-   **Silhouette** — 평균 silhouette이 최대인 $k$\n-   **Gap statistic** — 실제 $\\log W_k$ 를 \"군집이 없는 균일분포 참조 데이터\"의 $\\log W_k$ 기댓값과 비교. $\\text{Gap}(k) \\ge \\text{Gap}(k+1) - s_{k+1}$ 을 만족하는 **가장 작은 $k$** (1-SE 규칙)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(23)\nKs  <- 1:8\nWSS <- sapply(Ks, function(k) kmeans(bl$X, k, nstart = 20)$tot.withinss)\nsil <- c(NA, sapply(2:8, function(k) silhouette_avg(bl$X, kmeans(bl$X, k, nstart = 20)$cluster)))\n\ngap_stat <- function(X, Ks, B = 20) {\n  lo <- apply(X, 2, min); hi <- apply(X, 2, max)\n  logW  <- sapply(Ks, function(k) log(kmeans(X, k, nstart = 10)$tot.withinss))\n  logWb <- sapply(seq_len(B), function(b) {                 # 군집이 없는 참조 데이터 B개\n    Xb <- sapply(seq_len(ncol(X)), function(j) runif(nrow(X), lo[j], hi[j]))\n    sapply(Ks, function(k) log(kmeans(Xb, k, nstart = 10)$tot.withinss))\n  })\n  data.frame(k = Ks, gap = rowMeans(logWb) - logW, se = apply(logWb, 1, sd) * sqrt(1 + 1/B))\n}\nset.seed(24)\ngp <- gap_stat(bl$X, Ks, B = 20)\nk_1se <- min(which(gp$gap[-length(Ks)] >= gp$gap[-1] - gp$se[-1]))\n\ndata.frame(k = Ks, WSS = round(WSS, 1),\n           silhouette = ifelse(is.na(sil), \"-\", format(round(sil, 4))),\n           gap = round(gp$gap, 4), gap_se = round(gp$se, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  k    WSS silhouette    gap gap_se\n1 1 3840.8          - 0.2565 0.0379\n2 2 2235.3     0.4085 0.2867 0.0244\n3 3 1383.4     0.4391 0.3049 0.0366\n4 4  669.4     0.5338 0.6112 0.0317\n5 5  587.4     0.4743 0.5451 0.0325\n6 6  518.0     0.4132 0.4572 0.0317\n7 7  463.9     0.4070 0.4197 0.0358\n8 8  412.0     0.3274 0.3808 0.0325\n```\n\n\n:::\n\n```{.r .cell-code}\nc(k_by_silhouette = which.max(sil), k_by_gap_max = which.max(gp$gap), k_by_gap_1SE_rule = k_1se)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  k_by_silhouette      k_by_gap_max k_by_gap_1SE_rule \n                4                 4                 2 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkl <- rbind(data.frame(k = Ks, v = WSS, lo = NA, hi = NA, what = \"elbow: WSS\"),\n            data.frame(k = Ks[-1], v = sil[-1], lo = NA, hi = NA, what = \"silhouette\"),\n            data.frame(k = Ks, v = gp$gap, lo = gp$gap - gp$se, hi = gp$gap + gp$se, what = \"gap statistic\"))\nkl$what <- factor(kl$what, levels = c(\"elbow: WSS\", \"silhouette\", \"gap statistic\"))\nggplot(kl, aes(k, v)) +\n  geom_vline(xintercept = 4, linetype = 2, colour = \"#d1495b\") +\n  geom_errorbar(aes(ymin = lo, ymax = hi), width = .2, colour = \"#7d8597\", na.rm = TRUE) +\n  geom_line(colour = \"#2e8b7a\", linewidth = .9) + geom_point(colour = \"#2e8b7a\", size = 1.8) +\n  facet_wrap(~ what, scales = \"free_y\") + scale_x_continuous(breaks = Ks) +\n  labs(x = \"k\", y = NULL, caption = \"dashed = true k\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-15-1.png){width=729.6}\n:::\n:::\n\n\n-   WSS는 $k = 4$ 에서 뚜렷하게 꺾이고(1383.4 → 669.4 → 587.4), silhouette과 gap의 **최댓값**도 $k = 4$\n-   ⚠️ 그런데 **gap의 1-SE 규칙은 $k = 2$ 를 고릅니다.** gap이 $k = 1$~3에서 거의 평평하다가 4에서 뛰어오르기 때문입니다\n-   4개 blob이 2×2 격자로 놓여 있으니 \"왼쪽/오른쪽 두 덩어리\"도 **거친 해상도에서는 틀린 답이 아닙니다.** 1-SE 규칙은 원래 보수적(작은 $k$ 선호)으로 설계되었습니다\n-   ✅ **규칙마다 다른 질문에 답합니다.** 하나의 규칙이 준 숫자를 \"진짜 군집 수\"로 보고하지 말고, 여러 기준과 **생물학적 해석 가능성**을 함께 보세요\n\n### 5) k-means가 가정하는 것\n\nk-means의 목적함수는 **모든 방향으로 같은 반지름**의 군집을 선호합니다.\n\n| 데이터 모양 | k-means | 대안 |\n|---|---|---|\n| 길쭉하거나 기울어진 타원 | 가로로 잘못 자름 | **GMM** (full covariance) |\n| 반달·고리 같은 비볼록 | 불가능 | **DBSCAN**, spectral, 그래프 기반 |\n| 크기가 크게 다른 군집 | 큰 군집을 쪼갬 | GMM, 그래프 기반 |\n| 잡음·이상치 | 모두 어딘가에 배정 | **DBSCAN** (noise로 분리) |\n\n### 6) 🧪 실습: Gaussian mixture model (EM) `[신규]`\n\nGMM은 각 군집을 **평균 $\\boldsymbol{\\mu}_k$ 와 공분산 $\\Sigma_k$ 를 가진 정규분포**로 보고, **어느 군집에서 왔는가**를 숨은 변수로 둡니다. W11 7절의 EM이 그대로 쓰입니다.\n\n-   **E-step** — 책임도 $\\gamma_{nk} = \\dfrac{\\pi_k\\,\\mathcal{N}(\\mathbf{x}_n\\mid\\boldsymbol{\\mu}_k,\\Sigma_k)}{\\sum_j \\pi_j\\,\\mathcal{N}(\\mathbf{x}_n\\mid\\boldsymbol{\\mu}_j,\\Sigma_j)}$\n-   **M-step** — 책임도를 가중치로 $\\pi_k, \\boldsymbol{\\mu}_k, \\Sigma_k$ 갱신\n\n✅ **k-means는 GMM의 특수한 경우**입니다 — 모든 $\\Sigma_k = \\sigma^2 I$ 이고 $\\sigma \\to 0$ 이면 책임도가 0/1이 되어 Lloyd 알고리즘과 같아집니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(25)\nrot <- function(th) matrix(c(cos(th), sin(th), -sin(th), cos(th)), 2)\nmkA <- function(n, mu, sds, th)\n  t(rot(th) %*% t(cbind(rnorm(n, 0, sds[1]), rnorm(n, 0, sds[2])))) + matrix(mu, n, 2, byrow = TRUE)\nXA <- rbind(mkA(150, c(0, 0),    c(3, .45), pi/5),     # 길쭉하고 기울어진 두 군집\n            mkA(150, c(0, 3.2),  c(3, .45), pi/5),\n            mkA(150, c(5, -2.5), c(.8, .8), 0))         # 둥근 군집 하나\nyA <- rep(1:3, each = 150)\n\ndmvn2 <- function(X, mu, S) {                           # 2차원 정규분포 밀도\n  Xc <- sweep(X, 2, mu)\n  exp(-0.5 * rowSums((Xc %*% solve(S)) * Xc)) / (2*pi*sqrt(det(S)))\n}\ngmm_em <- function(X, K, init_cl, iter = 200, tol = 1e-8) {\n  n <- nrow(X); R <- diag(K)[init_cl, ]; ll_old <- -Inf; hist <- numeric(0)\n  for (it in 1:iter) {\n    Nk <- colSums(R); pk <- Nk / n                                          # ---- M-step\n    mu <- lapply(1:K, function(k) colSums(R[, k] * X) / Nk[k])\n    S  <- lapply(1:K, function(k) { Xc <- sweep(X, 2, mu[[k]])\n            crossprod(Xc * sqrt(R[, k])) / Nk[k] + diag(1e-6, 2) })\n    dens <- sapply(1:K, function(k) pk[k] * dmvn2(X, mu[[k]], S[[k]]))     # ---- E-step\n    ll <- sum(log(rowSums(dens))); hist <- c(hist, ll)\n    R  <- dens / rowSums(dens)\n    if (abs(ll - ll_old) < tol) break\n    ll_old <- ll\n  }\n  list(cluster = max.col(R), R = R, ll = hist, iter = it)\n}\nset.seed(26)\nkmA <- kmeans(XA, 3, nstart = 20)\ngm  <- gmm_em(XA, 3, init_cl = kmA$cluster)             # k-means 결과에서 출발\ndata.frame(EM_iterations = gm$iter, loglik_first = round(gm$ll[1], 2),\n           loglik_last = round(tail(gm$ll, 1), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  EM_iterations loglik_first loglik_last\n1            45     -1902.21    -1775.94\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(method = c(\"k-means\", \"GMM (EM, full covariance)\"),\n           ARI = round(c(ext_index(kmA$cluster, yA)[[\"ARI\"]], ext_index(gm$cluster, yA)[[\"ARI\"]]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     method    ARI\n1                   k-means 0.5953\n2 GMM (EM, full covariance) 0.9933\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nga <- rbind(data.frame(x1 = XA[,1], x2 = XA[,2], cl = factor(kmA$cluster), method = \"k-means\"),\n            data.frame(x1 = XA[,1], x2 = XA[,2], cl = factor(gm$cluster),  method = \"GMM (EM)\"))\nga$method <- factor(ga$method, levels = c(\"k-means\", \"GMM (EM)\"))\nggplot(ga, aes(x1, x2, colour = cl)) +\n  geom_point(size = .9, alpha = .8) + coord_equal() + facet_wrap(~ method) +\n  scale_colour_manual(values = c(\"1\" = \"#d1495b\", \"2\" = \"#2e8b7a\", \"3\" = \"#7d8597\"), guide = \"none\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-17-1.png){width=729.6}\n:::\n:::\n\n\n-   k-means는 길쭉한 두 군집을 **가로로 잘라** ARI 0.5953. GMM은 **0.9933**\n-   GMM은 **k-means 결과에서 출발**해 45번 만에 수렴했습니다. 실무에서도 이렇게 초기화합니다\n-   GMM은 각 점의 **소속 확률**도 줍니다 — 경계의 애매한 세포를 \"모른다\"고 표시할 수 있습니다\n-   ⚠️ 차원이 높으면 full covariance의 모수가 $d^2$ 로 늘어 불안정합니다. 대각 공분산이나 PCA 후 적용\n\n### 7) LVQ (Learning Vector Quantization)\n\nprototype 기반이지만 **label을 쓰는** 방법입니다. 가장 가까운 prototype이 같은 class면 가까이, 다르면 멀리 밀어냅니다. 엄밀히는 지도학습이며, prototype이 \"각 class의 대표 샘플\"로 해석된다는 장점이 있습니다.\n\n------------------------------------------------------------------------\n\n## 5. Density-based clustering 🌫️ `[보강 — 원자료에 제목만 있음]`\n\n### 1) DBSCAN\n\n**\"밀도가 이어진 점들을 한 군집으로\"**. 필요한 것은 두 개의 모수뿐입니다.\n\n-   **$\\varepsilon$-neighborhood** — 점 $\\mathbf{x}$ 에서 거리 $\\varepsilon$ 안의 점들\n-   **Core point** — $\\varepsilon$-이웃이 **MinPts** 개 이상인 점\n-   **Border point** — core는 아니지만 어떤 core의 이웃인 점\n-   **Noise** — 둘 다 아닌 점. **어느 군집에도 배정하지 않습니다**\n\ncore에서 core로 **밀도-도달 가능(density-reachable)**하게 이어진 점들이 하나의 군집입니다.\n\n✅ 군집 수를 미리 정하지 않아도 되고, **모양이 자유롭고**, **이상치를 스스로 걸러냅니다.**\n\n### 2) 🧪 실습: DBSCAN 직접 구현 — 반달 두 개\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbscan_ <- function(X, eps, minpts) {\n  D  <- as.matrix(dist(X)); n <- nrow(X)\n  nb <- lapply(seq_len(n), function(i) which(D[i, ] <= eps))    # 자기 자신 포함\n  core <- lengths(nb) >= minpts\n  cl <- rep(0L, n); k <- 0L\n  for (i in which(core)) {\n    if (cl[i] != 0L) next\n    k <- k + 1L; cl[i] <- k; queue <- nb[[i]]                   # 새 군집을 core에서 시작\n    while (length(queue)) {                                    # 밀도-도달 가능한 점을 확장\n      j <- queue[1]; queue <- queue[-1]\n      if (cl[j] == 0L) { cl[j] <- k; if (core[j]) queue <- c(queue, nb[[j]][cl[nb[[j]]] == 0L]) }\n    }\n  }\n  list(cluster = cl, type = ifelse(core, \"core\", ifelse(cl > 0, \"border\", \"noise\")))\n}\nmake_moons <- function(n, noise, seed) {\n  set.seed(seed)\n  t1 <- runif(n, 0, pi); t2 <- runif(n, 0, pi)\n  X <- rbind(cbind(cos(t1), sin(t1)), cbind(1 - cos(t2), 0.5 - sin(t2)))\n  X + matrix(rnorm(4*n, 0, noise), ncol = 2)\n}\nXm <- make_moons(200, 0.08, 31)                                     # 내부에서 set.seed(31)\nXm <- rbind(Xm, cbind(runif(20, -1.2, 2.2), runif(20, -0.8, 1.3)))   # 배경 잡음 20개\nym <- c(rep(1, 200), rep(2, 200), rep(0, 20))                        # 0 = 진짜 잡음\nsig <- ym > 0\n\nset.seed(32)\nkmm <- kmeans(Xm, 2, nstart = 20)$cluster\ndb  <- dbscan_(Xm, eps = 0.15, minpts = 5)\ntable(db$type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nborder   core  noise \n    21    385     14 \n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(method = c(\"k-means (k=2)\", \"DBSCAN (eps=0.15, MinPts=5)\"),\n           ARI_on_signal = round(c(ext_index(kmm[sig], ym[sig])[[\"ARI\"]],\n                                   ext_index(db$cluster[sig], ym[sig])[[\"ARI\"]]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       method ARI_on_signal\n1               k-means (k=2)        0.2791\n2 DBSCAN (eps=0.15, MinPts=5)        0.9657\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(dbscan = db$cluster, truth = ym)          # 0 = noise\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      truth\ndbscan   0   1   2\n     0   7   6   1\n     1  11 194   0\n     2   2   0 199\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2절의 silhouette 은 어느 분할을 더 좋다고 할까 (진짜 잡음은 제외)\nc(silhouette_kmeans_split = round(silhouette_avg(Xm[sig, ], kmm[sig]), 4),\n  silhouette_true_moons   = round(silhouette_avg(Xm[sig, ], ym[sig]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsilhouette_kmeans_split   silhouette_true_moons \n                 0.5147                  0.3470 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlab <- function(v) factor(ifelse(v == 0, \"noise\", paste(\"cluster\", v)),\n                          levels = c(\"cluster 1\", \"cluster 2\", \"noise\"))\nmm <- rbind(data.frame(x1 = Xm[,1], x2 = Xm[,2], cl = lab(kmm),        method = \"k-means (k=2)\"),\n            data.frame(x1 = Xm[,1], x2 = Xm[,2], cl = lab(db$cluster), method = \"DBSCAN\"))\nmm$method <- factor(mm$method, levels = c(\"k-means (k=2)\", \"DBSCAN\"))\nggplot(mm, aes(x1, x2, colour = cl, shape = cl)) +\n  geom_point(size = 1.1) + coord_equal() + facet_wrap(~ method) +\n  scale_colour_manual(values = c(\"cluster 1\" = \"#d1495b\", \"cluster 2\" = \"#2e8b7a\", \"noise\" = \"#7d8597\")) +\n  scale_shape_manual(values = c(\"cluster 1\" = 16, \"cluster 2\" = 16, \"noise\" = 4)) +\n  labs(colour = NULL, shape = NULL) + theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-20-1.png){width=729.6}\n:::\n:::\n\n\n-   k-means는 반달을 **직선으로 잘라** ARI 0.2791. DBSCAN은 **0.9657**\n-   진짜 잡음 20개 중 **7개를 noise로** 걸렀고, 13개(11 + 2)는 반달 가까이에 떨어져 군집에 흡수되었습니다\n-   신호 400개 중 noise로 잘못 버린 것은 7개(6 + 1)\n-   ⚠️ **silhouette은 틀린 k-means 분할(0.5147)을 진짜 반달(0.347)보다 좋다고 평가합니다.** 2절에서 말한 대로, 중심·거리 기반 내부 지표는 k-means와 같은 편향을 공유합니다\n\n### 3) 🧪 실습: $\\varepsilon$ 은 어떻게 고르나\n\n**k-distance plot** — 각 점에서 MinPts−1 번째 이웃까지의 거리를 정렬해 그리면, 꺾이는 지점이 적당한 $\\varepsilon$ 후보입니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkd <- apply(as.matrix(dist(Xm)), 1, function(r) sort(r)[5])   # 4번째 이웃 (자기 자신 제외)\nround(quantile(kd, c(.5, .8, .9, .95, .99)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  50%   80%   90%   95%   99% \n0.075 0.106 0.134 0.165 0.283 \n```\n\n\n:::\n\n```{.r .cell-code}\ndo.call(rbind, lapply(c(0.05, 0.1, 0.15, 0.2, 0.3, 0.5), function(e) {\n  r <- dbscan_(Xm, e, 5)\n  data.frame(eps = e, n_clusters = max(r$cluster), n_noise = sum(r$cluster == 0),\n             ARI_signal = round(ext_index(r$cluster[sig], ym[sig])[[\"ARI\"]], 4))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   eps n_clusters n_noise ARI_signal\n1 0.05         19     295     0.0106\n2 0.10          7      42     0.4041\n3 0.15          2      14     0.9657\n4 0.20          1       5     0.0000\n5 0.30          1       2     0.0000\n6 0.50          1       0     0.0000\n```\n\n\n:::\n:::\n\n\n-   k-distance의 95% 분위수가 0.165 — 꺾이는 지점 근처에서 고른 0.15가 맞았습니다\n-   ⚠️ 그런데 **창이 매우 좁습니다.** 0.10이면 7개로 조각나고, 0.20이면 두 반달이 **하나로 붙습니다**\n-   $\\varepsilon$ 을 0.05 바꿨을 뿐인데 ARI가 0.4041 → 0.9657 → 0\n\n### 4) 🧪 실습: 밀도가 다르면 $\\varepsilon$ 하나로는 안 된다\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(33)\nXv <- rbind(cbind(rnorm(200, 0, .25), rnorm(200, 0, .25)),     # 조밀한 군집\n            cbind(rnorm(200, 3.2, 1.0), rnorm(200, 0, 1.0)))   # 성긴 군집\nyv <- rep(1:2, each = 200)\ndo.call(rbind, lapply(c(0.1, 0.2, 0.3, 0.5, 0.8), function(e) {\n  r <- dbscan_(Xv, e, 5)\n  data.frame(eps = e, n_clusters = max(r$cluster),\n             noise_in_dense = sum(r$cluster[yv == 1] == 0),\n             noise_in_sparse = sum(r$cluster[yv == 2] == 0),\n             ARI = round(ext_index(r$cluster, yv)[[\"ARI\"]], 4))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  eps n_clusters noise_in_dense noise_in_sparse    ARI\n1 0.1          2             37             200 0.6475\n2 0.2          8              3             123 0.6838\n3 0.3          2              2              65 0.7668\n4 0.5          1              0              19 0.0086\n5 0.8          1              0               3 0.0002\n```\n\n\n:::\n:::\n\n\n-   $\\varepsilon$ 이 작으면 성긴 군집이 **통째로 noise**(0.1에서 200개 전부), 크면 두 군집이 **붙습니다**(0.5 이상에서 1개)\n-   최선인 0.3에서도 성긴 군집의 65개를 버리고 ARI 0.7668\n-   ✅ 이것이 **HDBSCAN**이 나온 이유입니다\n\n### 5) HDBSCAN `[신규]`\n\n-   $\\varepsilon$ 을 **하나로 고정하지 않고 모든 $\\varepsilon$ 에 대해** DBSCAN을 돌린 결과를 트리(밀도 계층)로 쌓습니다\n-   트리에서 **오래 살아남는(안정적인) 군집**만 골라냅니다 — 조밀한 군집과 성긴 군집이 각자 다른 $\\varepsilon$ 에서 선택됩니다\n-   사용자가 정할 것은 **최소 군집 크기** 정도. 실무에서는 DBSCAN보다 HDBSCAN을 먼저 쓰는 것이 좋습니다 (R `dbscan::hdbscan`, Python `sklearn.cluster.HDBSCAN`)\n\n------------------------------------------------------------------------\n\n## 6. Hierarchical clustering 🌳\n\n### 1) 개요\n\n-   단계별로 데이터를 합치거나 나눠 **트리(덴드로그램)**를 만듭니다. $k$ 를 미리 정하지 않고, **원하는 높이에서 잘라** 군집을 얻습니다\n-   **Bottom-up (AGNES)** — 모든 샘플이 각자 군집 → 가장 가까운 둘을 계속 합침\n-   **Top-down (DIANA)** — 전체가 한 군집 → 계속 나눔. 계산량이 커서 덜 씀\n\n### 2) Linkage — 군집 사이 거리를 어떻게 잴 것인가\n\n| Linkage | 정의 | 성향 |\n|---|---|---|\n| **Single** | $d_{\\min}(C_i, C_j) = \\min_{\\mathbf{x}\\in C_i, \\mathbf{z}\\in C_j}\\text{dist}(\\mathbf{x}, \\mathbf{z})$ | 사슬처럼 길게 이어짐 (chaining) |\n| **Complete** | $d_{\\max} = \\max\\,\\text{dist}(\\mathbf{x}, \\mathbf{z})$ | 조밀하고 둥근 군집 |\n| **Average** | $d_{\\text{avg}} = \\frac{1}{\\|C_i\\|\\|C_j\\|}\\sum\\sum\\text{dist}(\\mathbf{x}, \\mathbf{z})$ | 중간 |\n| **Ward** `[신규]` | 합쳤을 때 **군집 내 제곱합의 증가량** | k-means와 같은 목적. 크기가 비슷한 군집 |\n\n### 3) 🧪 실습: 원자료의 A, B, C, D 예제\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDm <- matrix(0, 4, 4, dimnames = list(LETTERS[1:4], LETTERS[1:4]))\nDm[\"A\",\"B\"] <- 20; Dm[\"A\",\"C\"] <- 7; Dm[\"A\",\"D\"] <- 2\nDm[\"B\",\"C\"] <- 10; Dm[\"B\",\"D\"] <- 25; Dm[\"C\",\"D\"] <- 3\nDm <- Dm + t(Dm)\nhs <- lapply(c(\"single\", \"complete\", \"average\"), function(m) hclust(as.dist(Dm), method = m))\npar(mfrow = c(1, 3), mar = c(2, 4, 3, 1))\nfor (i in 1:3) plot(hs[[i]], main = c(\"single\", \"complete\", \"average\")[i],\n                    xlab = \"\", sub = \"\", ylab = \"height\", hang = -1)\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-23-1.png){width=729.6}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(linkage = c(\"single\", \"complete\", \"average\"),\n           merge_1_AD  = sapply(hs, function(h) h$height[1]),\n           merge_2_ADC = round(sapply(hs, function(h) h$height[2]), 2),\n           merge_3_all = round(sapply(hs, function(h) h$height[3]), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   linkage merge_1_AD merge_2_ADC merge_3_all\n1   single          2           3       10.00\n2 complete          2           7       25.00\n3  average          2           5       18.33\n```\n\n\n:::\n:::\n\n\n-   첫 병합은 셋 다 **A–D (거리 2)**\n-   다음 단계에서 $d(AD, C)$ 를 계산하는 방식이 갈립니다. single은 $\\min(7, 3) = 3$ (원자료 그림 ④와 일치), complete는 $\\max(7, 3) = 7$, average는 $(7+3)/2 = 5$\n-   병합 **순서는 같아도 높이가 다릅니다**. 덴드로그램을 같은 높이에서 자르면 다른 군집이 나옵니다\n\n### 4) 🧪 실습: 다리 하나가 single linkage를 무너뜨린다\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(34)\nXb <- rbind(cbind(rnorm(120, 0, .5), rnorm(120, 0, .5)),\n            cbind(rnorm(120, 4, .5), rnorm(120, 0, .5)),\n            cbind(seq(0.6, 3.4, length.out = 12), rnorm(12, 0, .06)),   # 두 군집을 잇는 다리 12개\n            cbind(rnorm(80, 2, .35), rnorm(80, 3.2, .35)))\nyb <- c(rep(1, 120), rep(2, 120), rep(0, 12), rep(3, 80))\nnb <- yb > 0\nlinks <- c(\"single\", \"complete\", \"average\", \"ward.D2\")\nhb <- lapply(links, function(m) hclust(dist(Xb), method = m))\ndo.call(rbind, lapply(seq_along(links), function(i) {\n  cl <- cutree(hb[[i]], 3)\n  data.frame(linkage = links[i],\n             ARI = round(ext_index(cl[nb], yb[nb])[[\"ARI\"]], 4),\n             cluster_sizes = paste(sort(table(cl), decreasing = TRUE), collapse = \" / \"),\n             cophenetic_cor = round(cor(dist(Xb), cophenetic(hb[[i]])), 4))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   linkage    ARI  cluster_sizes cophenetic_cor\n1   single 0.4754   251 / 80 / 1         0.5346\n2 complete 1.0000 128 / 124 / 80         0.8808\n3  average 1.0000 128 / 124 / 80         0.9224\n4  ward.D2 1.0000 128 / 124 / 80         0.9149\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlb <- do.call(rbind, lapply(seq_along(links), function(i) {\n  cl <- cutree(hb[[i]], 3)\n  cl <- match(cl, as.integer(names(sort(table(cl), decreasing = TRUE))))   # 크기 순으로 번호\n  data.frame(x1 = Xb[,1], x2 = Xb[,2], cl = factor(cl), linkage = links[i])\n}))\nlb$linkage <- factor(lb$linkage, levels = links)\nggplot(lb, aes(x1, x2, colour = cl)) +\n  geom_point(size = .8) + coord_equal() + facet_wrap(~ linkage, ncol = 2) +\n  scale_colour_manual(values = c(\"1\" = \"#2e8b7a\", \"2\" = \"#d1495b\", \"3\" = \"#7d8597\"),\n                      labels = c(\"largest\", \"2nd\", \"3rd\")) +\n  labs(colour = \"cluster\") + theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-26-1.png){width=729.6}\n:::\n:::\n\n\n-   single linkage는 다리 12개를 따라 **아래의 두 군집을 하나로 이어 붙이고**(251개), 세 번째 \"군집\"은 **점 1개**입니다. ARI 0.4754\n-   complete·average·Ward는 모두 ARI **1.0000**\n-   **Cophenetic correlation** — 덴드로그램 위의 병합 높이가 원래 거리를 얼마나 보존하는가. average가 0.9224로 가장 높고 single이 0.5346으로 가장 낮습니다\n-   ⚠️ single linkage의 사슬 현상은 **실제 데이터의 이상치 몇 개**로도 일어납니다. 발현 히트맵의 기본값으로 쓰지 마세요 (R `hclust` 기본값은 complete)\n\n### 5) 덴드로그램 자르기\n\n-   **높이 $h$ 로 자르기** (`cutree(h, h = ...)`) — 원자료 그림의 점선. 거리 척도가 의미 있을 때\n-   **개수 $k$ 로 자르기** (`cutree(h, k = ...)`) — 4절의 $k$ 선택 문제로 돌아옵니다\n-   **동적 자르기** (`dynamicTreeCut`) — 가지마다 다른 높이에서. WGCNA 모듈 탐지의 기본\n-   계산량 — 거리행렬이 $O(n^2)$ 메모리. **세포 수만 개 이상이면 사실상 불가능** → 7절\n\n------------------------------------------------------------------------\n\n## 7. Graph-based clustering 🕸️ `[신규]`\n\n단일세포·공간전사체 분석에서 **실질적으로 가장 많이 쓰는 방법**입니다 (Seurat `FindClusters`, Scanpy `sc.tl.leiden`).\n\n### 1) 파이프라인\n\n1.  **PCA** — 수천 개 유전자를 수십 개 성분으로 (W13)\n2.  **kNN 그래프** — 각 세포를 가장 가까운 $k$ 개 세포와 연결\n3.  **SNN 가중치** — 두 세포가 **공유하는 이웃의 비율**(Jaccard)로 edge 가중치. 우연한 연결을 약화\n4.  **Community detection** — 그래프를 **modularity**가 최대가 되도록 나눔\n\n$$Q = \\frac{1}{2m}\\sum_{i,j}\\left[A_{ij} - \\gamma\\frac{k_i k_j}{2m}\\right]\\delta(c_i, c_j)$$\n\n\"같은 군집 안의 연결이 **무작위로 연결했을 때의 기댓값**($k_ik_j/2m$)보다 얼마나 많은가\". $\\gamma$ 는 **resolution** — 클수록 작은 군집을 선호합니다.\n\n### 2) Louvain과 Leiden\n\n**Louvain** (Blondel et al. 2008)\n\n1.  **Local moving** — 각 노드를 이웃 군집으로 옮겨 보고, $Q$ 가 가장 많이 오르는 곳으로 이동. 더 이상 안 바뀔 때까지 반복\n2.  **Aggregation** — 각 군집을 하나의 노드로 접어 새 그래프를 만듦\n3.  1–2를 $Q$ 가 더 오르지 않을 때까지 반복\n\n**Leiden** (Traag et al. 2019) — Louvain은 **내부가 끊어진 군집**을 만들 수 있습니다(연결 노드가 빠져나가도 나머지를 그대로 둠). Leiden은 aggregation 전에 **refinement** 단계를 넣어 모든 군집이 잘 연결되도록 보장합니다. 현재 Seurat·Scanpy의 권장 기본값입니다.\n\n### 3) 🧪 실습: SNN 그래프와 Louvain 직접 구현\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnn_graph <- function(X, k = 15, prune = 1/15) {\n  n <- nrow(X); D <- as.matrix(dist(X)); A <- matrix(0, n, n)\n  for (i in 1:n) A[i, order(D[i, ])[1:(k + 1)]] <- 1        # kNN (자기 자신 포함 k+1)\n  S <- A %*% t(A)                                            # 공유 이웃 수\n  J <- S / (2 * (k + 1) - S)                                 # Jaccard\n  J[J < prune] <- 0; diag(J) <- 0\n  J\n}\nmodularity <- function(W, comm, gamma = 1) {\n  m2 <- sum(W); k <- rowSums(W)\n  inn <- tapply(seq_len(nrow(W)), comm, function(ix) sum(W[ix, ix]))\n  tot <- tapply(k, comm, sum)\n  (sum(inn) - gamma * sum(tot^2) / m2) / m2\n}\nlouvain_move <- function(W, gamma) {                          # 1단계: local moving\n  n <- nrow(W); k <- rowSums(W); m2 <- sum(W)\n  comm <- seq_len(n); tot <- k; moved <- FALSE\n  repeat {\n    improved <- FALSE\n    for (i in sample(n)) {\n      ci <- comm[i]; nb <- which(W[i, ] > 0); nb <- nb[nb != i]\n      if (!length(nb)) next\n      tot[ci] <- tot[ci] - k[i]                               # i 를 자기 군집에서 빼고\n      kin  <- tapply(W[i, nb], comm[nb], sum); cand <- as.integer(names(kin))\n      gain <- kin - gamma * tot[cand] * k[i] / m2             # 각 이웃 군집으로 갈 때의 이득\n      own  <- (if (ci %in% cand) kin[[as.character(ci)]] else 0) - gamma * tot[ci] * k[i] / m2\n      newc <- if (max(gain) > own + 1e-12) cand[which.max(gain)] else ci\n      comm[i] <- newc; tot[newc] <- tot[newc] + k[i]\n      if (newc != ci) { improved <- TRUE; moved <- TRUE }\n    }\n    if (!improved) break\n  }\n  list(comm = as.integer(factor(comm)), moved = moved)\n}\nlouvain <- function(W, gamma = 1, seed = 1) {\n  set.seed(seed); memb <- seq_len(nrow(W)); level <- 0\n  repeat {\n    r <- louvain_move(W, gamma)\n    if (!r$moved) break\n    level <- level + 1; memb <- r$comm[memb]\n    Z <- diag(max(r$comm))[r$comm, , drop = FALSE]            # 2단계: 군집을 한 노드로 접는다\n    W <- t(Z) %*% W %*% Z\n  }\n  list(cluster = memb, levels = level)\n}\n```\n:::\n\n\n### 4) 🧪 실습: 단일세포 모사 데이터\n\n세포 750개 × 유전자 500개. 유형 5개의 크기는 300 / 200 / 150 / 80 / **20**이고, **T5(20개)는 T4와 marker 20개 중 12개를 공유하는 희귀 아형**입니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_sc <- function(seed) {\n  set.seed(seed)\n  sizes <- c(T1 = 300, T2 = 200, T3 = 150, T4 = 80, T5 = 20)\n  G <- 500\n  base <- rnorm(G, 0, 1)                                    # 유전자별 기본 발현 (log)\n  mk <- split(sample(G, 100), rep(1:5, each = 20))          # 유형별 marker 20개\n  mk[[5]] <- c(mk[[4]][1:12], mk[[5]][1:8])                 # T5 는 T4 와 12개 공유\n  y <- rep(names(sizes), sizes)\n  lfc <- matrix(0, length(y), G)\n  for (t in 1:5) lfc[y == names(sizes)[t], mk[[t]]] <- 1.6\n  s  <- exp(rnorm(length(y), 0, 0.3))                       # library size\n  mu <- s * exp(sweep(lfc, 2, base, \"+\"))\n  list(cnt = matrix(rnbinom(length(mu), mu = mu, size = 4), nrow(mu)), y = y)\n}\nsc   <- sim_sc(41)\nlib  <- rowSums(sc$cnt)\nlogn <- log1p(sc$cnt / lib * median(lib))                   # library 정규화 + log\nPC   <- prcomp(logn, center = TRUE, scale. = TRUE)$x[, 1:15]\n\nW  <- snn_graph(PC, k = 15)\nlv <- louvain(W, gamma = 1, seed = 1)\ndata.frame(n_edges = sum(W > 0) / 2, n_clusters = max(lv$cluster),\n           modularity = round(modularity(W, lv$cluster), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n_edges n_clusters modularity\n1   40618          4     0.7255\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(louvain = lv$cluster, truth = sc$y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       truth\nlouvain  T1  T2  T3  T4  T5\n      1 300   0   0   0   0\n      2   0 200   0   0   0\n      3   0   0 150   0   0\n      4   0   0   0  80  20\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nkm5 <- kmeans(PC, 5, nstart = 20)$cluster\nhw5 <- cutree(hclust(dist(PC), \"ward.D2\"), 5)\ntable(kmeans = km5, truth = sc$y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      truth\nkmeans  T1  T2  T3  T4  T5\n     1   0   0   0  80  20\n     2   0 200   0   0   0\n     3 168   0   0   0   0\n     4   0   0 150   0   0\n     5 132   0   0   0   0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrare_stat <- function(cl, y, lab = \"T5\") {   # T5 를 가장 많이 담은 군집 기준\n  tb <- table(cl[y == lab]); best <- as.integer(names(which.max(tb)))\n  c(recall = max(tb) / sum(y == lab), purity = max(tb) / sum(cl == best))\n}\nrs <- rbind(rare_stat(km5, sc$y), rare_stat(hw5, sc$y), rare_stat(lv$cluster, sc$y))\ndata.frame(method = c(\"k-means (k=5, told)\", \"hclust Ward (k=5, told)\", \"Louvain (gamma=1)\"),\n           n_clusters = c(5, 5, max(lv$cluster)),\n           ARI = round(c(ext_index(km5, sc$y)[[\"ARI\"]], ext_index(hw5, sc$y)[[\"ARI\"]],\n                         ext_index(lv$cluster, sc$y)[[\"ARI\"]]), 4),\n           T5_recall = round(rs[, \"recall\"], 3), T5_purity = round(rs[, \"purity\"], 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   method n_clusters    ARI T5_recall T5_purity\n1     k-means (k=5, told)          5 0.7732         1     0.200\n2 hclust Ward (k=5, told)          5 0.9991         1     0.952\n3       Louvain (gamma=1)          4 0.9860         1     0.200\n```\n\n\n:::\n:::\n\n\n-   **k-means (k = 5)** — 정답 개수를 알려줬는데도 **T1(300개)을 168 / 132로 쪼개고, T4와 T5를 합쳤습니다.** ARI 0.7732\n-   이유는 목적함수입니다. **큰 군집을 둘로 쪼개면 SSE가 크게 줄고, 20개짜리를 따로 세우면 조금밖에 안 줍니다.** k-means는 희귀 세포를 싫어하도록 설계되어 있습니다\n-   **Louvain** — 군집 수(4개)를 **스스로 정했고** T1~T3을 완벽히 분리. 다만 **T5는 T4에 합쳐졌습니다** (T5 purity 0.2 = 100개 군집 중 20개). ARI 0.9860\n-   Ward (k = 5)는 ARI 0.9991로 거의 완벽 — 하지만 **우리가 $k = 5$ 를 알려줬기 때문**입니다. 실제로는 모르는 숫자입니다\n\n### 5) 🧪 실습: resolution $\\gamma$ 를 올리면?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_sweep <- do.call(rbind, lapply(c(0.2, 0.5, 1, 1.5, 2, 3), function(g) {\n  r <- louvain(W, gamma = g, seed = 1); st <- rare_stat(r$cluster, sc$y)\n  data.frame(gamma = g, n_clusters = max(r$cluster),\n             ARI = round(ext_index(r$cluster, sc$y)[[\"ARI\"]], 4),\n             T5_recall = round(st[[\"recall\"]], 3), T5_purity = round(st[[\"purity\"]], 3))\n}))\nres_sweep\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  gamma n_clusters    ARI T5_recall T5_purity\n1   0.2          4 0.9860         1       0.2\n2   0.5          4 0.9860         1       0.2\n3   1.0          4 0.9860         1       0.2\n4   1.5          4 0.9860         1       0.2\n5   2.0          6 0.6889         1       0.2\n6   3.0          9 0.5107         1       0.2\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 강건성: kNN 의 k 와 노드 순서(seed)를 바꿔도 같은가\nrbind(\n  do.call(rbind, lapply(c(5, 10, 30, 60), function(kk) { r <- louvain(snn_graph(PC, kk), 1, 1)\n    data.frame(setting = paste0(\"k = \", kk, \", seed = 1\"), n_clusters = max(r$cluster),\n               ARI = round(ext_index(r$cluster, sc$y)[[\"ARI\"]], 4)) })),\n  do.call(rbind, lapply(2:4, function(s) { r <- louvain(W, 1, s)\n    data.frame(setting = paste0(\"k = 15, seed = \", s), n_clusters = max(r$cluster),\n               ARI = round(ext_index(r$cluster, sc$y)[[\"ARI\"]], 4)) })))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           setting n_clusters   ARI\n1  k = 5, seed = 1          4 0.986\n2 k = 10, seed = 1          4 0.986\n3 k = 30, seed = 1          4 0.986\n4 k = 60, seed = 1          4 0.986\n5 k = 15, seed = 2          4 0.986\n6 k = 15, seed = 3          4 0.986\n7 k = 15, seed = 4          4 0.986\n```\n\n\n:::\n:::\n\n\n-   $\\gamma$ 를 0.2 → 1.5로 올려도 **4개 그대로**. 2에서 6개, 3에서 9개로 늘어나지만 **T5는 끝까지 T4에 붙어 있습니다**(purity 0.2)\n-   늘어난 군집은 **T1~T3가 쪼개진 것**이고, 그래서 ARI는 0.9860 → 0.5107로 **오히려 떨어집니다**\n-   kNN의 $k$ (5~60)와 seed를 바꿔도 결과는 **항상 4개, ARI 0.986** — 우연이 아니라 **구조적**입니다\n-   ✅ **\"resolution을 올리면 희귀 세포가 나온다\"는 기대는 틀릴 수 있습니다.** 해상도는 모든 군집에 한꺼번에 작용합니다\n\n### 6) 🧪 실습: 왜 못 찾았나, 그리고 sub-clustering\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt5 <- which(sc$y == \"T5\"); t4 <- which(sc$y == \"T4\")\nDp <- as.matrix(dist(PC))\nc(T5_share_of_T5_15NN = round(mean(sapply(t5, function(i)\n    mean(sc$y[order(Dp[i, ])[2:16]] == \"T5\"))), 3),\n  SNN_weight_T5_T5 = round(sum(W[t5, t5]), 1),\n  SNN_weight_T5_T4 = round(sum(W[t5, t4]), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT5_share_of_T5_15NN    SNN_weight_T5_T5    SNN_weight_T5_T4 \n              0.577             125.700             116.500 \n```\n\n\n:::\n:::\n\n\n-   T5 세포의 15개 이웃 중 T5는 **57.7%**뿐. 그래프에서 T5–T4 연결(116.5)이 T5 내부 연결(125.7)과 **거의 같습니다**\n-   전체 750개 세포로 만든 PCA는 **T1~T3를 가르는 축**에 분산을 쓰느라 T4/T5를 가르는 미세한 축을 잡지 못했습니다\n\n그래서 단일세포 분석에서는 **합쳐진 군집만 떼어 다시 분석**합니다 (sub-clustering).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsub <- which(lv$cluster == lv$cluster[t5[1]])               # T4+T5 가 들어간 군집 (100개)\nPCs <- prcomp(logn[sub, ], center = TRUE, scale. = TRUE)$x[, 1:10]   # 이 세포들만으로 PCA\nWs  <- snn_graph(PCs, k = 10)\nfor (g in c(0.5, 1)) {\n  r <- louvain(Ws, gamma = g, seed = 1)\n  cat(\"gamma =\", g, \"-> sub-clusters:\", max(r$cluster), \"\\n\")\n  print(table(sub_cluster = r$cluster, truth = sc$y[sub]))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngamma = 0.5 -> sub-clusters: 1 \n           truth\nsub_cluster T4 T5\n          1 80 20\ngamma = 1 -> sub-clusters: 5 \n           truth\nsub_cluster T4 T5\n          1  7  0\n          2 28  0\n          3 27  0\n          4 17  0\n          5  1 20\n```\n\n\n:::\n\n```{.r .cell-code}\nround(cor(PCs[, 1], sc$y[sub] == \"T5\"), 3)                   # 부분 PCA의 PC1 과 T5 소속의 상관\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.86\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrp <- function(y) factor(ifelse(y == \"T5\", \"T5 (rare)\", ifelse(y == \"T4\", \"T4\", \"other\")),\n                          levels = c(\"T5 (rare)\", \"T4\", \"other\"))\npp <- rbind(data.frame(a = PC[,1],  b = PC[,2],  type = grp(sc$y),      view = \"all 750 cells: PC1 vs PC2\"),\n            data.frame(a = PCs[,1], b = PCs[,2], type = grp(sc$y[sub]), view = \"re-PCA of the T4+T5 cluster\"))\npp$view <- factor(pp$view, levels = c(\"all 750 cells: PC1 vs PC2\", \"re-PCA of the T4+T5 cluster\"))\npp <- pp[order(pp$type, decreasing = TRUE), ]                # T5 를 맨 위에\nggplot(pp, aes(a, b, colour = type)) +\n  geom_point(size = 1.1, alpha = .85) + facet_wrap(~ view, scales = \"free\") +\n  scale_colour_manual(values = c(\"T5 (rare)\" = \"#d1495b\", \"T4\" = \"#2e8b7a\", \"other\" = \"#7d8597\")) +\n  labs(x = \"PC1\", y = \"PC2\", colour = NULL) + theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](12_clustering_files/figure-html/unnamed-chunk-35-1.png){width=729.6}\n:::\n:::\n\n\n-   T4+T5 군집(100개)만으로 PCA를 다시 하면 PC1과 T5 소속의 상관이 **-0.86** — **PC1이 곧 T4/T5 축**이 됩니다 (오른쪽 그림)\n-   $\\gamma = 1$ 에서 **T5 20개가 T4 한 개와 함께 독립 군집으로** 분리됩니다\n-   ⚠️ 그런데 **T4(균질한 유형)도 4조각**(7 / 28 / 27 / 17)으로 쪼개졌습니다. T4에는 실제 하위구조가 없는데도요\n-   ✅ **Louvain은 구조가 없는 데이터에서도 군집을 만듭니다.** modularity는 \"무작위보다 조밀한가\"를 볼 뿐, \"생물학적으로 다른가\"는 모릅니다\n-   ✅ 그래서 sub-cluster마다 **marker 유전자로 검증**해야 합니다\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gamma = 1 의 sub-cluster 마다: 나머지 세포보다 평균 log 발현이 0.8 이상 높은 유전자 수\nr1 <- louvain(Ws, gamma = 1, seed = 1)\nL  <- logn[sub, ]\ndo.call(rbind, lapply(sort(unique(r1$cluster)), function(k) {\n  d <- colMeans(L[r1$cluster == k, , drop = FALSE]) - colMeans(L[r1$cluster != k, , drop = FALSE])\n  data.frame(sub_cluster = k, n_cells = sum(r1$cluster == k),\n             n_T5 = sum(sc$y[sub][r1$cluster == k] == \"T5\"),\n             n_up_genes = sum(d > 0.8), max_log_diff = round(max(d), 2))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sub_cluster n_cells n_T5 n_up_genes max_log_diff\n1           1       7    0          0         0.67\n2           2      28    0          0         0.46\n3           3      27    0          0         0.53\n4           4      17    0          0         0.56\n5           5      21   20          7         1.46\n```\n\n\n:::\n:::\n\n\n-   T5 군집만 **올라간 유전자 7개**(최대 차이 1.46)를 가집니다. 시뮬레이션에서 T5 고유 marker는 8개였습니다\n-   T4의 네 조각은 올라간 유전자가 **0개**(최대 차이 0.46~0.67) — 생물학적으로 구분할 근거가 없는 과분할입니다\n\n------------------------------------------------------------------------\n\n## 8. 장단점과 실무 지침 ⚠️\n\n### 1) 방법 비교\n\n| 방법 | $k$ 필요 | 모양 | 잡음 처리 | 규모 | 주의 |\n|---|---|---|---|---|---|\n| **k-means** | 필요 | 구형, 비슷한 크기 | 없음 | 매우 큼 | 초기값, 희귀 군집 흡수 |\n| **GMM** | 필요 | 타원 | 없음(확률은 줌) | 중간 | 고차원에서 공분산 불안정 |\n| **DBSCAN** | 불필요 | 자유 | **있음** | 중간~큼 | $\\varepsilon$ 극도로 민감, 밀도 차 |\n| **HDBSCAN** | 불필요 | 자유 | 있음 | 중간~큼 | 최소 군집 크기 |\n| **계층적** | 사후에 | linkage 의존 | 없음 | $n^2$ 메모리 | single linkage 사슬 |\n| **Louvain/Leiden** | 불필요($\\gamma$) | 그래프 구조 | 없음 | **매우 큼** | resolution, 과분할 |\n\n### 2) 체크리스트\n\n-   **거리부터 정하세요** — 표준화했는가? 크기를 볼 것인가 패턴을 볼 것인가? (3절)\n-   **여러 번 돌리세요** — k-means는 `nstart ≥ 20`, Louvain/Leiden은 여러 seed\n-   **여러 $k$ / resolution을 보세요** — 하나의 숫자를 \"진짜 군집 수\"로 보고하지 말 것\n-   **안정성을 확인하세요** — 부트스트랩·부분표본으로 다시 돌려 ARI로 비교. 안정적이지 않은 군집은 해석하지 말 것\n-   **생물학으로 검증하세요** — marker, 경로 농축, 독립 코호트에서의 재현\n\n::: {.callout-warning}\n## ⚠️ 군집 결과를 논문에 쓸 때\n\n-   **군집 수를 어떻게 정했는지 명시** — 알고리즘, resolution, $k$ 와 그 근거. \"Louvain으로 12개 군집을 얻었다\"만으로는 재현 불가\n-   **일치도는 ARI(또는 NMI)로** — Rand index는 무작위 label에도 0.74가 나옵니다\n-   **군집을 만든 데이터로 군집 간 차이를 검정하지 말 것** — 군집이 이미 그 차이로 만들어졌으므로 $p$-값이 무조건 작습니다(double dipping). 별도 데이터나 selective inference가 필요\n-   **\"새로운 세포 아형\"을 주장하려면** — 과분할이 아님을 보이는 marker, 여러 resolution과 seed에서의 안정성, 가능하면 독립 데이터에서의 재현\n-   **t-SNE/UMAP 그림에서 보이는 덩어리를 군집의 근거로 쓰지 말 것** — 군집화는 PCA 공간이나 그래프에서, 시각화는 결과 표시용 (W13)\n-   **batch effect를 먼저 보정** — 그렇지 않으면 군집이 세포 유형이 아니라 실험 날짜를 따라갑니다\n:::\n\n::: {.callout-important}\n## Where this ends up\n\n-   GMM의 EM → W11 7절의 EM과 같은 기계. 숨은 변수가 \"어느 군집 소속인가\"일 뿐\n-   k-means ↔ Ward linkage ↔ GMM의 극한 — 모두 **군집 내 제곱합**이라는 같은 목적\n-   PCA로 차원을 줄인 뒤 군집화, t-SNE/UMAP 시각화, kNN의 차원의 저주 → **W13**\n-   거리 학습(metric learning), kernel로 비선형 거리 → W13, W10\n-   군집을 label처럼 쓰는 다음 단계(차등발현, 분류기 학습)의 double dipping → W14\n-   외부 지표(ARI)와 W4의 혼동행렬 — 쌍(pair) 단위로 세면 같은 TP/FP/FN/TN 구조\n:::\n\n------------------------------------------------------------------------\n\n## 📝 Summary\n\n-   군집화에는 **정답이 없고**, 알고리즘마다 \"군집\"의 정의가 다릅니다. 어떤 정의가 질문에 맞는지 먼저 정해야 합니다\n-   **외부 지표**는 샘플 쌍을 SS/SD/DS/DD로 셉니다. (원자료와 달리) **DS는 FN**입니다\n-   **RI는 무작위 label에 속습니다** — 군집 50개면 0.7417. **ARI**는 우연 수준을 빼서 항상 0 근처\n-   **내부 지표**(silhouette·DB·Dunn)는 blob 4개에서 모두 $k = 4$ 를 골랐지만, 중심·거리 기반이라 k-means의 편향을 공유합니다\n-   **거리가 결과를 정합니다** — Minkowski $p$ 에 따라 최근접 이웃이 A → B로 바뀌고, 표준화 여부로 ARI가 0.0045 ↔ 1\n-   발현 데이터는 **correlation distance**가 패턴으로 묶습니다 (ARI 1 vs Euclidean -0.0263). 단 $1 - r$ 과 cosine은 **삼각부등식을 어깁니다**\n-   **k-means = Lloyd 알고리즘** — 직접 구현이 `kmeans()`와 SSE까지 일치. 국소해만 보장\n-   초깃값: 무작위 **25.5%**, k-means++ **36.0%**만 전역해 도달 → **`nstart`를 크게**\n-   $k$ 선택 — elbow·silhouette·gap 최댓값은 $k = 4$, **gap의 1-SE 규칙은 $k = 2$**. 규칙마다 다른 질문에 답합니다\n-   길쭉한 군집에서 k-means ARI 0.5953 vs **GMM(EM) 0.9933**. k-means는 GMM의 특수한 경우\n-   **DBSCAN** — 반달에서 k-means 0.2791 vs **0.9657**, 잡음 분리. 그러나 $\\varepsilon$ 0.05 차이로 ARI 0.4041 → 0.9657 → 0\n-   밀도가 다른 군집은 $\\varepsilon$ 하나로 불가능(최선 0.7668) → **HDBSCAN**\n-   계층적 — 원자료 A–D 예제에서 병합 높이가 single 2 / 3 / 10, complete 2 / 7 / 25. **single linkage는 다리 하나에 무너집니다**(ARI 0.4754 vs 나머지 1)\n-   **그래프 기반(Louvain/Leiden)** — kNN → SNN → modularity. 단일세포의 사실상 표준\n-   단일세포 모사 — **k-means(k = 5)는 큰 유형을 쪼개고 희귀 유형을 합침**(0.7732). Louvain은 4개를 스스로 찾았지만(0.9860) **희귀 T5를 T4에 흡수**\n-   **resolution을 올리면 희귀 유형보다 큰 군집이 먼저 쪼개집니다** ($\\gamma = 3$ 에서 ARI 0.5107)\n-   **sub-clustering**으로 T5를 분리했지만 균질한 T4도 4조각 — Louvain은 구조가 없어도 군집을 만듭니다. marker를 세면 T5 군집은 7개, T4 조각들은 **0개** — **marker로 검증**할 것\n\n## 🔑 Key terms\n\n| 용어 | 정의 |\n|------|------|\n| **External index** | 기준 label과 비교. 쌍 단위 SS/SD/DS/DD = TP/FP/FN/TN |\n| **Rand index / ARI** | $2(a+d)/m(m-1)$ / 우연 기댓값을 뺀 RI. 무작위면 0 |\n| **Internal index** | label 없이 응집·분리만으로 평가 |\n| **Silhouette** | $(b - a)/\\max(a, b)$. 샘플별로 계산, 음수면 잘못 배정 |\n| **Davies–Bouldin / Dunn** | 군집 내 퍼짐 ÷ 군집 간 거리 (작을수록) / 최소 군집 간 거리 ÷ 최대 지름 (클수록) |\n| **Minkowski distance** | $(\\sum\\|x_u - y_u\\|^p)^{1/p}$. $p$ = 1 Manhattan, 2 Euclidean |\n| **VDM** | 범주형 값 사이 거리를 군집 분포 차이로 정의 |\n| **Correlation distance** | $1 - r$. 크기가 아니라 패턴. 엄밀한 척도는 아님 |\n| **k-means / Lloyd** | 군집 내 제곱합 최소화. 배정 ↔ 갱신 반복, 국소해 |\n| **k-means++** | 기존 centroid에서 먼 점을 $D^2$ 확률로 뽑는 초기화 |\n| **Gap statistic** | 균일분포 참조 대비 $\\log W_k$ 의 차이 |\n| **GMM** | 정규분포 혼합. EM으로 학습, 소속 확률을 줌 |\n| **DBSCAN** | $\\varepsilon$, MinPts로 core/border/noise 구분, 밀도 연결 |\n| **HDBSCAN** | 모든 $\\varepsilon$ 에 대한 밀도 계층에서 안정적 군집 선택 |\n| **Linkage** | 군집 간 거리. single / complete / average / Ward |\n| **Cophenetic correlation** | 덴드로그램 병합 높이와 원래 거리의 상관 |\n| **SNN graph** | 공유 이웃 비율(Jaccard)로 가중치를 준 kNN 그래프 |\n| **Modularity / resolution** | 기대보다 조밀한 정도 / $\\gamma$, 클수록 작은 군집 |\n| **Louvain / Leiden** | modularity 최대화. Leiden은 refinement로 연결성 보장 |\n| **Sub-clustering** | 한 군집만 떼어 PCA·그래프를 다시 만들어 재군집 |\n\n## ➕ References\n\n-   Jain AK. Data clustering: 50 years beyond K-means. *Pattern Recognition Letters* 2010;31(8):651–666.\n-   Hubert L, Arabie P. Comparing partitions. *Journal of Classification* 1985;2:193–218.\n-   Rousseeuw PJ. Silhouettes: a graphical aid to the interpretation and validation of cluster analysis. *J Comput Appl Math* 1987;20:53–65.\n-   Davies DL, Bouldin DW. A cluster separation measure. *IEEE TPAMI* 1979;1(2):224–227.\n-   Tibshirani R, Walther G, Hastie T. Estimating the number of clusters in a data set via the gap statistic. *JRSS-B* 2001;63(2):411–423.\n-   Arthur D, Vassilvitskii S. k-means++: the advantages of careful seeding. *SODA 2007*:1027–1035.\n-   Ester M, Kriegel HP, Sander J, Xu X. A density-based algorithm for discovering clusters in large spatial databases with noise. *KDD 1996*:226–231.\n-   Campello RJGB, Moulavi D, Sander J. Density-based clustering based on hierarchical density estimates. *PAKDD 2013*:160–172.\n-   Blondel VD, Guillaume JL, Lambiotte R, Lefebvre E. Fast unfolding of communities in large networks. *J Stat Mech* 2008:P10008.\n-   Traag VA, Waltman L, van Eck NJ. From Louvain to Leiden: guaranteeing well-connected communities. *Sci Rep* 2019;9:5233.\n-   Fortunato S, Barthélemy M. Resolution limit in community detection. *PNAS* 2007;104(1):36–41.\n-   Kiselev VY, Andrews TS, Hemberg M. Challenges in unsupervised clustering of single-cell RNA-seq data. *Nat Rev Genet* 2019;20:273–282.\n-   Luecken MD, Theis FJ. Current best practices in single-cell RNA-seq analysis: a tutorial. *Mol Syst Biol* 2019;15:e8746.\n-   Zhang JM, Kamath GM, Tse DN. Valid post-clustering differential analysis for single-cell RNA-seq. *Cell Systems* 2019;9(4):383–392.\n\n------------------------------------------------------------------------\n\n[← W11. Bayesian Classifier](11_bayes.qmd)\n",
    "supporting": [
      "12_clustering_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}