{
  "hash": "e5a97e4470f5d910fdf8b37c250a26b5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"W9. Ensemble Learning\"\ndescription: \"Bagging, random forest, boosting, stacking — 그리고 diversity\"\nauthor: \"Eunji Ha\"\ndate: today\n\n# ── AI 채팅 위젯 설정 ──────────────────────────────────────────\nformat:\n  html:\n    include-in-header:\n      text: |\n        <meta name=\"ai-title\" content=\"W9. Ensemble Learning\">\n        <meta name=\"ai-context\" content=\"\n        이 챕터는 앙상블 학습을 다룹니다.\n        여러 학습기를 만들어 결합하며, base learner가 같은 종류면 homogeneous,\n        다른 종류면 heterogeneous입니다.\n        개별 학습기의 오차가 독립이면 다수결 오차는 Hoeffding 부등식에 따라\n        학습기 수 T에 대해 지수적으로 줄어듭니다. 실습에서 개별 오차 0.4인 학습기를\n        독립으로 51개 모으면 오차가 0.074로 떨어지지만,\n        상관 0.3이면 0.329, 상관 0.6이면 0.376에서 멈춥니다.\n        같은 데이터로 학습하므로 독립은 불가능하고, 그래서 accuracy와 diversity의\n        상충을 관리하는 것이 앙상블의 전부입니다.\n        bagging은 bootstrap으로 데이터를 흔들어 variance를 줄입니다.\n        실습에서 단일 트리 0.782가 트리 100개 bagging으로 0.828이 되고,\n        bootstrap에서 빠지는 약 36.8퍼센트(1/e)의 샘플로 OOB 오차를 계산해\n        별도 validation set 없이 0.810을 얻습니다.\n        random forest는 여기에 feature sampling을 더합니다. mtry를 2에서 12까지 늘리면\n        개별 트리 정확도는 0.546에서 0.725로 오르지만 트리 사이 불일치도는\n        0.486에서 0.292로 떨어지고, 앙상블 정확도는 중간인 mtry 8에서 0.843으로 최대가 됩니다.\n        이것이 accuracy-diversity 상충의 실증입니다.\n        다만 rpart로는 split마다 feature를 뽑을 수 없어 tree마다 뽑는 random subspace로\n        근사했습니다. 진짜 random forest는 split마다 뽑습니다.\n        boosting은 순차적으로 이전 학습기가 틀린 샘플에 weight를 주며 bias를 줄입니다.\n        AdaBoost 실습에서 depth 1 stump는 train 0.868 test 0.802,\n        depth 2는 train 0.948 test 0.818, depth 3은 train 1.0인데 test는 0.818로\n        더 나아지지 않습니다. base learner가 약할수록 boosting이 잘 듣습니다.\n        gradient boosting은 잔차를 순차적으로 적합하며 learning rate eta로 조절합니다.\n        eta 1.0은 M=10에서 test RMSE 0.386으로 최저였다가 M=300에서 0.459로 나빠지고,\n        eta 0.1은 M=300에서 0.346으로 안정적입니다.\n        stacking은 base learner들의 out-of-fold 예측을 meta learner의 입력으로 씁니다.\n        실습에서 로지스틱 0.850, 트리 0.782, kNN 0.785인데 단순 평균은 0.843,\n        stacking은 0.845이고 meta 계수는 glm 5.04, tree 0.50, knn 0.48로\n        가장 잘 맞는 학습기에 가중치를 몰아줍니다.\n        이 데이터의 진짜 경계가 선형이라 로지스틱 하나가 앙상블보다 나았다는 점이 중요합니다.\n        앙상블은 만능이 아닙니다.\n        \">\n---\n\n::: {.callout-note}\n## 🎯 Learning objectives\n\n-   앙상블이 오차를 줄이는 조건(독립성)을 Hoeffding 부등식으로 설명할 수 있다\n-   **accuracy와 diversity가 상충한다는 것을 수치로 보일 수 있다**\n-   bagging과 boosting의 차이를 variance/bias 관점에서 설명할 수 있다\n-   **OOB 오차가 무엇이고 왜 별도 validation set을 대신할 수 있는지 설명할 수 있다**\n-   AdaBoost와 gradient boosting의 갱신 규칙을 쓰고 직접 구현할 수 있다\n-   **averaging / voting / stacking을 구분하고 stacking의 누수 위험을 피할 수 있다**\n:::\n\n> 🤔 **정확도 60%짜리 모델 100개를 모으면 정확도 99%가 될까? 된다면 왜 아무도 그렇게 안 할까?**\n\n------------------------------------------------------------------------\n\n## 1. 여러 개를 모으면 왜 나아지는가 🗳️\n\n### 1) 용어\n\n-   **Ensemble learning** (= multi-classifier system, committee-based learning) — 같은 문제에 대해 학습기를 여러 개 만들어 **결합**\n-   **Individual learner** — 알고리즘 하나로 만든 학습기 하나\n-   **Homogeneous** — 개별 학습기가 모두 같은 종류. 이때 개별 학습기를 **base learner**라 부름 (트리 100개)\n-   **Heterogeneous** — 종류가 섞여 있음. 이때는 **component learner** (트리 + 로지스틱 + kNN)\n\n### 2) 오차 상한 — Hoeffding 부등식\n\n개별 학습기의 오차율이 $\\epsilon$ 이고 **서로 독립**이라면, $T$ 개를 다수결로 모았을 때 앙상블이 틀릴 확률은\n\n$$P(H(\\mathbf{x}) \\neq f(\\mathbf{x})) = \\sum_{k=0}^{\\lfloor T/2 \\rfloor} \\binom{T}{k}(1-\\epsilon)^k \\epsilon^{T-k}\n\\;\\le\\; \\exp\\!\\left(-\\tfrac{1}{2}T(1-2\\epsilon)^2\\right)$$\n\n-   $\\epsilon < 0.5$ 이기만 하면 **$T$ 가 커질수록 오차가 지수적으로 0에 수렴**\n-   \"약한 학습기를 모아 강한 학습기를 만든다\"는 주장의 근거\n\n### 3) 🧪 실습: '독립'이라는 가정이 전부다\n\n개별 오차 $\\epsilon = 0.4$ 인 학습기를 $T$ 개 모읍니다. 독립일 때, 그리고 오차가 서로 상관($\\rho$)될 때를 비교합니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nTs <- seq(1, 51, by = 2); eps <- 0.4\n\n# 독립일 때: 다수결이 틀릴 확률 = Binomial 꼬리확률\nindep <- pbinom(floor(Ts / 2), Ts, 1 - eps)\nbound <- exp(-0.5 * Ts * (1 - 2 * eps)^2)          # Hoeffding 상한\n\n# 상관이 있을 때: 공통 성분 u를 공유하는 잠재변수로 모의실험\nsim_rho <- function(T_, eps, rho, R = 20000, seed = 1) {\n  set.seed(seed); thr <- qnorm(eps)\n  u   <- matrix(rnorm(R), R, T_)                    # 모든 학습기가 공유하는 오차\n  lat <- sqrt(rho) * u + sqrt(1 - rho) * matrix(rnorm(R * T_), R, T_)\n  mean(rowSums(lat < thr) > T_ / 2)                 # 과반이 틀린 비율\n}\n\nlvl <- c(\"Independent (rho = 0)\", \"Correlated (rho = 0.3)\",\n         \"Correlated (rho = 0.6)\", \"Hoeffding bound\")\ncurves <- rbind(\n  data.frame(T = Ts, error = indep,                         kind = lvl[1]),\n  data.frame(T = Ts, error = sapply(Ts, sim_rho, eps, 0.3), kind = lvl[2]),\n  data.frame(T = Ts, error = sapply(Ts, sim_rho, eps, 0.6), kind = lvl[3]),\n  data.frame(T = Ts, error = bound,                         kind = lvl[4])\n)\ncurves$kind <- factor(curves$kind, levels = lvl)\n\nggplot(curves, aes(T, error, colour = kind, linetype = kind)) +\n  geom_line(linewidth = .9) +\n  scale_colour_manual(values  = setNames(c(\"#2e8b7a\", \"#d1495b\", \"#d1495b\", \"#7d8597\"), lvl)) +\n  scale_linetype_manual(values = setNames(c(1, 1, 3, 2), lvl)) +\n  labs(x = \"Number of learners (T)\", y = \"Ensemble error\",\n       colour = NULL, linetype = NULL,\n       caption = \"individual error = 0.4 in every case\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_ensemble_files/figure-html/unnamed-chunk-1-1.png){width=624}\n:::\n:::\n\n\n-   **독립이면** $T = 51$ 에서 오차 0.4 → **0.074**. 이론이 말하는 그대로입니다\n-   **$\\rho = 0.3$** 이면 0.329에서 멈춥니다. **$\\rho = 0.6$** 이면 0.376 — 거의 개선이 없습니다\n-   학습기를 아무리 늘려도 **상관이 있으면 바닥이 생깁니다**\n\n### 4) 그런데 독립은 불가능하다\n\n-   개별 학습기는 **같은 training set**으로 학습합니다. 독립일 수가 없습니다\n-   게다가 **accuracy와 diversity는 상충**합니다 — 모두 정확하려면 모두 진짜 함수에 가까워야 하고, 그러면 서로 닮습니다\n-   그래서 앙상블의 기술은 전부 **\"정확도를 크게 잃지 않으면서 어떻게 서로 다르게 만들까\"** 입니다\n\n::: {.callout-tip}\n## 원자료 노트의 한 줄\n\n> 일반적으로 generalization ↑ (**but 아주 좋은 single learner = best**)\n\n이 챕터의 실습 데이터가 정확히 그 경우입니다. 진짜 경계가 선형이라 **로지스틱 회귀 하나(0.850)가 트리 앙상블 전부(0.828\\~0.843)보다 낫습니다.** 앙상블은 공짜 성능이 아니라, 알맞은 단일 모델을 찾기 어려울 때 쓰는 보험입니다.\n:::\n\n### 5) 학습기 생성 방식\n\n| | **Serialization (순차)** | **Parallel (병렬)** |\n|---|---|---|\n| 의존 관계 | 앞 학습기에 **강하게 의존** | 거의 독립적으로 생성 |\n| 생성 순서 | 하나씩 순서대로 | 동시에 가능 |\n| 주로 줄이는 것 | **Bias** | **Variance** |\n| base learner | 약한 학습기(얕은 트리) | 강한 학습기(깊은 트리) |\n| 대표 | **Boosting** (AdaBoost, GBM) | **Bagging**, Random forest |\n\n------------------------------------------------------------------------\n\n## 2. Bagging 🎲\n\n### 1) Bootstrap aggregating\n\n-   training data $N$ 개에서 **복원추출로 $N$ 개**를 뽑아 부트스트랩 표본을 만듦\n-   이걸 $B$ 번 반복해 학습기 $B$ 개를 만들고\n\n$$s_L(\\cdot) = \\frac{1}{B}\\sum_{b=1}^{B} w_b(\\cdot) \\quad \\text{(회귀: 평균)}, \\qquad\ns_L(\\cdot) = \\arg\\max_k\\,\\mathrm{card}\\{b \\mid w_b(\\cdot) = k\\} \\quad \\text{(분류: 다수결)}$$\n\n-   각 표본이 원래 분포를 유지하면서 **조금씩 다르므로** 학습기들이 달라짐\n-   평균/투표가 **variance를 줄임**. 그래서 base learner는 **깊은 트리**(저bias 고variance)를 씁니다\n\n### 2) OOB (out-of-bag)\n\n-   복원추출이라 어떤 샘플은 한 번도 안 뽑힙니다. 안 뽑힐 확률은\n\n$$\\left(1 - \\frac{1}{N}\\right)^N \\xrightarrow[N \\to \\infty]{} \\frac{1}{e} \\approx 0.368$$\n\n-   각 샘플을 **그 샘플을 안 본 트리들**만으로 예측하면 **공짜 validation**이 생깁니다\n-   별도 hold-out 없이 generalization error를 추정할 수 있다는 것이 bagging의 큰 실무적 장점\n\n### 3) 🧪 실습: bagging을 직접 구현한다\n\n-   feature 12개 중 `x1`\\~`x4`만 진짜 신호(`x1`이 가장 강함), `z1`\\~`z8`은 노이즈\n-   환자 1200명 중 800명 학습\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rpart)\n\nset.seed(2026)\nn <- 1200\nX <- matrix(rnorm(n * 12), n)\ncolnames(X) <- c(paste0(\"x\", 1:4), paste0(\"z\", 1:8))\nlp  <- 2.2*X[,1] + 1.1*X[,2] + 1.0*X[,3] + 0.9*X[,4]\ndat <- as.data.frame(X)\ndat$y <- factor(rbinom(n, 1, plogis(lp)), labels = c(\"A\", \"B\"))\n\nset.seed(3)\nti <- sample(n, 800); tr <- dat[ti, ]; te <- dat[-ti, ]\nfe <- setdiff(names(dat), \"y\")\nfm <- as.formula(paste(\"y ~\", paste(fe, collapse = \" + \")))\nctrl <- rpart.control(cp = 0, minsplit = 10, minbucket = 5, xval = 0)  # 깊게 키운다\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# mtry = NULL 이면 bagging, 숫자를 주면 feature도 뽑는다 (3절)\nbag_fit <- function(B = 100, mtry = NULL, seed = 1) {\n  set.seed(seed); N <- nrow(tr)\n  trees <- vector(\"list\", B); oob <- matrix(NA_character_, N, B)\n  for (b in seq_len(B)) {\n    ib <- sample(N, N, replace = TRUE)                       # 부트스트랩\n    f  <- if (is.null(mtry)) fe else sample(fe, mtry)\n    m  <- rpart(as.formula(paste(\"y ~\", paste(f, collapse = \" + \"))),\n                data = tr[ib, ], method = \"class\", control = ctrl)\n    trees[[b]] <- m\n    o <- setdiff(seq_len(N), unique(ib))                     # 이 트리의 OOB 샘플\n    oob[o, b] <- as.character(predict(m, tr[o, ], type = \"class\"))\n  }\n  list(trees = trees, oob = oob)\n}\nvote <- function(M) apply(M, 1, function(v) {\n  v <- v[!is.na(v)]\n  if (!length(v)) NA_character_ else names(sort(table(v), decreasing = TRUE))[1]\n})\nens_pred <- function(m, nd)\n  vote(sapply(m$trees, function(t) as.character(predict(t, nd, type = \"class\"))))\n\nbag <- bag_fit(B = 100)\n\nsingle <- rpart(fm, data = tr, method = \"class\")\ndata.frame(\n  model    = c(\"Single tree\", \"Bagging (B = 100)\"),\n  test_acc = round(c(mean(predict(single, te, type = \"class\") == te$y),\n                     mean(ens_pred(bag, te) == te$y)), 3),\n  oob_acc  = c(\"-\", sprintf(\"%.3f\", mean(vote(bag$oob) == tr$y))),\n  oob_frac = c(\"-\", sprintf(\"%.3f\", mean(rowMeans(!is.na(bag$oob)))))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              model test_acc oob_acc oob_frac\n1       Single tree    0.782       -        -\n2 Bagging (B = 100)    0.828   0.810    0.368\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 트리를 하나씩 더할 때의 누적 정확도 (±1로 바꿔 cumsum하면 다수결과 같다)\nP   <- sapply(bag$trees, function(t) ifelse(predict(t, te, type = \"class\") == \"B\", 1, -1))\ncum <- t(apply(P, 1, cumsum))\nO   <- ifelse(is.na(bag$oob), 0, ifelse(bag$oob == \"B\", 1, -1))\ncumo <- t(apply(O, 1, cumsum))\n\ncurves2 <- rbind(\n  data.frame(B = 1:100, acc = sapply(1:100, function(b) mean(ifelse(cum[, b]  > 0, \"B\", \"A\") == te$y)),\n             kind = \"Test set\"),\n  data.frame(B = 1:100, acc = sapply(1:100, function(b) mean(ifelse(cumo[, b] > 0, \"B\", \"A\") == tr$y)),\n             kind = \"OOB estimate\")\n)\n\nggplot(curves2, aes(B, acc, colour = kind)) +\n  geom_line(linewidth = .9) +\n  geom_hline(yintercept = mean(predict(single, te, type = \"class\") == te$y),\n             linetype = 2, colour = \"grey40\") +\n  scale_colour_manual(values = c(\"Test set\" = \"#d1495b\", \"OOB estimate\" = \"#2e8b7a\")) +\n  labs(x = \"Number of trees (B)\", y = \"Accuracy\", colour = NULL,\n       caption = \"dashed = single tree\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_ensemble_files/figure-html/unnamed-chunk-4-1.png){width=624}\n:::\n:::\n\n\n-   단일 트리 0.782 → 트리 100개 bagging **0.828**\n-   **B = 25에서 이미 0.825** — 이득의 대부분은 앞쪽 몇십 개에서 나옵니다. $B$ 를 늘려도 과적합하지 않고 **수렴할 뿐**\n-   OOB 비율 **0.368** — 이론값 $1/e$ 와 정확히 일치\n-   OOB 추정치 0.810은 test 0.828보다 **살짝 비관적**입니다. 각 샘플이 전체가 아닌 약 37%의 트리로만 예측되기 때문 (정상입니다)\n\n------------------------------------------------------------------------\n\n## 3. Random Forest 🌲🌲\n\n### 1) 데이터만이 아니라 feature도 흔든다\n\n-   bagging의 문제 — **강한 feature 하나가 있으면 모든 트리가 그걸 먼저 씁니다.** 트리들이 닮아버림\n-   random forest는 분할할 때마다 **feature의 무작위 부분집합**만 후보로 두어, 강한 feature를 강제로 비켜 가게 함\n-   데이터 교란(bootstrap) + **속성 교란(feature sampling)** → 상관이 낮아짐 → 1절의 $\\rho$ 가 내려감\n-   보너스 — feature 일부만 봐도 되므로 결측치와 고차원에 robust, 학습도 빠름\n\n::: {.callout-warning}\n## 이 실습은 진짜 random forest가 아닙니다\n\n진짜 RF는 **split마다** feature를 다시 뽑습니다. `rpart`로는 그렇게 할 수 없어, 여기서는 **tree마다 한 번** 뽑는 **random subspace method**(Ho 1998)로 근사했습니다.\n\n차이가 중요합니다 — tree마다 뽑으면 그 트리는 나머지 feature를 **영원히** 못 봅니다. 그래서 `mtry`가 작을 때 성능이 급격히 나빠집니다. 실무에서는 `ranger::ranger()` 나 `randomForest::randomForest()` 를 쓰세요.\n:::\n\n### 2) 🧪 실습: mtry를 바꾸면 무슨 일이 일어나는가\n\n앙상블 정확도만 보지 말고, **개별 트리의 평균 정확도**와 **트리 사이의 평균 불일치도**를 같이 봅니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_single <- function(m) mean(sapply(m$trees,\n  function(t) mean(predict(t, te, type = \"class\") == te$y)))\n\ndisagreement <- function(m) {                 # 두 트리가 다르게 예측하는 비율의 평균\n  P <- sapply(m$trees, function(t) as.character(predict(t, te, type = \"class\")))\n  B <- ncol(P); s <- 0; k <- 0\n  for (i in 1:(B-1)) for (j in (i+1):B) { s <- s + mean(P[, i] != P[, j]); k <- k + 1 }\n  s / k\n}\n\nsweep <- do.call(rbind, lapply(c(2, 4, 6, 8, 10, 12), function(mt) {\n  m <- bag_fit(B = 60, mtry = if (mt == 12) NULL else mt, seed = 7)\n  data.frame(mtry         = mt,\n             ensemble     = round(mean(ens_pred(m, te) == te$y), 3),\n             mean_single  = round(mean_single(m), 3),\n             disagreement = round(disagreement(m), 3))\n}))\nsweep\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mtry ensemble mean_single disagreement\n1    2    0.690       0.546        0.486\n2    4    0.748       0.574        0.475\n3    6    0.825       0.641        0.424\n4    8    0.843       0.683        0.378\n5   10    0.835       0.703        0.336\n6   12    0.823       0.725        0.292\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong <- rbind(\n  data.frame(mtry = sweep$mtry, value = sweep$ensemble,\n             panel = \"Accuracy\", series = \"Ensemble\"),\n  data.frame(mtry = sweep$mtry, value = sweep$mean_single,\n             panel = \"Accuracy\", series = \"Mean single tree\"),\n  data.frame(mtry = sweep$mtry, value = sweep$disagreement,\n             panel = \"Diversity (pairwise disagreement)\", series = \"Disagreement\")\n)\n\nggplot(long, aes(mtry, value, colour = series)) +\n  geom_line(linewidth = .9) + geom_point(size = 1.8) +\n  facet_wrap(~ panel, scales = \"free_y\") +\n  scale_colour_manual(values = c(\"Ensemble\" = \"#d1495b\",\n                                 \"Mean single tree\" = \"#2e8b7a\",\n                                 \"Disagreement\" = \"#7d8597\")) +\n  labs(x = \"mtry (features sampled per tree)\", y = NULL, colour = NULL,\n       caption = \"B = 60 trees; mtry = 12 means no feature sampling (plain bagging)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_ensemble_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\n-   `mtry`가 커질수록 **개별 트리는 정확해지고**(0.546 → 0.725) **서로 닮습니다**(불일치도 0.486 → 0.292)\n-   앙상블 정확도는 양 끝이 아니라 **가운데 `mtry = 8`에서 최대(0.843)** 입니다\n-   `mtry = 2` — 다양성은 최대지만 개별 트리가 거의 찍는 수준(0.546)이라 앙상블도 0.690\n-   `mtry = 12`(= bagging) — 개별은 가장 정확하지만 서로 닮아 0.823\n-   ✅ **이것이 accuracy–diversity 상충의 실증입니다.** 5절 diversity 이론이 말하는 바로 그 곡선\n\n------------------------------------------------------------------------\n\n## 4. Boosting 🔁\n\n### 1) 아이디어\n\n-   일단 약한 학습기를 하나 만든 뒤, **그것이 틀린 샘플에 weight를 주어** 다음 학습기가 거기에 집중하게 함\n-   최종 결과는 마지막 학습기가 아니라 **모든 학습기의 가중 투표**\n-   bagging이 variance를 줄인다면, boosting은 **bias를 줄입니다**\n\n### 2) AdaBoost\n\n샘플 가중치 $w_i$ 를 갱신하며 $M$ 개의 약한 학습기 $h_m$ 을 순차적으로 만듭니다.\n\n$$\\epsilon_m = \\sum_i w_i \\,\\mathbb{1}[h_m(\\mathbf{x}_i) \\neq y_i], \\qquad\n\\alpha_m = \\tfrac{1}{2}\\ln\\frac{1-\\epsilon_m}{\\epsilon_m}, \\qquad\nw_i \\leftarrow \\frac{w_i \\exp(-\\alpha_m y_i h_m(\\mathbf{x}_i))}{Z}$$\n\n$$H(\\mathbf{x}) = \\mathrm{sign}\\left(\\sum_{m=1}^{M} \\alpha_m h_m(\\mathbf{x})\\right)$$\n\n-   $\\epsilon_m$ 이 작을수록 $\\alpha_m$ 이 큼 → **잘 맞춘 학습기에 큰 발언권**\n-   맞힌 샘플은 weight가 줄고, 틀린 샘플은 늘어남 ($y_i h_m = -1$ 이면 $\\exp(+\\alpha_m)$)\n\n### 3) 🧪 실습: AdaBoost를 직접 구현한다\n\n\n::: {.cell}\n\n```{.r .cell-code}\nada_fit <- function(M = 150, depth = 2, seed = 1) {\n  set.seed(seed); N <- nrow(tr); w <- rep(1/N, N)\n  lev <- levels(tr$y); ys <- ifelse(tr$y == lev[2], 1, -1)\n  ct  <- rpart.control(maxdepth = depth, cp = 0, minsplit = 2, minbucket = 1, xval = 0)\n  dd  <- tr; mods <- vector(\"list\", M); alpha <- numeric(M)\n  for (m in seq_len(M)) {\n    dd$wt <- w                                     # rpart는 weights를 data 안에서 찾는다\n    h  <- rpart(fm, data = dd, weights = wt, method = \"class\", control = ct)\n    p  <- ifelse(predict(h, dd, type = \"class\") == lev[2], 1, -1)\n    e  <- min(max(sum(w * (p != ys)), 1e-10), 1 - 1e-10)\n    a  <- 0.5 * log((1 - e) / e)\n    w  <- w * exp(-a * ys * p); w <- w / sum(w)    # 틀린 샘플의 weight를 키운다\n    mods[[m]] <- h; alpha[m] <- a\n  }\n  list(mods = mods, alpha = alpha, lev = lev)\n}\n\n# 1..M 단계까지 누적했을 때의 정확도\nstage_acc <- function(m, nd) {\n  ys <- ifelse(nd$y == m$lev[2], 1, -1); S <- rep(0, nrow(nd))\n  sapply(seq_along(m$alpha), function(i) {\n    S <<- S + m$alpha[i] * ifelse(predict(m$mods[[i]], nd, type = \"class\") == m$lev[2], 1, -1)\n    mean(sign(S) == ys)\n  })\n}\n\nada <- lapply(1:3, function(dp) ada_fit(M = 150, depth = dp))\ndo.call(rbind, lapply(1:3, function(i) {\n  trc <- stage_acc(ada[[i]], tr); tec <- stage_acc(ada[[i]], te)\n  data.frame(base_depth = i, train_acc = round(tail(trc, 1), 3),\n             test_acc   = round(tail(tec, 1), 3),\n             best_test  = round(max(tec), 3), best_M = which.max(tec))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  base_depth train_acc test_acc best_test best_M\n1          1     0.868    0.802     0.828     18\n2          2     0.948    0.818     0.835    115\n3          3     1.000    0.818     0.835    133\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nada_long <- do.call(rbind, lapply(1:3, function(i) rbind(\n  data.frame(M = 1:150, acc = stage_acc(ada[[i]], tr), set = \"Train\",\n             panel = paste0(\"base depth = \", i)),\n  data.frame(M = 1:150, acc = stage_acc(ada[[i]], te), set = \"Test\",\n             panel = paste0(\"base depth = \", i))\n)))\n\nggplot(ada_long, aes(M, acc, colour = set)) +\n  geom_line(linewidth = .8) +\n  facet_wrap(~ panel) +\n  scale_colour_manual(values = c(Train = \"#2e8b7a\", Test = \"#d1495b\")) +\n  labs(x = \"Boosting iterations (M)\", y = \"Accuracy\", colour = NULL,\n       caption = \"stronger base learner -> train accuracy reaches 1.0, test does not follow\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_ensemble_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n-   **depth 1 (stump)** — train 0.868 / test 0.802. 약한 학습기라 천천히, 안정적으로 오름\n-   **depth 2** — train 0.948 / test 0.818. 이 데이터에서 가장 좋음\n-   **depth 3** — **train이 1.0에 도달**하는데 test는 0.818에서 멈춥니다. 더 키워도 소용없음\n-   ✅ 원자료 노트의 *\"learner의 성능이 낮을 때 사용\"* 이 정확합니다. **boosting의 base learner는 약해야 합니다**\n-   ⚠️ AdaBoost는 **라벨 노이즈에 약합니다** — 잘못 붙은 라벨은 계속 틀리므로 weight가 폭주합니다\n\n### 4) Gradient boosting — 잔차를 적합한다\n\nAdaBoost를 \"손실함수를 함수공간에서 경사하강\"으로 일반화한 것입니다. 제곱오차 손실이면 음의 gradient가 곧 **잔차**입니다.\n\n$$f_0(\\mathbf{x}) = \\bar{y}, \\qquad\nr_i^{(m)} = y_i - f_{m-1}(\\mathbf{x}_i), \\qquad\nf_m(\\mathbf{x}) = f_{m-1}(\\mathbf{x}) + \\eta\\, h_m(\\mathbf{x})$$\n\n-   $h_m$ — **잔차를 목표로 적합한** 얕은 회귀 트리\n-   $\\eta$ — **learning rate (shrinkage)**. 한 걸음을 작게 밟아 과적합을 늦춤\n-   $\\eta$ 와 $M$ 은 **상충** — $\\eta$ 를 줄이면 $M$ 을 늘려야 합니다\n\n### 5) 🧪 실습: shrinkage가 하는 일\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\nnx  <- 400\ngx  <- sort(runif(nx, 0, 6)); gy <- sin(gx) + 0.4*cos(3*gx) + rnorm(nx, 0, .3)\ngi  <- sample(nx, 260)\ngtr <- data.frame(x = gx[gi],  y = gy[gi])\ngte <- data.frame(x = gx[-gi], y = gy[-gi])\n\ngb_fit <- function(dtr, M = 300, eta = 0.1, depth = 2) {\n  f0 <- mean(dtr$y); f <- rep(f0, nrow(dtr)); mods <- vector(\"list\", M)\n  ct <- rpart.control(maxdepth = depth, cp = 0, minsplit = 10, xval = 0)\n  for (m in seq_len(M)) {\n    r  <- dtr$y - f                                        # 잔차 = 음의 gradient\n    h  <- rpart(r ~ x, data = data.frame(x = dtr$x, r = r),\n                method = \"anova\", control = ct)\n    f  <- f + eta * predict(h)\n    mods[[m]] <- h\n  }\n  list(f0 = f0, mods = mods, eta = eta)\n}\n\ngb_curve <- function(g, nd) {                    # M = 1..300 에서의 test RMSE\n  P <- sapply(g$mods, function(h) predict(h, data.frame(x = nd$x)))\n  cumfit <- g$f0 + g$eta * t(apply(P, 1, cumsum))\n  sqrt(colMeans((cumfit - nd$y)^2))\n}\n\ngb_long <- do.call(rbind, lapply(c(1.0, 0.1, 0.03), function(e) {\n  g <- gb_fit(gtr, M = 300, eta = e)\n  data.frame(M = 1:300, rmse = gb_curve(g, gte), eta = sprintf(\"eta = %.2f\", e))\n}))\ngb_long$eta <- factor(gb_long$eta, levels = c(\"eta = 1.00\", \"eta = 0.10\", \"eta = 0.03\"))\n\nggplot(gb_long, aes(M, rmse, colour = eta)) +\n  geom_line(linewidth = .85) +\n  scale_colour_manual(values = c(\"eta = 1.00\" = \"#d1495b\",\n                                 \"eta = 0.10\" = \"#2e8b7a\",\n                                 \"eta = 0.03\" = \"#7d8597\")) +\n  geom_hline(yintercept = 0.3, linetype = 2, colour = \"grey40\") +\n  coord_cartesian(ylim = c(0.28, 0.65)) +\n  labs(x = \"Boosting iterations (M)\", y = \"Test RMSE\", colour = NULL,\n       caption = \"dashed = noise floor (sd = 0.3)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_ensemble_files/figure-html/unnamed-chunk-9-1.png){width=624}\n:::\n:::\n\n\n-   **$\\eta = 1.0$** — $M = 10$ 에서 0.386으로 가장 좋다가 $M = 300$ 에서 **0.459로 악화**. 학습 RMSE는 0.057까지 내려갑니다(과적합)\n-   **$\\eta = 0.1$** — 천천히 내려와 0.346에서 **평평하게 유지**\n-   **$\\eta = 0.03$** — 더 느리지만 결국 0.337로 가장 낮음. 대신 $M$ 이 많이 필요\n-   참고 — 노이즈 바닥은 0.30, 단일 깊은 트리는 0.380\n-   ✅ 실무 기본값: **작은 $\\eta$(0.01\\~0.1) + 큰 $M$ + early stopping**\n\n### 6) XGBoost / LightGBM\n\n정형 데이터에서 사실상 표준이 된 gradient boosting 구현입니다.\n\n| 요소 | 무엇을 더했나 |\n|---|---|\n| **정규화** | leaf 수와 leaf 값에 벌점 ($\\gamma$, $\\lambda$) — W6의 Ridge/Lasso가 트리로 들어온 것 |\n| **2차 근사** | gradient만이 아니라 Hessian까지 써서 분할 이득 계산 |\n| **열/행 부분추출** | `colsample_bytree`, `subsample` — random forest의 아이디어 차용 |\n| **결측치 기본 방향** | 결측을 어느 쪽 가지로 보낼지 **학습** |\n| **LightGBM** | leaf-wise 성장 + 히스토그램 분할로 대용량에서 훨씬 빠름 |\n\n주요 hyperparameter — `eta`(learning rate), `max_depth`, `min_child_weight`, `subsample`, `colsample_bytree`, `lambda`, 그리고 **`early_stopping_rounds`**. 튜닝은 W3의 nested CV 구조를 그대로 쓰면 됩니다.\n\n------------------------------------------------------------------------\n\n## 5. Combining strategy 🧩\n\n원자료에 제목만 있던 부분입니다. 결합 방법은 셋으로 나뉩니다.\n\n### 1) Averaging (회귀)\n\n-   **단순 평균** — 학습기 성능이 비슷할 때. 의외로 강력한 기준선\n-   **가중 평균** — 성능 차이가 클 때. 단, 가중치도 추정해야 하므로 **학습기가 적거나 데이터가 적으면 단순 평균이 낫습니다**\n\n### 2) Voting (분류)\n\n| 방식 | 규칙 |\n|---|---|\n| **Majority voting** | 과반을 얻은 class. 없으면 **기권** |\n| **Plurality voting** | 최다 득표 class (기권 없음). 대부분의 구현이 이것 |\n| **Weighted voting** | 학습기별 가중치를 곱해서 집계 |\n| **Soft voting** | class **확률**을 평균. 확률이 잘 보정되어 있으면 hard voting보다 낫습니다 (W4) |\n\n### 3) Stacking\n\n-   학습기의 **출력을 입력으로 받는 메타 학습기**를 학습시킴\n-   ⚠️ **누수 위험** — base learner가 training set에 과적합해 있으면 메타 학습기가 그 과적합된 예측을 믿습니다\n-   ✅ 반드시 **out-of-fold(OOF) 예측**으로 메타 학습기를 학습시킬 것. W2의 \"전처리는 fold 안에서\"와 같은 원리\n\n### 4) 🧪 실습: stacking\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(class)\n\nbase_pred <- function(train_, nd) {\n  g  <- glm(fm, data = train_, family = binomial)\n  t_ <- rpart(fm, data = train_, method = \"class\")\n  s  <- scale(train_[fe])\n  k  <- knn(s, scale(nd[fe], attr(s, \"scaled:center\"), attr(s, \"scaled:scale\")),\n            train_$y, k = 25, prob = TRUE)\n  pk <- attr(k, \"prob\")                          # 다수 class의 득표율\n  data.frame(glm  = predict(g, nd, type = \"response\"),\n             tree = predict(t_, nd, type = \"prob\")[, \"B\"],\n             knn  = ifelse(k == \"B\", pk, 1 - pk))\n}\n\nset.seed(9)\nfolds <- sample(rep(1:5, length.out = nrow(tr)))\noof   <- base_pred(tr, tr)                       # 형태만 잡아두고 fold별로 덮어쓴다\nfor (k in 1:5) oof[folds == k, ] <- base_pred(tr[folds != k, ], tr[folds == k, ])\noof$y <- tr$y\n\nmeta    <- glm(y ~ glm + tree + knn, data = oof, family = binomial)\nte_base <- base_pred(tr, te)\na       <- function(p) round(mean(ifelse(p > 0.5, \"B\", \"A\") == te$y), 3)\n\ndata.frame(\n  model    = c(\"Logistic\", \"Tree\", \"kNN (k = 25)\", \"Simple average\", \"Stacking (glm meta)\"),\n  test_acc = c(a(te_base$glm), a(te_base$tree), a(te_base$knn),\n               a(rowMeans(te_base)), a(predict(meta, te_base, type = \"response\")))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                model test_acc\n1            Logistic    0.850\n2                Tree    0.782\n3        kNN (k = 25)    0.785\n4      Simple average    0.843\n5 Stacking (glm meta)    0.845\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(coef(meta), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         glm        tree         knn \n     -3.015       5.044       0.496       0.479 \n```\n\n\n:::\n:::\n\n\n-   base learner — 로지스틱 0.850, 트리 0.782, kNN 0.785\n-   **단순 평균 0.843** — 약한 학습기 둘이 끌어내려 최고 학습기보다 낮습니다\n-   **stacking 0.845** — 메타 계수가 `glm` 5.04 vs `tree` 0.50, `knn` 0.48로 **좋은 학습기에 가중치를 몰아줍니다**\n-   ⚠️ 그런데 **로지스틱 하나(0.850)를 못 이겼습니다.** 진짜 경계가 선형이라 더 보탤 정보가 없었기 때문입니다\n\n------------------------------------------------------------------------\n\n## 6. Diversity 🎨\n\n원자료에 제목만 있던 부분이자, 앙상블을 이해하는 핵심입니다.\n\n### 1) Error-ambiguity decomposition\n\n회귀 앙상블의 오차는 다음처럼 정확히 쪼개집니다.\n\n$$E_{\\text{ensemble}} = \\bar{E} - \\bar{A}$$\n\n-   $\\bar{E}$ — 개별 학습기 오차의 **가중평균** (정확도 항)\n-   $\\bar{A}$ — 개별 예측이 앙상블 예측에서 벗어난 정도의 가중평균, 즉 **ambiguity = diversity**\n-   **다양할수록 오차가 줄어든다**는 것이 등식으로 증명됩니다\n-   단, $\\bar{E}$ 와 $\\bar{A}$ 를 따로 최적화할 수는 없습니다. 다양하게 만들면 보통 $\\bar{E}$ 도 커지니까요 → 3절의 `mtry` 곡선이 바로 이 상충입니다\n\n### 2) Diversity 측정\n\n두 학습기 $h_i, h_j$ 의 예측을 교차표로 놓고($a$ = 둘 다 맞음, $b, c$ = 하나만 맞음, $d$ = 둘 다 틀림)\n\n| 지표 | 식 | 해석 |\n|---|---|---|\n| **Disagreement** | $(b+c)/m$ | 다르게 예측한 비율. 클수록 다양 (3절에서 쓴 것) |\n| **Q-statistic** | $\\dfrac{ad-bc}{ad+bc}$ | −1\\~1. 0에 가까울수록 독립 |\n| **Correlation** | $\\dfrac{ad-bc}{\\sqrt{(a+b)(c+d)(a+c)(b+d)}}$ | 1절의 $\\rho$ 에 해당 |\n| **$\\kappa$-statistic** | 우연 일치를 보정한 일치도 | $\\kappa$–error diagram으로 시각화 |\n\n### 3) Diversity를 만드는 네 가지 교란\n\n| 교란 대상 | 방법 | 예 |\n|---|---|---|\n| **데이터** | 샘플을 다르게 | Bagging, AdaBoost의 weight |\n| **속성** | feature를 다르게 | **Random forest**, random subspace |\n| **파라미터** | 초기값·구조를 다르게 | 신경망 seed, 트리 깊이 섞기 |\n| **출력** | label 표현을 다르게 | ECOC (W6), flipping output |\n\n-   실무에서는 **여러 개를 동시에** 씁니다. random forest = 데이터 + 속성 교란\n-   heterogeneous ensemble(트리 + 선형 + kNN)은 **알고리즘 자체를 교란**하는 가장 강한 방법이고, 그래서 stacking과 궁합이 좋습니다\n\n::: {.callout-warning}\n## ⚠️ 앙상블을 논문에 쓸 때\n\n-   **단일 모델과 반드시 비교할 것.** 이 챕터의 데이터처럼 로지스틱 하나가 이기는 경우가 실제로 흔합니다\n-   **OOB를 test set처럼 쓰지 말 것** — hyperparameter를 OOB로 고르면 OOB는 더 이상 unbiased가 아닙니다\n-   **boosting에서 M은 hyperparameter입니다** — 반드시 validation으로 early stopping\n-   stacking의 메타 학습기는 **OOF 예측으로만** 학습 (누수)\n-   변수 중요도는 앙상블에서도 **상관된 feature에 취약**합니다 (W14)\n-   해석이 필요하면 성능과 맞바꾸는 것임을 인정하고 **SHAP 같은 사후 설명**을 붙일 것 (W14)\n:::\n\n::: {.callout-important}\n## Where this ends up\n\n-   앙상블이 우회한 **비선형 경계를 kernel로 정면돌파** → W10\n-   Bagging의 평균이 variance를 줄이는 이유는 W4의 **bias–variance 분해** 그 자체\n-   XGBoost의 leaf 벌점 $\\lambda$ 는 W6의 **Ridge**와 같은 것\n-   트리 기반 변수 중요도, permutation importance, SHAP → W14\n-   오믹스에서 RF로 feature selection할 때의 함정 → W14\n:::\n\n------------------------------------------------------------------------\n\n## 📝 Summary\n\n-   앙상블의 이론적 근거는 **개별 오차의 독립성** — 독립이면 $T$ 에 대해 오차가 지수적으로 감소\n-   실습 — 개별 오차 0.4가 독립 51개면 **0.074**, 상관 0.3이면 **0.329에서 멈춤**. 독립성이 전부입니다\n-   **Bagging** — bootstrap으로 데이터를 흔들어 **variance ↓**. 단일 트리 0.782 → 0.828. base learner는 **깊은 트리**\n-   **OOB** — bootstrap에서 빠지는 $1/e \\approx 0.368$ 로 공짜 validation. 실습에서 0.368 정확히 관측\n-   **Random forest** — 데이터 + **속성** 교란. `mtry` 2→12에서 개별 정확도 0.546→0.725, 불일치도 0.486→0.292, 앙상블은 **가운데 `mtry = 8`에서 0.843 최대**\n-   **Boosting** — 순차적으로 틀린 샘플에 집중해 **bias ↓**. base learner는 **약해야** 함 (depth 3은 train 1.0인데 test는 제자리)\n-   **Gradient boosting** — 잔차를 적합. $\\eta = 1.0$ 은 $M=300$ 에서 RMSE 0.459로 악화, $\\eta = 0.1$ 은 0.346에서 안정\n-   **Stacking** — 반드시 **OOF 예측**으로 메타 학습기 학습. 좋은 학습기에 가중치가 몰림(glm 계수 5.04)\n-   **$E_{\\text{ensemble}} = \\bar{E} - \\bar{A}$** — 정확도와 다양성의 상충이 앙상블의 전부\n-   ⚠️ **앙상블은 만능이 아닙니다.** 이 데이터에서는 로지스틱 하나(0.850)가 최고였습니다\n\n## 🔑 Key terms\n\n| 용어 | 정의 |\n|------|------|\n| **Base / component learner** | homogeneous / heterogeneous 앙상블의 개별 학습기 |\n| **Hoeffding 상한** | 독립 가정에서 다수결 오차의 지수적 상한 |\n| **Bagging** | 부트스트랩 표본마다 학습기를 만들어 평균·투표. variance ↓ |\n| **OOB** | 부트스트랩에서 빠진 약 36.8%로 계산하는 공짜 generalization 추정 |\n| **mtry** | 분할 후보로 뽑는 feature 수. 작을수록 다양성 ↑, 개별 정확도 ↓ |\n| **Random subspace** | tree마다 feature 부분집합을 뽑는 방법. RF는 split마다 뽑음 |\n| **AdaBoost** | 틀린 샘플의 weight를 키우며 $\\alpha_m$ 가중 투표로 결합 |\n| **Gradient boosting** | 잔차(음의 gradient)를 순차적으로 적합 |\n| **Shrinkage ($\\eta$)** | boosting의 한 걸음 크기. 작을수록 robust, $M$ 은 더 필요 |\n| **Soft voting** | class 확률을 평균하는 투표. 보정이 잘 되어 있을 때 유리 |\n| **Stacking** | base learner의 OOF 예측을 입력으로 받는 메타 학습기 |\n| **Error-ambiguity** | $E_{\\text{ensemble}} = \\bar{E} - \\bar{A}$. 다양성이 오차를 깎는다 |\n| **Disagreement / Q-statistic** | 학습기 쌍의 다양성 측정 지표 |\n\n## ➕ References\n\n-   Dietterich TG. Ensemble methods in machine learning. *MCS 2000*, LNCS 1857:1–15.\n-   Breiman L. Bagging predictors. *Machine Learning* 1996;24(2):123–140.\n-   Breiman L. Random forests. *Machine Learning* 2001;45(1):5–32.\n-   Ho TK. The random subspace method for constructing decision forests. *IEEE TPAMI* 1998;20(8):832–844.\n-   Freund Y, Schapire RE. A decision-theoretic generalization of on-line learning and an application to boosting. *JCSS* 1997;55(1):119–139.\n-   Friedman JH. Greedy function approximation: a gradient boosting machine. *Annals of Statistics* 2001;29(5):1189–1232.\n-   Chen T, Guestrin C. XGBoost: a scalable tree boosting system. *KDD 2016*:785–794.\n-   Wolpert DH. Stacked generalization. *Neural Networks* 1992;5(2):241–259.\n-   Krogh A, Vedelsby J. Neural network ensembles, cross validation, and active learning. *NIPS 1994*:231–238.\n-   Kuncheva LI, Whitaker CJ. Measures of diversity in classifier ensembles. *Machine Learning* 2003;51(2):181–207.\n\n------------------------------------------------------------------------\n\n[← W7. Decision Tree](07_decision_tree.qmd)\n",
    "supporting": [
      "09_ensemble_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}