{
  "hash": "c580d7a618127d6de7e48ac48f57e513",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"W4. 성능 척도와 모델 비교\"\ndescription: \"Confusion matrix, ROC·PR, calibration, 모델 비교 검정, bias-variance\"\nauthor: \"Eunji Ha\"\ndate: today\n\n# ── AI 채팅 위젯 설정 ──────────────────────────────────────────\nformat:\n  html:\n    include-in-header:\n      text: |\n        <meta name=\"ai-title\" content=\"W4. 성능 척도와 모델 비교\">\n        <meta name=\"ai-context\" content=\"\n        이 챕터는 분류·회귀 모델의 성능 척도와 모델 간 비교 방법을 다룹니다.\n        Confusion matrix에서 recall(sensitivity), precision, specificity, NPV가 유도되고,\n        precision과 recall의 trade-off, P-R curve, break-even point, F1과 F-beta,\n        macro/micro 평균을 설명합니다.\n        ROC curve는 FPR-TPR 평면의 곡선이고 AUC로 요약되지만,\n        class imbalance에서는 ROC-AUC가 실제보다 후하게 나옵니다.\n        유병률 2% 데이터에서 ROC-AUC 0.85인 모델도 recall 80%를 얻으려면\n        637명을 검사해 36명만 찾게 되어 precision이 0.057에 불과합니다.\n        따라서 불균형에서는 PR-AUC(average precision)를 함께 봐야 합니다 (Saito & Rehmsmeier 2015).\n        Calibration은 판별력과 다른 축입니다. 다운샘플링으로 균형을 맞춰 학습하면\n        ROC-AUC는 그대로 0.801인데 평균 예측확률이 실제 유병률 0.043에서 0.361로 튀고\n        Brier score가 0.038에서 0.187로 악화됩니다 (Van Calster et al. 2019).\n        모델 비교에는 paired t-test(교차검증 fold 간 상관 때문에 주의),\n        McNemar 검정, 여러 모델·데이터셋 비교에는 Friedman + Nemenyi를 씁니다\n        (Dietterich 1998, Demsar 2006, Nadeau & Bengio 2003).\n        Generalization error는 bias^2 + variance + noise로 분해되며,\n        모델 복잡도가 증가하면 bias는 줄고 variance는 커지는 bias-variance dilemma가 생깁니다.\n        \">\n---\n\n::: {.callout-note}\n## 🎯 Learning objectives\n\n-   Confusion matrix에서 파생 지표를 유도하고 상황에 맞게 고를 수 있다\n-   Precision-recall trade-off와 임계값의 역할을 설명할 수 있다\n-   **불균형 데이터에서 ROC-AUC가 왜 후한지 설명하고 PR-AUC를 쓸 수 있다**\n-   **판별력과 보정(calibration)을 구분하고 Brier score로 평가할 수 있다**\n-   모델 간 성능 차이가 우연인지 검정할 수 있다\n-   Generalization error를 bias·variance·noise로 분해해 해석할 수 있다\n:::\n\n> 🤔 **ROC-AUC 0.85인 모델로 환자의 80%를 찾으려면, 몇 명을 검사해야 할까?**\n\n------------------------------------------------------------------------\n\n## 1. 기본 척도와 그 함정 📊\n\n### 1) Error rate와 accuracy\n\n-   **Error rate** — 잘못 분류한 샘플 수 / 전체 샘플 수\n-   **Accuracy** — 1 − error rate\n-   장점 — 직관적, 계산 간단\n-   한계 — **class 분포를 전혀 반영하지 않음**\n\n### 2) ⚠️ Accuracy paradox\n\n-   유병률 2% 질환에서 \"전원 음성\"이라고 답하는 모델\n-   Accuracy = 98%. 환자는 **한 명도** 찾지 못함\n-   → 불균형 데이터에서 accuracy는 **보고하지 않는 편이 낫다**\n\n------------------------------------------------------------------------\n\n## 2. Confusion matrix 🔲\n\n### 1) 네 칸\n\n|  | 예측 Positive | 예측 Negative |\n|---|---|---|\n| **실제 Positive** | TP (True Positive) | FN (False Negative) |\n| **실제 Negative** | FP (False Positive) | TN (True Negative) |\n\n### 2) 파생 지표\n\n| 지표 | 식 | 읽는 법 |\n|------|-----|--------|\n| **Recall / Sensitivity** | TP / (TP + FN) | 실제 양성 중 몇 %를 잡았나 |\n| **Specificity** | TN / (TN + FP) | 실제 음성 중 몇 %를 통과시켰나 |\n| **Precision / PPV** | TP / (TP + FP) | 양성이라 한 것 중 몇 %가 진짜인가 |\n| **NPV** | TN / (TN + FN) | 음성이라 한 것 중 몇 %가 진짜인가 |\n| **FPR** | FP / (FP + TN) = 1 − specificity | 위양성률 |\n\n-   **Recall과 specificity** — 실제 class를 기준으로 계산. 유병률과 무관\n-   **Precision과 NPV** — 예측을 기준으로 계산. **유병률에 크게 의존**\n\n### 3) 무엇을 볼 것인가\n\n| 상황 | 중요한 지표 | 이유 |\n|------|-----------|------|\n| 선별검사(screening) | Recall ↑ | 놓치면 안 됨. 위양성은 확진검사로 걸러냄 |\n| 확진·치료 결정 | Precision ↑ | 잘못된 양성의 대가가 큼 |\n| 바이오마커 패널 후보 선정 | Precision ↑ | 후속 실험 자원이 한정 |\n| 자원 배분 (검사 100건) | Precision @ top-k | 실제 운영 조건과 일치 |\n\n-   **하나의 숫자로 요약하기 전에, 이 모델이 어떻게 쓰일지를 먼저 정할 것**\n\n------------------------------------------------------------------------\n\n## 3. Precision-Recall과 F score ⚖️\n\n### 1) Trade-off\n\n-   임계값을 낮추면 — 양성 판정 증가 → recall ↑, precision ↓\n-   임계값을 높이면 — recall ↓, precision ↑\n-   **둘은 원리적으로 동시에 최대화되지 않음**\n\n### 2) P-R curve와 BEP\n\n-   임계값을 연속적으로 바꾸며 (recall, precision)을 그린 곡선\n-   곡선 아래 면적이 클수록 좋음 → 성능 비교 가능\n-   **Break-even point (BEP)** — precision = recall 이 되는 지점\n-   BEP는 간편하지만 **너무 단순** — precision과 recall의 상대 중요도를 반영 못 함\n\n### 3) F1과 Fβ\n\n$$F_1 = \\frac{2 \\cdot P \\cdot R}{P + R}, \\qquad F_\\beta = \\frac{(1+\\beta^2)\\, P \\cdot R}{\\beta^2 P + R}$$\n\n-   $F_1$ — precision과 recall의 **조화평균**. 한쪽이 낮으면 크게 벌점\n-   $\\beta$ — precision 대비 **recall의 상대적 중요도**\n    -   $\\beta > 1$ → recall 중시 (선별검사)\n    -   $\\beta < 1$ → precision 중시 (확진)\n-   ⚠️ F score는 **TN을 전혀 쓰지 않음** — 음성을 잘 거르는 능력은 반영 안 됨\n\n### 4) Macro / micro\n\n-   다중 class 또는 반복 검증에서 평균 내는 두 방식\n-   **Micro** — 모든 fold·class의 TP/FP/FN을 합산한 뒤 지표 계산\n    -   샘플이 많은 class의 영향이 큼\n-   **Macro** — class·fold별로 지표를 계산한 뒤 평균\n    -   **희귀 class에 동등한 가중치** → 불균형에서는 보통 macro\n-   보고 시 어느 쪽인지 반드시 명시\n\n------------------------------------------------------------------------\n\n## 4. ROC, AUC, 그리고 불균형 📈\n\n### 1) 임계값을 바꾼다는 것\n\n-   대부분의 분류기는 0/1이 아니라 **연속 점수**를 출력\n-   임계값 하나를 고정하면 정보가 손실됨\n-   → 모든 임계값에 걸쳐 성능을 요약하는 곡선이 필요\n\n### 2) ROC와 AUC\n\n-   **ROC curve** — x축 FPR, y축 TPR(= recall)\n-   **AUC** — 곡선 아래 면적\n-   해석 — **무작위로 뽑은 양성 1명이 음성 1명보다 높은 점수를 받을 확률**\n-   0.5 = 무작위, 1.0 = 완전 분리\n-   장점 — 임계값·유병률과 무관하게 **순위 능력**만 평가\n\n### 3) ⚠️ 불균형에서 ROC-AUC는 후하다\n\n-   FPR의 분모는 TN + FP. 음성이 압도적으로 많으면 **FP가 꽤 늘어도 FPR은 거의 안 움직임**\n-   결과 — ROC 곡선은 좋아 보이는데, 실제 양성 판정 목록은 위양성투성이\n-   PR curve는 분모에 TN이 없어 이 문제에 영향받지 않음\n-   **PR-AUC의 기준선은 0.5가 아니라 유병률** — 보고 시 함께 제시할 것\n\n### 4) 🧪 실습: 같은 모델, 두 개의 그림\n\n-   샘플 2,000명, 유병률 약 2%\n-   양성은 점수 분포가 평균 1.5만큼 높음 (현실적인 수준의 신호)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nset.seed(2026)\nn <- 2000\nlabel <- rbinom(n, 1, 0.02)\nscore <- rnorm(n, mean = ifelse(label == 1, 1.5, 0))\n\n# ROC-AUC = 양성이 음성보다 높은 점수를 받을 확률 (Mann-Whitney)\nauc_roc <- function(s, l) {\n  r <- rank(s); n1 <- sum(l == 1); n0 <- sum(l == 0)\n  (sum(r[l == 1]) - n1 * (n1 + 1) / 2) / (n1 * n0)\n}\n# PR-AUC = average precision\navg_prec <- function(s, l) {\n  o <- order(s, decreasing = TRUE); y <- l[o]\n  tp <- cumsum(y == 1)\n  sum((tp / seq_along(y))[y == 1]) / sum(l == 1)\n}\n\ndata.frame(\n  prevalence  = round(mean(label), 3),\n  n_positive  = sum(label),\n  ROC_AUC     = round(auc_roc(score, label), 3),\n  PR_AUC      = round(avg_prec(score, label), 3),\n  PR_baseline = round(mean(label), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  prevalence n_positive ROC_AUC PR_AUC PR_baseline\n1      0.022         44   0.849  0.314       0.022\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\no <- order(score, decreasing = TRUE); y <- label[o]\ntp <- cumsum(y == 1); fp <- cumsum(y == 0)\nprev <- mean(label)\n\ncurves <- rbind(\n  data.frame(panel = sprintf(\"ROC  (AUC = %.3f)\", auc_roc(score, label)),\n             x = fp / sum(label == 0), y = tp / sum(label), type = \"model\"),\n  data.frame(panel = sprintf(\"Precision-Recall  (AP = %.3f)\", avg_prec(score, label)),\n             x = tp / sum(label), y = tp / seq_along(y), type = \"model\")\n)\nrefs <- rbind(\n  data.frame(panel = sprintf(\"ROC  (AUC = %.3f)\", auc_roc(score, label)),\n             x = c(0, 1), y = c(0, 1), type = \"baseline\"),\n  data.frame(panel = sprintf(\"Precision-Recall  (AP = %.3f)\", avg_prec(score, label)),\n             x = c(0, 1), y = c(prev, prev), type = \"baseline\")\n)\n\nplot_df <- rbind(curves, refs)\nplot_df$panel <- factor(plot_df$panel, levels = unique(curves$panel))  # ROC를 왼쪽에\n\nggplot(plot_df, aes(x, y, linetype = type)) +\n  geom_line(linewidth = .8, colour = \"#d1495b\") +\n  facet_wrap(~ panel, scales = \"free_x\") +\n  scale_linetype_manual(values = c(model = 1, baseline = 2)) +\n  labs(x = NULL, y = NULL, linetype = NULL,\n       caption = \"left: FPR vs TPR   |   right: Recall vs Precision (dashed = prevalence)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04_metrics_files/figure-html/unnamed-chunk-2-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 실제 운영 조건으로 환산하면?\nrecall <- tp / sum(label); precision <- tp / seq_along(y)\ndo.call(rbind, lapply(c(0.3, 0.5, 0.8), function(r) {\n  i <- which(recall >= r)[1]\n  data.frame(target_recall = r, n_tested = i,\n             true_positives = tp[i], precision = round(precision[i], 3))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  target_recall n_tested true_positives precision\n1           0.3       49             14     0.286\n2           0.5       91             22     0.242\n3           0.8      637             36     0.057\n```\n\n\n:::\n:::\n\n\n-   **ROC-AUC 0.849** — 논문이라면 \"우수한 판별력\"으로 쓰일 숫자\n-   그러나 환자의 **80%를 찾으려면 637명을 검사해 36명**을 얻음 → precision 0.057\n-   같은 모델, 같은 데이터. **지표 선택만 바꿔도 결론이 뒤집힘**\n\n------------------------------------------------------------------------\n\n## 5. 확률을 믿을 수 있는가 — Calibration 🎯\n\n### 1) 판별력 ≠ 보정\n\n-   **Discrimination(판별력)** — 양성을 음성보다 높게 매기는 능력. ROC-AUC가 측정\n-   **Calibration(보정)** — \"위험도 20%\"라고 한 환자들 중 실제로 20%가 발병하는가\n-   **둘은 독립적** — 모든 확률에 같은 상수를 곱해도 AUC는 변하지 않음\n-   임상 의사결정·자원 배분에는 **확률의 절대값**이 필요 → 보정이 필수\n\n### 2) Calibration plot과 Brier score\n\n-   **Calibration plot** — 예측확률을 구간별로 묶어 (평균 예측확률, 실제 발생률)을 그림\n    -   대각선에 붙을수록 좋음\n-   **Brier score** — $\\frac{1}{n}\\sum (p_i - y_i)^2$\n    -   낮을수록 좋음. 판별력과 보정을 **함께** 반영\n\n### 3) 🧪 실습: 균형을 맞춰 학습한 대가\n\n-   불균형이 싫어서 다수 class를 다운샘플링해 1:1로 맞춘 뒤 학습하는 관행\n-   판별력은 유지되지만 **확률이 통째로 이동**함\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nn <- 4000\nx <- rnorm(n)\np_true <- plogis(-4 + 1.5 * x)          # 실제 유병률이 낮은 상황\ny <- rbinom(n, 1, p_true)\nd <- data.frame(x, y)\ntr <- 1:2000; te <- 2001:4000\n\n# ① 원래 분포 그대로 학습\nm_plain <- glm(y ~ x, data = d[tr, ], family = binomial)\n\n# ② 다수 class를 다운샘플링해 1:1로 맞춰 학습\npos <- tr[d$y[tr] == 1]\nneg <- sample(tr[d$y[tr] == 0], length(pos))\nm_bal <- glm(y ~ x, data = d[c(pos, neg), ], family = binomial)\n\np1 <- predict(m_plain, d[te, ], type = \"response\")\np2 <- predict(m_bal,   d[te, ], type = \"response\")\nbrier <- function(p, y) mean((p - y)^2)\n\ndata.frame(\n  model       = c(\"Original distribution\", \"Downsampled to 1:1\"),\n  mean_pred   = round(c(mean(p1), mean(p2)), 3),\n  observed    = round(mean(d$y[te]), 3),\n  ROC_AUC     = round(c(auc_roc(p1, d$y[te]), auc_roc(p2, d$y[te])), 3),\n  Brier       = round(c(brier(p1, d$y[te]), brier(p2, d$y[te])), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  model mean_pred observed ROC_AUC  Brier\n1 Original distribution     0.044    0.043   0.801 0.0375\n2    Downsampled to 1:1     0.361    0.043   0.801 0.1866\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncal <- function(p, lab, name, bins = 10) {\n  g <- cut(p, quantile(p, seq(0, 1, length.out = bins + 1)),\n           include.lowest = TRUE)\n  data.frame(model = name,\n             predicted = tapply(p, g, mean),\n             observed  = tapply(lab, g, mean))\n}\ncal_df <- rbind(cal(p1, d$y[te], \"Original distribution\"),\n                cal(p2, d$y[te], \"Downsampled to 1:1\"))\n\nggplot(cal_df, aes(predicted, observed, colour = model)) +\n  geom_abline(linetype = 2) +\n  geom_line(linewidth = .8) + geom_point(size = 1.8) +\n  scale_colour_manual(values = c(\"Original distribution\" = \"#2e8b7a\",\n                                 \"Downsampled to 1:1\"    = \"#d1495b\")) +\n  labs(x = \"Mean predicted probability\", y = \"Observed frequency\", colour = NULL,\n       caption = \"dashed = perfect calibration\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04_metrics_files/figure-html/unnamed-chunk-5-1.png){width=624}\n:::\n:::\n\n\n-   **ROC-AUC는 두 모델이 동일 (0.801)** — 순위를 바꾸지 않았으므로 당연\n-   그러나 평균 예측확률은 실제 0.043 대비 **0.361로 8배 과대**\n-   Brier score는 0.038 → 0.187로 악화\n-   → 재샘플링은 **임계값 조정의 한 형태**일 뿐, 확률을 개선하지 않음\n\n::: {.callout-warning}\n## ⚠️ W6 class imbalance 처리와 직결\n\n-   SMOTE·다운샘플링 후 예측확률을 그대로 임상 위험도로 보고하는 것은 오류\n-   판별력만 필요하면 문제없음. **확률이 필요하면 반드시 재보정**\n:::\n\n### 4) 보정 방법\n\n-   **Platt scaling** — 예측 점수에 로지스틱 회귀를 한 번 더 적용\n-   **Isotonic regression** — 단조 증가 제약만 두는 비모수 보정\n-   ⚠️ 보정도 **학습이므로 별도 데이터(또는 fold 안)에서** 수행할 것\n\n------------------------------------------------------------------------\n\n## 6. 회귀 지표 📏\n\n| 지표 | 특징 | 주의 |\n|------|------|------|\n| **RMSE** | 원래 단위, 큰 오차에 민감 | 이상치에 크게 흔들림 |\n| **MAE** | 원래 단위, 이상치에 robust | 미분 불가점 존재 |\n| **R²** | 설명된 분산 비율 | test set에서는 음수 가능 |\n| **MAPE** | 상대 오차(%) | 실제값이 0 근처면 폭발 |\n\n-   발현량·농도처럼 **로그 스케일이 자연스러운 값**은 로그 변환 후 평가\n-   지표는 **의사결정 비용**을 반영해 고를 것 — 과대예측과 과소예측의 대가가 다르면 비대칭 손실\n\n------------------------------------------------------------------------\n\n## 7. 모델 비교 🆚\n\n### 1) 차이가 우연인가\n\n-   모델 A가 0.82, 모델 B가 0.79 — **이 차이는 재현되는가?**\n-   교차검증 점수에는 분할 우연에 의한 변동이 섞여 있음\n-   점수 하나만 비교하는 것은 근거가 되지 못함\n\n### 2) Paired t-test\n\n-   같은 fold에서 두 모델의 성능 차이를 쌍으로 비교\n-   ⚠️ **교차검증 fold는 서로 독립이 아님** — training set이 대부분 겹침\n-   → 표준 paired t-test는 **1종 오류가 부풀려짐**\n-   대안 — corrected resampled t-test (Nadeau & Bengio 2003)\n\n### 3) McNemar 검정\n\n-   **같은 test set**에서 두 모델의 예측이 갈린 샘플만 사용\n-   두 분류기를 한 번씩만 학습해도 적용 가능\n-   불일치 쌍 (A만 맞음, B만 맞음)의 비대칭성을 검정\n\n### 4) Friedman + Nemenyi\n\n-   **여러 모델 × 여러 데이터셋**을 동시에 비교할 때\n-   Friedman — 모델 간 순위에 차이가 있는지 (비모수)\n-   유의하면 Nemenyi 사후검정 → critical difference diagram\n-   벤치마크 논문의 표준 절차 (Demšar 2006)\n\n### 5) ⚠️ 다중 비교\n\n-   모델 10개를 비교하면 우연히 \"유의한\" 차이가 나옴\n-   다중비교 보정 필수\n-   **성능 차이가 작으면, 단순한 모델을 고르는 것이 정당** (Occam's razor, W1)\n\n------------------------------------------------------------------------\n\n## 8. Bias-Variance Decomposition 🎲\n\n### 1) 세 성분\n\n-   같은 분포에서 뽑아도 training set이 달라지면 모델이 달라짐\n-   **Variance** — training set 표집에 의한 예측값의 흔들림\n-   **Bias** — 학습된 모델의 기대 예측값과 실제값의 차이\n-   **Noise** — 가진 변수로는 설명 불가능한 부분. **문제 자체의 난이도**\n    -   기댓값 0으로 가정. 어떤 모델로도 줄일 수 없는 **하한**\n\n### 2) 분해식\n\n$$\\mathbb{E}\\left[(y - \\hat f(x))^2\\right] = \\underbrace{\\text{Bias}^2}_{\\text{모델의 한계}} + \\underbrace{\\text{Variance}}_{\\text{표집의 흔들림}} + \\underbrace{\\sigma^2}_{\\text{줄일 수 없음}}$$\n\n### 3) Bias-variance dilemma\n\n-   모델을 단순하게 → bias ↑, variance ↓ → **underfitting**\n-   모델을 복잡하게 → bias ↓, variance ↑ → **overfitting**\n-   generalization error를 최소화하는 **중간 지점**이 존재\n-   W3에서 본 복잡도 곡선의 U자 형태가 바로 이것\n\n### 4) 🧪 실습: 분해를 눈으로 보기\n\n-   진짜 함수 $f(x) = \\sin(2x)$, 잡음 $\\sigma = 0.5$ → 이론적 하한 $\\sigma^2 = 0.25$\n-   training set 200개를 새로 뽑아가며 깊이별로 트리를 적합\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rpart)\nlibrary(tidyr)\n\nset.seed(2026)\nf <- function(x) sin(2 * x); sigma <- 0.5\nx_grid <- seq(-2.5, 2.5, length.out = 60)\n\nbv <- do.call(rbind, lapply(1:8, function(depth) {\n  # 같은 분포에서 training set을 200번 새로 뽑아 예측을 모음\n  P <- sapply(1:200, function(b) {\n    xt <- runif(80, -2.5, 2.5)\n    dt <- data.frame(x = xt, y = f(xt) + rnorm(80, sd = sigma))\n    m <- rpart(y ~ x, dt,\n               control = rpart.control(maxdepth = depth, cp = 0, minsplit = 2))\n    predict(m, data.frame(x = x_grid))\n  })\n  data.frame(depth    = depth,\n             bias2    = mean((rowMeans(P) - f(x_grid))^2),\n             variance = mean(apply(P, 1, var)),\n             noise    = sigma^2)\n}))\nbv$total <- bv$bias2 + bv$variance + bv$noise\nround(bv, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  depth bias2 variance noise total\n1     1 0.342    0.094  0.25 0.686\n2     2 0.153    0.186  0.25 0.589\n3     3 0.020    0.131  0.25 0.401\n4     4 0.005    0.129  0.25 0.384\n5     5 0.001    0.153  0.25 0.404\n6     6 0.001    0.186  0.25 0.437\n7     7 0.001    0.214  0.25 0.465\n8     8 0.001    0.235  0.25 0.487\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong <- pivot_longer(bv, c(bias2, variance, noise, total),\n                     names_to = \"component\", values_to = \"value\")\n\nggplot(long, aes(depth, value, colour = component)) +\n  geom_line(linewidth = .9) + geom_point(size = 1.6) +\n  geom_vline(xintercept = bv$depth[which.min(bv$total)], linetype = 2) +\n  scale_colour_manual(values = c(bias2 = \"#2e8b7a\", variance = \"#d1495b\",\n                                 noise = \"grey55\",  total = \"black\")) +\n  labs(x = \"Tree depth (model complexity)\", y = \"Expected squared error\",\n       colour = NULL, caption = \"dashed = minimum total error\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04_metrics_files/figure-html/unnamed-chunk-7-1.png){width=624}\n:::\n:::\n\n\n-   **bias²** — 깊이가 늘수록 급격히 0으로 수렴\n-   **variance** — 깊이가 늘수록 계속 증가\n-   **noise** — 0.25에서 수평. **어떤 모델도 이 아래로 못 감**\n-   **total** — 둘의 합이 만드는 U자. 최소 지점이 최적 복잡도\n-   W9의 ensemble은 이 그림에서 **variance를 깎는 전략**(bagging)과 **bias를 깎는 전략**(boosting)으로 나뉨\n\n::: {.callout-important}\n## Where this ends up\n\n-   불균형 처리 → W6 (class imbalance, threshold moving)\n-   Variance 감소 → W9 bagging·random forest\n-   Bias 감소 → W9 boosting\n-   보정과 보고 지침 → W14 (TRIPOD+AI)\n:::\n\n------------------------------------------------------------------------\n\n## 📝 Summary\n\n-   **Accuracy는 불균형에서 쓰지 말 것** — 전원 음성으로 98%가 나옴\n-   Recall·specificity는 유병률과 무관, **precision·NPV는 유병률에 크게 의존**\n-   지표는 **모델이 어떻게 쓰일지**를 정한 뒤에 고른다\n-   F score는 TN을 쓰지 않음. 불균형 다중 class 평균은 보통 macro\n-   **ROC-AUC는 불균형에서 후하다** — AUC 0.849인 모델의 실제 precision은 0.057\n-   PR-AUC를 함께 보고하고, **기준선이 유병률**임을 명시\n-   **판별력과 보정은 다른 축** — 다운샘플링은 AUC를 유지한 채 확률을 8배 부풀림\n-   모델 비교는 검정으로 — CV fold는 독립이 아니므로 corrected t-test 또는 McNemar\n-   Generalization error = **bias² + variance + noise**, noise는 줄일 수 없는 하한\n\n## 🔑 Key terms\n\n| 용어 | 정의 |\n|------|------|\n| **Recall / Sensitivity** | 실제 양성 중 맞게 잡아낸 비율 |\n| **Precision / PPV** | 양성으로 예측한 것 중 실제 양성 비율 |\n| **Fβ score** | precision·recall의 가중 조화평균. β>1이면 recall 중시 |\n| **ROC curve / AUC** | FPR-TPR 곡선과 그 아래 면적. 순위 능력 |\n| **PR-AUC (AP)** | recall-precision 곡선 면적. 기준선은 유병률 |\n| **Calibration** | 예측확률이 실제 발생률과 일치하는 정도 |\n| **Brier score** | 예측확률과 실제값 차이의 제곱 평균. 낮을수록 좋음 |\n| **McNemar test** | 같은 test set에서 두 분류기의 불일치 쌍을 비교 |\n| **Bias² / Variance / Noise** | 모델의 한계 / 표집의 흔들림 / 줄일 수 없는 하한 |\n\n## ➕ References\n\n-   Dietterich TG. Approximate statistical tests for comparing supervised classification learning algorithms. *Neural Computation* 1998;10(7):1895–1923.\n-   Nadeau C, Bengio Y. Inference for the generalization error. *Machine Learning* 2003;52(3):239–281.\n-   Demšar J. Statistical comparisons of classifiers over multiple data sets. *JMLR* 2006;7:1–30.\n-   Saito T, Rehmsmeier M. The precision-recall plot is more informative than the ROC plot when evaluating binary classifiers on imbalanced datasets. *PLoS ONE* 2015;10(3):e0118432.\n-   Van Calster B, McLernon DJ, van Smeden M, Wynants L, Steyerberg EW. Calibration: the Achilles heel of predictive analytics. *BMC Medicine* 2019;17:230.\n-   Collins GS, Moons KGM, Dhiman P, et al. TRIPOD+AI statement: updated guidance for reporting clinical prediction models. *BMJ* 2024;385:e078378.\n-   Hastie T, Tibshirani R, Friedman J. *The Elements of Statistical Learning.* 2nd ed., Ch. 7. Springer, 2009.\n\n------------------------------------------------------------------------\n\n[← W3. 검증 설계](03_validation.qmd)\n",
    "supporting": [
      "04_metrics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}